# fools2022 - autogenerated map file, please do not change!
# created from: pokeemerald/data/maps/x0565_GlitchResearchLab/map.json

.thumb
.include "include/constants.inc"
.org MAP_LOAD_BASE

.include "include/macros.inc"
.include "include/symbols.inc"
.include "include/map.inc"
.include "include/event.inc"
.include "include/save.inc"

GlitchResearchLab_MapHeader:
    .word GlitchResearchLab_MapLayout
    .word GlitchResearchLab_MapEvts
    .word NULL
    .word NULL
    .hword MUS_BIRCH_LAB
    .hword 0
    .byte 0
    .byte 0
    .byte WEATHER_NONE
    .byte 0
    .hword 0
    map_header_flags allow_cycling=1, allow_escaping=1, allow_running=1, show_map_name=1
    .byte 0
    # additional data specific to fools2022 maps
    .word GlitchResearchLab_MapInitCode+1
    .word GlitchResearchLab_MapConnections
    .word GlitchResearchLab_MapInitScript
    .word GlitchResearchLab_MapName
    .word 0x2819

GlitchResearchLab_MapLayout:
    .word 17
    .word 13
    .word GlitchResearchLab_MapBorder
    .word GlitchResearchLab_MapData
    .word gTileset_Building
    .word gTileset_Lab

.align 4
GlitchResearchLab_MapObjectEvents:
    object_event 1, OBJ_EVENT_GFX_SCIENTIST_1, 0, 13, 7, 3, MOVEMENT_TYPE_FACE_UP, 0, 0, TRAINER_TYPE_NONE, 0, GlitchResearchLab_Scientist3, 0
    object_event 2, OBJ_EVENT_GFX_SCIENTIST_2, 0, 12, 10, 3, MOVEMENT_TYPE_WANDER_LEFT_AND_RIGHT, 1, 0, TRAINER_TYPE_NONE, 0, GlitchResearchLab_Scientist5, 0
    object_event 3, OBJ_EVENT_GFX_PROF_BIRCH, 0, 8, 7, 3, MOVEMENT_TYPE_FACE_DOWN, 0, 0, TRAINER_TYPE_NONE, 0, GlitchResearchLab_Professor, 0
    object_event 4, OBJ_EVENT_GFX_SCIENTIST_2, 0, 8, 2, 3, MOVEMENT_TYPE_FACE_UP, 0, 0, TRAINER_TYPE_NONE, 0, GlitchResearchLab_Scientist1, 0
    object_event 5, OBJ_EVENT_GFX_SCIENTIST_2, 0, 5, 7, 3, MOVEMENT_TYPE_FACE_RIGHT, 0, 0, TRAINER_TYPE_NONE, 0, GlitchResearchLab_Scientist2, 0
    object_event 6, OBJ_EVENT_GFX_SCIENTIST_1, 0, 2, 10, 3, MOVEMENT_TYPE_FACE_LEFT, 0, 0, TRAINER_TYPE_NONE, 0, GlitchResearchLab_Scientist4, 0

.align 4
GlitchResearchLab_MapCoordEvents:
GlitchResearchLab_WarpCoordEvents:
    coord_event 6, 12, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT
    coord_event 7, 12, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT

.align 4
GlitchResearchLab_MapBGEvents:
    bg_event 0, 4, 0, BG_EVENT_PLAYER_FACING_ANY, GlitchResearchLab_PC1
    bg_event 1, 4, 0, BG_EVENT_PLAYER_FACING_ANY, GlitchResearchLab_PC1
    bg_event 5, 1, 0, BG_EVENT_PLAYER_FACING_ANY, GlitchResearchLab_PC4
    bg_event 6, 1, 0, BG_EVENT_PLAYER_FACING_ANY, GlitchResearchLab_PC4
    bg_event 11, 6, 0, BG_EVENT_PLAYER_FACING_ANY, GlitchResearchLab_Machine
    bg_event 12, 6, 0, BG_EVENT_PLAYER_FACING_ANY, GlitchResearchLab_Machine
    bg_event 6, 6, 0, BG_EVENT_PLAYER_FACING_ANY, GlitchResearchLab_PC3
    bg_event 6, 5, 0, BG_EVENT_PLAYER_FACING_ANY, GlitchResearchLab_PC3
    bg_event 1, 9, 0, BG_EVENT_PLAYER_FACING_ANY, GlitchResearchLab_PC2
    bg_event 1, 10, 0, BG_EVENT_PLAYER_FACING_ANY, GlitchResearchLab_PC2

.align 4
GlitchResearchLab_MapEvts:
    map_events 6, GlitchResearchLab_MapObjectEvents, 0, 0, 2, GlitchResearchLab_MapCoordEvents, 10, GlitchResearchLab_MapBGEvents

.align 4
GlitchResearchLab_MapBorder:
    .byte 0x01, 0x02, 0x01, 0x02, 0x01, 0x02, 0x01, 0x02

.align 4
GlitchResearchLab_MapData:
    .hword 0xc601, 0xa601, 0xa601, 0xc601, 0xb608, 0xb612, 0xa613, 0xb608, 0xa608, 0xc609, 0xb609, 0xa608, 0xb608, 0xb608, 0xb608, 0xa601, 0xa601
    .hword 0xb601, 0xb601, 0xb601, 0xb601, 0xa63c, 0xa61a, 0xc61b, 0xc60a, 0xc60b, 0xb60c, 0xb60d, 0xa60e, 0xa60a, 0xc60a, 0xc60a, 0xa601, 0xc601
    .hword 0xc601, 0xc601, 0xa601, 0xa601, 0xb644, 0x3222, 0x3223, 0x323e, 0x3222, 0x3233, 0x3222, 0x3233, 0x323e, 0xa69a, 0xa69a, 0xb601, 0xa601
    .hword 0xa612, 0xc613, 0xc210, 0xc211, 0x322a, 0x322a, 0x3241, 0x3202, 0x3202, 0x3202, 0x3202, 0x3229, 0x323a, 0x3202, 0xc632, 0xa601, 0xa601
    .hword 0xc61a, 0xa61b, 0xc218, 0xc219, 0x3202, 0x3202, 0x3202, 0x3226, 0x3202, 0x3202, 0x3202, 0xa631, 0xb642, 0x3202, 0x3202, 0xa608, 0xc608
    .hword 0x3222, 0x3223, 0xc220, 0x3221, 0x3202, 0x3202, 0xb63b, 0xc62e, 0x3202, 0x3202, 0x3202, 0xc614, 0xc615, 0x3216, 0x3202, 0xa60a, 0xb60a
    .hword 0x3202, 0x3202, 0xc228, 0x3202, 0x3202, 0x3249, 0xa643, 0xc63a, 0x3202, 0x3202, 0x3202, 0xa61c, 0xb61d, 0xc61e, 0x3202, 0xb636, 0xc637
    .hword 0x3202, 0x3202, 0x323f, 0x3202, 0x3202, 0x3202, 0xa64b, 0xb642, 0x3202, 0x3202, 0x3202, 0x3202, 0x3202, 0x3202, 0x3202, 0xc62c, 0xa62d
    .hword 0x3202, 0x3202, 0x3202, 0x3202, 0x3202, 0x3202, 0x323f, 0x323f, 0x3202, 0x3202, 0x3202, 0x3202, 0x3202, 0x3202, 0x3202, 0xc634, 0xc635
    .hword 0x3202, 0xa630, 0x3202, 0x3202, 0x3202, 0x3202, 0x3202, 0x3202, 0x3202, 0x3202, 0x3202, 0x3202, 0x3202, 0x3202, 0x3202, 0x323f, 0x323f
    .hword 0xb648, 0xa638, 0x3239, 0x3202, 0x3202, 0x3202, 0x3202, 0x3202, 0x3202, 0x3202, 0x3202, 0x3202, 0x3202, 0x3202, 0x3202, 0x3202, 0x3202
    .hword 0xc648, 0xc640, 0x3202, 0x3226, 0x3202, 0x3202, 0x3202, 0x3202, 0x3202, 0x3202, 0xb601, 0xc601, 0xb601, 0xc601, 0xc601, 0xa601, 0xc601
    .hword 0x324f, 0x323f, 0x3202, 0xc62e, 0x3202, 0x3202, 0x0206, 0x0207, 0x3202, 0x3202, 0xb601, 0xc601, 0xc601, 0xa601, 0xb601, 0xa601, 0xb601

.align 4
GlitchResearchLab_MapConnections:
    .hword 1315
    .byte 11, 8
    .hword 1315
    .byte 11, 8

.align 4
GlitchResearchLab_MapName:
    .string "G.RESEARCH LAB$"

# scripts/0565_GlitchResearchLab.s

.align 4

GlitchResearchLab_MapInitCode:
    ldr r0, =zSkipMapExitMovement
    mov r1, #2
    strb r1, [r0]
    bx lr

.align 4
.ltorg

GlitchResearchLab_MapInitScript:
    end

GlitchResearchLab_Professor:
    lock
    faceplayer
    msgbox GlitchResearchLab_Professor_Text
    release
    end

GlitchResearchLab_Professor_Text:
    .string "Hello, and welcome to the Glitchland\n"
    .string "Glitch Research Laboratory!\l"
    .string "Please have a look around.$"

GlitchResearchLab_Scientist1:
    lock
    faceplayer
    msgbox GlitchResearchLab_Scientist1_Text
    release
    end

GlitchResearchLab_Scientist1_Text:
    .string "Through our combined efforts, we\n"
    .string "discovered a Gen III counterpart to\l"
    .string "OAM DMA hijacking.\p"
    .string "The name of the game is IRQ vectors!\n"
    .string "IRQ vector hijacking has potential to\l"
    .string "revolutionize Generation III ACE!$"

GlitchResearchLab_Scientist2:
    lock
    faceplayer
    msgbox GlitchResearchLab_Scientist2_Text
    release
    end

GlitchResearchLab_Scientist2_Text:
    .string "Interesting. The curtains in our\n"
    .string "windows keep changing shape based on\l"
    .string "the contents of my PC box.\p"
    .string "I'm hoping I can receive some grants\n"
    .string "for investigating this with proper\l"
    .string "glitch research methodologies.\p"
    .string "Empirical glitching just ain't gonna\n"
    .string "work here.$"

GlitchResearchLab_Scientist3:
    lock
    faceplayer
    msgbox GlitchResearchLab_Scientist3_Text
    release
    end

GlitchResearchLab_Scientist3_Text:
    .string "I'm currently developing a machine that\n"
    .string "accelerates growth of Pomeg Berries.\p"
    .string "Ever since we moved to Generation III,\n"
    .string "we need an awful lot of them.\p"
    .string "We've drained our entire supply of\n"
    .string "berries in just a few days.$"

GlitchResearchLab_Scientist4:
    lock
    faceplayer
    msgbox GlitchResearchLab_Scientist4_Text
    release
    end

GlitchResearchLab_Scientist4_Text:
    .string "Spank me as much as you want,\n"
    .string "I'm not moving away from my Ley Lines!\p"
    .string "Hey, I'm doing important research.\n"
    .string "Please go somewhere else.$"

GlitchResearchLab_Scientist5:
    lock
    faceplayer
    msgbox GlitchResearchLab_Scientist5_Text
    release
    end

GlitchResearchLab_Scientist5_Text:
    .string "Hmm... let's see...\n"
    .string "The Acro Bike instability glitches...\p"
    .string "Aha, here's the problem.\n"
    .string "Too many grass sprites!\p"
    .string "You know what they say.\n"
    .string "All sprites... sprite sprites.$"

GlitchResearchLab_Machine:
    lock
    faceplayer
    msgbox GlitchResearchLab_Machine_Text
    release
    end

GlitchResearchLab_Machine_Text:
    .string "Very complicated machinery.\n"
    .string "Pomeg Berries are tightly packed inside.$"

GlitchResearchLab_PC1:
    lock
    msgbox GlitchResearchLab_PC1_Text
    release
    end

GlitchResearchLab_PC1_Text:
    .string "Hmm, what's this?\n"
    .string "Fools Event 2023 - concept document?\p"
    .string "Better not read it.\n"
    .string "Spoilers aren't fun!$"

GlitchResearchLab_PC2:
    lock
    msgbox GlitchResearchLab_PC2_Text
    release
    end

GlitchResearchLab_PC2_Text:
    .string "You take a look at the screen.\p"
    .string "Hey, he's playing the critically\n"
    .string "acclaimed MMORPG, Final Fantasy XIV!\p"
    .string "He's using his free trial, which includes\n"
    .string "the entirety of A Realm Reborn and the\l"
    .string "award-winning Heavensward expansion\l"
    .string "up to level 60 with no restrictions\l"
    .string "on playtime!$"

GlitchResearchLab_PC3:
    lock
    msgbox GlitchResearchLab_PC3_Text
    release
    end

GlitchResearchLab_PC3_Text:
    .string "Some GameBoy Advance emulator is\n"
    .string "running with its debugger opened.\p"
    .string "Wait, what's it debugging? It's a game,\n"
    .string "but it looks exactly like this world!$"

GlitchResearchLab_PC4:
    lock
    msgbox GlitchResearchLab_PC4_Text
    release
    end

GlitchResearchLab_PC4_Text:
    .string "The pokeemerald disassembly files are\n"
    .string "neatly displayed on the screen.$"
