# fools2022 - autogenerated map file, please do not change!
# created from: pokeemerald/data/maps/x0669_NorthernRetreat/map.json

.thumb
.include "include/constants.inc"
.org MAP_LOAD_BASE

.include "include/macros.inc"
.include "include/symbols.inc"
.include "include/map.inc"
.include "include/event.inc"
.include "include/save.inc"

NorthernRetreat_MapHeader:
    .word NorthernRetreat_MapLayout
    .word NorthernRetreat_MapEvts
    .word NULL
    .word NULL
    .hword MUS_PETALBURG
    .hword 0
    .byte 0
    .byte 0
    .byte WEATHER_NONE
    .byte 0
    .hword 0
    map_header_flags allow_cycling=1, allow_escaping=1, allow_running=1, show_map_name=1
    .byte 0
    # additional data specific to fools2022 maps
    .word NorthernRetreat_MapInitCode+1
    .word NorthernRetreat_MapConnections
    .word NorthernRetreat_MapInitScript
    .word NorthernRetreat_MapName
    .word 0x0000

NorthernRetreat_MapLayout:
    .word 10
    .word 9
    .word NorthernRetreat_MapBorder
    .word NorthernRetreat_MapData
    .word gTileset_Building
    .word gTileset_GenericBuilding

.align 4
NorthernRetreat_MapObjectEvents:
    object_event 1, OBJ_EVENT_GFX_MAN_3, 0, 5, 4, 3, MOVEMENT_TYPE_FACE_LEFT, 0, 0, TRAINER_TYPE_NONE, 0, NorthernRetreat_House3_Script1, 0
    object_event 2, OBJ_EVENT_GFX_GIRL_3, 0, 5, 2, 3, MOVEMENT_TYPE_FACE_UP, 0, 0, TRAINER_TYPE_NONE, 0, NorthernRetreat_House3_Script2, 0

.align 4
NorthernRetreat_MapCoordEvents:
NorthernRetreat_WarpCoordEvents:
    coord_event 3, 8, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT
    coord_event 4, 8, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT

.align 4
NorthernRetreat_MapBGEvents:

.align 4
NorthernRetreat_MapEvts:
    map_events 2, NorthernRetreat_MapObjectEvents, 0, 0, 2, NorthernRetreat_MapCoordEvents, 0, NorthernRetreat_MapBGEvents

.align 4
NorthernRetreat_MapBorder:
    .byte 0x01, 0x02, 0x01, 0x02, 0x01, 0x02, 0x01, 0x02

.align 4
NorthernRetreat_MapData:
    .hword 0xa686, 0xc687, 0xa679, 0xc67a, 0xb605, 0xc607, 0xa605, 0xc605, 0xc605, 0xb605
    .hword 0xa68e, 0xb68f, 0xc681, 0xc682, 0xc60d, 0xb60f, 0xa60d, 0xb60d, 0xc690, 0xa690
    .hword 0x3296, 0x3297, 0x3289, 0x328a, 0x3224, 0x3224, 0x3224, 0x3224, 0xc698, 0xc698
    .hword 0x3239, 0x3235, 0x3236, 0x3236, 0x3236, 0x3236, 0x3236, 0x3237, 0x3223, 0x3223
    .hword 0x3239, 0x323d, 0x32e1, 0xc648, 0xa649, 0x32e2, 0x323e, 0x323f, 0x3223, 0x3223
    .hword 0x3239, 0x323d, 0x32e1, 0xa650, 0xc651, 0x32e2, 0x323e, 0x323f, 0x3223, 0x3223
    .hword 0x3239, 0x3245, 0x3246, 0x3246, 0x3246, 0x3246, 0x3246, 0x3247, 0x3223, 0x3223
    .hword 0x3239, 0x3223, 0x3223, 0x3223, 0x3223, 0x3223, 0x3223, 0x3223, 0x3223, 0x3222
    .hword 0x3239, 0x3223, 0x3223, 0x0208, 0x0209, 0x3223, 0x3223, 0x3223, 0x3223, 0xa62a

.align 4
NorthernRetreat_MapConnections:
    .hword 1583
    .byte 3, 8
    .hword 1583
    .byte 3, 8

.align 4
NorthernRetreat_MapName:
    .string "NORTHERN RETREAT$"

# scripts/0669_NorthernRetreat.s

.align 4

NorthernRetreat_MapInitCode:
    ldr r0, =zSkipMapExitMovement
    mov r1, #2
    strb r1, [r0]
    bx lr

.align 4
.ltorg

NorthernRetreat_MapInitScript:
    end

NorthernRetreat_House3_Script1:
    lock
    faceplayer
    msgbox NorthernRetreat_House3_Script1_Text
    release
    end

NorthernRetreat_House3_Script1_Text:
    .string "Northern Glitchland is one of the most\n"
    .string "developed districts in our region.\p"
    .string "We've got two towns, while all other\n"
    .string "districts have just one.\p"
    .string "Now, I know what you're thinking!\n"
    .string "What about Deliria?\p"
    .string "Well, that does not qualify as a town\n"
    .string "for me, so I guess we're settled.$"

NorthernRetreat_House3_Script2:
    lock
    faceplayer
    msgbox NorthernRetreat_House3_Script2_Text
    release
    end

NorthernRetreat_House3_Script2_Text:
    .string "Many Delirians started to leave\n"
    .string "Glitchland, rightfully accusing the\l"
    .string "local authorities of discrimination.\p"
    .string "No one is really sure how they're\n"
    .string "escaping, considering their town is\l"
    .string "strictly guarded.$"

