# fools2022 - autogenerated map file, please do not change!
# created from: pokeemerald/data/maps/x0824_ShiftingGrove/map.json

.thumb
.include "include/constants.inc"
.org MAP_LOAD_BASE

.include "include/macros.inc"
.include "include/symbols.inc"
.include "include/map.inc"
.include "include/event.inc"
.include "include/save.inc"

ShiftingGrove_MapHeader:
    .word ShiftingGrove_MapLayout
    .word ShiftingGrove_MapEvts
    .word NULL
    .word NULL
    .hword MUS_RG_ROUTE24
    .hword 0
    .byte 0
    .byte 0
    .byte WEATHER_NONE
    .byte 0
    .hword 0
    map_header_flags allow_cycling=1, allow_escaping=1, allow_running=1, show_map_name=1
    .byte 0
    # additional data specific to fools2022 maps
    .word ShiftingGrove_MapInitCode+1
    .word ShiftingGrove_MapConnections
    .word ShiftingGrove_MapInitScript
    .word ShiftingGrove_MapName
    .word 0x2819

ShiftingGrove_MapLayout:
    .word 38
    .word 14
    .word ShiftingGrove_MapBorder
    .word ShiftingGrove_MapData
    .word gTileset_General
    .word gTileset_Petalburg

.align 4
ShiftingGrove_MapObjectEvents:
    object_event 1, OBJ_EVENT_GFX_MAN_4, 0, 27, 10, 3, MOVEMENT_TYPE_LOOK_AROUND, 0, 0, TRAINER_TYPE_NONE, 0, ShiftingGrove_Script1, 0
    object_event 2, OBJ_EVENT_GFX_LASS, 0, 11, 9, 3, MOVEMENT_TYPE_WANDER_AROUND, 1, 1, TRAINER_TYPE_NONE, 0, ShiftingGrove_Script2, 0
    object_event 3, OBJ_EVENT_GFX_ROXANNE, 0, 15, 2, 3, MOVEMENT_TYPE_WANDER_LEFT_AND_RIGHT, 2, 0, TRAINER_TYPE_NONE, 0, ShiftingGrove_Script3, 0

.align 4
ShiftingGrove_MapCoordEvents:
ShiftingGrove_WarpCoordEvents:
    coord_event 8, 2, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT
    coord_event 8, 3, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT
    coord_event 8, 4, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT
    coord_event 30, 6, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT
    coord_event 30, 7, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT
    coord_event 30, 8, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT
    coord_event 30, 9, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT

.align 4
ShiftingGrove_MapBGEvents:
    bg_event 28, 3, 0, BG_EVENT_PLAYER_FACING_ANY, ShiftingGrove_Switch1
    bg_event 27, 5, 0, BG_EVENT_PLAYER_FACING_ANY, ShiftingGrove_Switch2
    bg_event 26, 3, 0, BG_EVENT_PLAYER_FACING_ANY, ShiftingGrove_Switch3

.align 4
ShiftingGrove_MapEvts:
    map_events 3, ShiftingGrove_MapObjectEvents, 0, 0, 7, ShiftingGrove_MapCoordEvents, 3, ShiftingGrove_MapBGEvents

.align 4
ShiftingGrove_MapBorder:
    .byte 0xd4, 0x01, 0xd5, 0x01, 0xdc, 0x01, 0xdd, 0x01

.align 4
ShiftingGrove_MapData:
    .hword 0xc5d4, 0xa5d5, 0xa5d4, 0xc5d5, 0xc5d4, 0xb5d5, 0xa5d4, 0xc5d5, 0xa5d4, 0xa5d5, 0xb5d4, 0xc5d5, 0xc5d4, 0xc5d5, 0xc5d4, 0xa5d5, 0xb5d4, 0xa5d5, 0xa5d4, 0xc5d5, 0xb5d4, 0xc5d5, 0xc5d4, 0xc5d5, 0xa5d4, 0xa5d5, 0xc5d4, 0xb5d5, 0xc5d4, 0xa5d5, 0xa5d4, 0xb5d5, 0xc5d4, 0xb5d5, 0xc5d4, 0xa5d5, 0xa5d4, 0xc5d5
    .hword 0xc5e6, 0xb5e7, 0xa5e6, 0xb5e7, 0xb5e6, 0xa5e7, 0xc5e6, 0xa5e7, 0xa5e6, 0xc5e7, 0xb5e6, 0xb5e7, 0xc5e6, 0xc5e7, 0xb5e6, 0xc5e7, 0xc5e6, 0xb5e7, 0xb5e6, 0xc5e7, 0xc5e6, 0xa5e7, 0xc5e6, 0xa5e7, 0xc5e6, 0xb5e7, 0xa5e6, 0xa5e7, 0xb5e6, 0xa5e7, 0xa5dc, 0xa5dd, 0xb5dc, 0xc5dd, 0xb5dc, 0xc5dd, 0xc5dc, 0xb5dd
    .hword 0x3001, 0x3001, 0x3001, 0x3001, 0x3001, 0x3001, 0x31d0, 0x31d1, 0x31d1, 0x31d1, 0x31d1, 0x31d1, 0x31d1, 0x31d1, 0x31d1, 0x31d1, 0x31d1, 0x31d1, 0x31d1, 0x31d1, 0x31d1, 0x31d1, 0x31d2, 0x3001, 0xa4ff, 0x3001, 0x3001, 0x3001, 0x3001, 0x3001, 0xc5d4, 0xb5d5, 0xb5d4, 0xa5d5, 0xc5d4, 0xc5d5, 0xa5d4, 0xa5d5
    .hword 0x31d1, 0x31d1, 0x31d1, 0x31d1, 0x31d1, 0x31d1, 0x31d9, 0x31d9, 0x31e1, 0x31e1, 0x31e1, 0x31e1, 0x31e1, 0x31e1, 0x31e1, 0x31e1, 0x31e1, 0x31e1, 0x31e1, 0x31e1, 0x31e1, 0x31e1, 0x31e2, 0x3001, 0xc486, 0x3001, 0xc602, 0x3001, 0xb602, 0x3001, 0xa5dc, 0xc5dd, 0xc5dc, 0xb5dd, 0xa5dc, 0xa5dd, 0xc5dc, 0xc5dd
    .hword 0x31e1, 0x31e1, 0x31e1, 0x31e1, 0x31e1, 0x31e1, 0x31e1, 0x31e2, 0x3001, 0x3001, 0x3001, 0x3001, 0x3001, 0x3001, 0x3001, 0x3001, 0x3001, 0x3001, 0x3001, 0x3001, 0x3001, 0x3001, 0x3001, 0x3001, 0xa486, 0x3001, 0x3001, 0x3001, 0x3001, 0x3001, 0xb5d4, 0xb5d5, 0xb5d4, 0xb5d5, 0xb5d4, 0xc5d5, 0xa5d4, 0xc5d5
    .hword 0x31ce, 0x31cf, 0x31ce, 0x31cf, 0x31ce, 0x31cf, 0x31ce, 0x31cf, 0xc4d5, 0xa487, 0xc4d6, 0x3001, 0xc4d5, 0xa487, 0xc4d6, 0xa549, 0xc549, 0xb549, 0xa549, 0xb549, 0xb549, 0xb4d5, 0xa487, 0xb487, 0xc48e, 0x3001, 0x3001, 0xa602, 0x3001, 0x3001, 0xc5e6, 0xb5e7, 0xb5e6, 0xc5e7, 0xc5e6, 0xa5e7, 0xc5e6, 0xa5e7
    .hword 0xa5d4, 0xb5d5, 0xa5d4, 0xa5d5, 0xa5d4, 0xa5d5, 0xc5d4, 0xc5d5, 0xc540, 0x3001, 0x31d0, 0x31d2, 0x3001, 0x3001, 0x3001, 0x0468, 0x046a, 0x04e0, 0x3001, 0x0468, 0x046a, 0x3001, 0x3001, 0x3001, 0x3001, 0x3001, 0x3001, 0x3001, 0x3001, 0x3001, 0x3001, 0x3001, 0x3001, 0x3001, 0x3001, 0x3001, 0x3001, 0x3001
    .hword 0xa5dc, 0xa5dd, 0xa5dc, 0xc5dd, 0xb5dc, 0xc5dd, 0xa5dc, 0xb5dd, 0xb540, 0x3001, 0x31d8, 0x31d9, 0x31d2, 0x3001, 0x3001, 0x0478, 0x047a, 0x3001, 0x3001, 0x0478, 0x047a, 0x3001, 0x3001, 0x3001, 0x3001, 0x3001, 0x3001, 0x3118, 0x3119, 0x3119, 0x3119, 0x3119, 0x3119, 0x3119, 0x3119, 0x3119, 0x3119, 0x3119
    .hword 0xb5d4, 0xc5d5, 0xb5d4, 0xa5d5, 0xa5d4, 0xa5d5, 0xb5d4, 0xb5d5, 0xc540, 0x31d0, 0x31d9, 0x31d9, 0x31d9, 0x31d2, 0x3001, 0x0468, 0x046a, 0x0468, 0x046a, 0x04e0, 0x3001, 0x3001, 0x3001, 0x3001, 0x3001, 0x3001, 0x3001, 0x3120, 0x3121, 0x3129, 0x3129, 0x3129, 0x3129, 0x3129, 0x3129, 0x3129, 0x3129, 0x3129
    .hword 0xb5dc, 0xc5dd, 0xc5dc, 0xb5dd, 0xb5dc, 0xc5dd, 0xc5dc, 0xb5dd, 0xc540, 0x31e0, 0x31d9, 0x31d9, 0x31d9, 0x31e2, 0x3001, 0x0478, 0x047a, 0x0478, 0x047a, 0x3001, 0x3001, 0x3001, 0x3001, 0x3001, 0x3118, 0x3119, 0x3119, 0x3121, 0x3122, 0x3001, 0x31ce, 0x31cf, 0x31ce, 0x31cf, 0x31ce, 0x31cf, 0x31ce, 0x31cf
    .hword 0xa5d4, 0xc5d5, 0xc5d4, 0xc5d5, 0xa5d4, 0xc5d5, 0xa5d4, 0xa5d5, 0xc532, 0x3001, 0x31e0, 0x31e1, 0x31e2, 0x3001, 0x3001, 0x04e0, 0x3001, 0x0468, 0x046a, 0x0468, 0x046a, 0x3001, 0x3001, 0x3001, 0x3128, 0x3129, 0x3129, 0x3129, 0x312a, 0x3001, 0xa5d4, 0xb5d5, 0xb5d4, 0xa5d5, 0xa5d4, 0xa5d5, 0xb5d4, 0xa5d5
    .hword 0xc5dc, 0xc5dd, 0xc5dc, 0xa5dd, 0xc5dc, 0xa5dd, 0xb5dc, 0xb5dd, 0x31ce, 0x31cf, 0x31ce, 0x31cf, 0x31ce, 0x31cf, 0x3001, 0x3001, 0x3001, 0x0478, 0x047a, 0x0478, 0x047a, 0x3001, 0x31ce, 0x31cf, 0x31ce, 0x31cf, 0x31ce, 0x31cf, 0x31ce, 0x31cf, 0xc5dc, 0xc5dd, 0xb5dc, 0xb5dd, 0xc5dc, 0xc5dd, 0xa5dc, 0xc5dd
    .hword 0xc5d4, 0xa5d5, 0xa5d4, 0xc5d5, 0xb5d4, 0xa5d5, 0xb5d4, 0xb5d5, 0xb5d4, 0xc5d5, 0xb5d4, 0xb5d5, 0xc5d4, 0xc5d5, 0xc549, 0xa549, 0xb549, 0xb549, 0xa549, 0xa549, 0xc549, 0xb549, 0xc5d4, 0xb5d5, 0xb5d4, 0xc5d5, 0xb5d4, 0xa5d5, 0xc5d4, 0xb5d5, 0xa5d4, 0xc5d5, 0xb5d4, 0xb5d5, 0xa5d4, 0xa5d5, 0xa5d4, 0xb5d5
    .hword 0xc5dc, 0xc5dd, 0xc5dc, 0xc5dd, 0xa5dc, 0xa5dd, 0xa5dc, 0xc5dd, 0xa5dc, 0xb5dd, 0xa5dc, 0xc5dd, 0xa5dc, 0xa5dd, 0xa40d, 0xa40d, 0xa40d, 0xb40d, 0xb40d, 0xa40d, 0xa40d, 0xa40d, 0xa5dc, 0xa5dd, 0xa5dc, 0xa5dd, 0xb5dc, 0xb5dd, 0xb5dc, 0xb5dd, 0xb5dc, 0xc5dd, 0xb5dc, 0xc5dd, 0xc5dc, 0xa5dd, 0xb5dc, 0xa5dd

.align 4
ShiftingGrove_MapConnections:
    .hword 0x0932
    .byte 148, 16
    .hword 0x0932
    .byte 148, 16
    .hword 0x0932
    .byte 148, 16
    .hword 0x0734
    .byte 135, 134
    .hword 0x0734
    .byte 135, 134
    .hword 0x0734
    .byte 135, 134
    .hword 0x0734
    .byte 135, 134

.align 4
ShiftingGrove_MapName:
    .string "SHIFTING GROVE$"

# scripts/0824_ShiftingGrove.s

.align 4

ShiftingGrove_MapInitCode:
    bx lr

ShiftingGrove_MapInitScript:
    setvar VAR_TEMP_1, 0
    setvar VAR_TEMP_2, 0
    setvar VAR_TEMP_3, 0
    end

ShiftingGrove_Script1:
    lock
    faceplayer
    msgbox ShiftingGrove_Script1_Text
    release
    end

ShiftingGrove_Script1_Text:
    .string "You know what grinds my gears?\n"
    .string "Useless puzzles!\p"
    .string "Why is all of this even necessary?\n"
    .string "Come on, game designers! Get with it!\p"
    .string "Geez. What were they thinking?\n"
    .string "This game's a bunch of poopy ass-dicks!$"

ShiftingGrove_Script2:
    lock
    faceplayer
    msgbox ShiftingGrove_Script2_Text
    release
    end

ShiftingGrove_Script2_Text:
    .string "With ledges, you have to jump. Once\n"
    .string "you jump, there's no way back.\p"
    .string "How in life, time only flows forward.\n"
    .string "You can't go back to fix your mistakes.\p"
    .string "It's all a symbol of evanescence.\n"
    .string "Panta rhei. Everything flows...\l"
    .string "Or am I just overthinking things?$"

ShiftingGrove_Script3:
    lock
    faceplayer
    msgbox ShiftingGrove_Script3_Text
    release
    end

ShiftingGrove_Script3_Text:
    .string "You know any... {LQUOT}weird{RQUOT} people, by\n"
    .string "chance? Someone who's just... not like\l"
    .string "everyone else.\p"
    .string "Authorities in Glitchland are treating\n"
    .string "any deviations from social norm\l"
    .string "extremely harshly.\p"
    .string "All people who don't comply are forced\n"
    .string "to live in a special Glitchland region\l"
    .string "named Deliria.$"

ShiftingGrove_Switch1:
    lock
    msgbox ShiftingGrove_Switch_Text, MSGBOX_YESNO
    compare_var_to_value VAR_RESULT, NO
    goto_if_eq ShiftingGrove_SwitchCancel
	playse SE_ICE_STAIRS
    call ShiftingGrove_Rotate_1
    call ShiftingGrove_UpdateTiles
    callnative DrawWholeMapView
    delay 30
    release
    end

ShiftingGrove_Switch2:
    lock
    msgbox ShiftingGrove_Switch_Text, MSGBOX_YESNO
    compare_var_to_value VAR_RESULT, NO
    goto_if_eq ShiftingGrove_SwitchCancel
	playse SE_ICE_STAIRS
    call ShiftingGrove_Rotate_2
    call ShiftingGrove_UpdateTiles
    callnative DrawWholeMapView
    delay 30
    release
    end

ShiftingGrove_Switch3:
    lock
    msgbox ShiftingGrove_Switch_Text, MSGBOX_YESNO
    compare_var_to_value VAR_RESULT, NO
    goto_if_eq ShiftingGrove_SwitchCancel
	playse SE_ICE_STAIRS
    call ShiftingGrove_Rotate_3
    call ShiftingGrove_UpdateTiles
    callnative DrawWholeMapView
    delay 30
    release
    end

ShiftingGrove_SwitchCancel:
    msgbox ShiftingGrove_SwitchCancel_Text
    release
    end

ShiftingGrove_SwitchCancel_Text:
    .string "Understandable.\n"
    .string "Have a great day.$"

ShiftingGrove_Rotate_1:
    addvar VAR_TEMP_1, 1
    compare_var_to_value VAR_TEMP_1, 3
    goto_if_eq ShiftingGrove_Rotate_1_Reset
    return
ShiftingGrove_Rotate_1_Reset:
    setvar VAR_TEMP_1, 0
    return

ShiftingGrove_Rotate_2:
    addvar VAR_TEMP_2, 1
    compare_var_to_value VAR_TEMP_2, 3
    goto_if_eq ShiftingGrove_Rotate_2_Reset
    return
ShiftingGrove_Rotate_2_Reset:
    setvar VAR_TEMP_2, 0
    return

ShiftingGrove_Rotate_3:
    addvar VAR_TEMP_3, 1
    compare_var_to_value VAR_TEMP_3, 3
    goto_if_eq ShiftingGrove_Rotate_3_Reset
    return
ShiftingGrove_Rotate_3_Reset:
    setvar VAR_TEMP_3, 0
    return

ShiftingGrove_UpdateTiles:
    compare_var_to_value VAR_TEMP_1, 0
    call_if_eq ShiftingGrove_Set_1_1
    call_if_eq ShiftingGrove_Set_1_2
    call_if_eq ShiftingGrove_Clear_1_3
    compare_var_to_value VAR_TEMP_1, 1
    call_if_eq ShiftingGrove_Clear_1_1
    call_if_eq ShiftingGrove_Set_1_2
    call_if_eq ShiftingGrove_Set_1_3
    compare_var_to_value VAR_TEMP_1, 2
    call_if_eq ShiftingGrove_Set_1_1
    call_if_eq ShiftingGrove_Clear_1_2
    call_if_eq ShiftingGrove_Set_1_3
    compare_var_to_value VAR_TEMP_2, 0
    call_if_eq ShiftingGrove_Clear_2_1
    call_if_eq ShiftingGrove_Set_2_2
    call_if_eq ShiftingGrove_Set_2_3
    compare_var_to_value VAR_TEMP_2, 1
    call_if_eq ShiftingGrove_Set_2_1
    call_if_eq ShiftingGrove_Clear_2_2
    call_if_eq ShiftingGrove_Set_2_3
    compare_var_to_value VAR_TEMP_2, 2
    call_if_eq ShiftingGrove_Set_2_1
    call_if_eq ShiftingGrove_Set_2_2
    call_if_eq ShiftingGrove_Clear_2_3
    compare_var_to_value VAR_TEMP_3, 0
    call_if_eq ShiftingGrove_Set_3_1
    call_if_eq ShiftingGrove_Clear_3_2
    call_if_eq ShiftingGrove_Set_3_3
    compare_var_to_value VAR_TEMP_3, 1
    call_if_eq ShiftingGrove_Set_3_1
    call_if_eq ShiftingGrove_Set_3_2
    call_if_eq ShiftingGrove_Clear_3_3
    compare_var_to_value VAR_TEMP_3, 2
    call_if_eq ShiftingGrove_Clear_3_1
    call_if_eq ShiftingGrove_Set_3_2
    call_if_eq ShiftingGrove_Set_3_3
    return

ShiftingGrove_Set_1_1:
    setmetatile 15, 6, 0x068, TRUE
    setmetatile 16, 6, 0x06A, TRUE
    setmetatile 15, 7, 0x078, TRUE
    setmetatile 16, 7, 0x07A, TRUE
    return

ShiftingGrove_Clear_1_1:
    setmetatile 15, 6, 0x0E0, TRUE
    setmetatile 16, 6, 0x001, FALSE
    setmetatile 15, 7, 0x001, FALSE
    setmetatile 16, 7, 0x001, FALSE
    return

ShiftingGrove_Set_2_1:
    setmetatile 17, 6, 0x068, TRUE
    setmetatile 18, 6, 0x06A, TRUE
    setmetatile 17, 7, 0x078, TRUE
    setmetatile 18, 7, 0x07A, TRUE
    return

ShiftingGrove_Clear_2_1:
    setmetatile 17, 6, 0x0E0, TRUE
    setmetatile 18, 6, 0x001, FALSE
    setmetatile 17, 7, 0x001, FALSE
    setmetatile 18, 7, 0x001, FALSE
    return

ShiftingGrove_Set_3_1:
    setmetatile 19, 6, 0x068, TRUE
    setmetatile 20, 6, 0x06A, TRUE
    setmetatile 19, 7, 0x078, TRUE
    setmetatile 20, 7, 0x07A, TRUE
    return

ShiftingGrove_Clear_3_1:
    setmetatile 19, 6, 0x0E0, TRUE
    setmetatile 20, 6, 0x001, FALSE
    setmetatile 19, 7, 0x001, FALSE
    setmetatile 20, 7, 0x001, FALSE
    return

ShiftingGrove_Set_1_2:
    setmetatile 15, 8, 0x068, TRUE
    setmetatile 16, 8, 0x06A, TRUE
    setmetatile 15, 9, 0x078, TRUE
    setmetatile 16, 9, 0x07A, TRUE
    return

ShiftingGrove_Clear_1_2:
    setmetatile 15, 8, 0x0E0, TRUE
    setmetatile 16, 8, 0x001, FALSE
    setmetatile 15, 9, 0x001, FALSE
    setmetatile 16, 9, 0x001, FALSE
    return

ShiftingGrove_Set_2_2:
    setmetatile 17, 8, 0x068, TRUE
    setmetatile 18, 8, 0x06A, TRUE
    setmetatile 17, 9, 0x078, TRUE
    setmetatile 18, 9, 0x07A, TRUE
    return

ShiftingGrove_Clear_2_2:
    setmetatile 17, 8, 0x0E0, TRUE
    setmetatile 18, 8, 0x001, FALSE
    setmetatile 17, 9, 0x001, FALSE
    setmetatile 18, 9, 0x001, FALSE
    return

ShiftingGrove_Set_3_2:
    setmetatile 19, 8, 0x068, TRUE
    setmetatile 20, 8, 0x06A, TRUE
    setmetatile 19, 9, 0x078, TRUE
    setmetatile 20, 9, 0x07A, TRUE
    return

ShiftingGrove_Clear_3_2:
    setmetatile 19, 8, 0x0E0, TRUE
    setmetatile 20, 8, 0x001, FALSE
    setmetatile 19, 9, 0x001, FALSE
    setmetatile 20, 9, 0x001, FALSE
    return

ShiftingGrove_Set_1_3:
    setmetatile 15, 10, 0x068, TRUE
    setmetatile 16, 10, 0x06A, TRUE
    setmetatile 15, 11, 0x078, TRUE
    setmetatile 16, 11, 0x07A, TRUE
    return

ShiftingGrove_Clear_1_3:
    setmetatile 15, 10, 0x0E0, TRUE
    setmetatile 16, 10, 0x001, FALSE
    setmetatile 15, 11, 0x001, FALSE
    setmetatile 16, 11, 0x001, FALSE
    return

ShiftingGrove_Set_2_3:
    setmetatile 17, 10, 0x068, TRUE
    setmetatile 18, 10, 0x06A, TRUE
    setmetatile 17, 11, 0x078, TRUE
    setmetatile 18, 11, 0x07A, TRUE
    return

ShiftingGrove_Clear_2_3:
    setmetatile 17, 10, 0x0E0, TRUE
    setmetatile 18, 10, 0x001, FALSE
    setmetatile 17, 11, 0x001, FALSE
    setmetatile 18, 11, 0x001, FALSE
    return

ShiftingGrove_Set_3_3:
    setmetatile 19, 10, 0x068, TRUE
    setmetatile 20, 10, 0x06A, TRUE
    setmetatile 19, 11, 0x078, TRUE
    setmetatile 20, 11, 0x07A, TRUE
    return

ShiftingGrove_Clear_3_3:
    setmetatile 19, 10, 0x0E0, TRUE
    setmetatile 20, 10, 0x001, FALSE
    setmetatile 19, 11, 0x001, FALSE
    setmetatile 20, 11, 0x001, FALSE
    return

ShiftingGrove_Switch_Text:
    .string "Aha! A rather suspicious object!\n"
    .string "Try to push it?$"
