# fools2022 - autogenerated map file, please do not change!
# created from: pokeemerald/data/maps/x096B_WorriedExplorer/map.json

.thumb
.include "include/constants.inc"
.org MAP_LOAD_BASE

.include "include/macros.inc"
.include "include/symbols.inc"
.include "include/map.inc"
.include "include/event.inc"
.include "include/save.inc"

WorriedExplorer_MapHeader:
    .word WorriedExplorer_MapLayout
    .word WorriedExplorer_MapEvts
    .word NULL
    .word NULL
    .hword MUS_RG_FUCHSIA
    .hword 0
    .byte 0
    .byte 0
    .byte WEATHER_NONE
    .byte 0
    .hword 0
    map_header_flags allow_cycling=1, allow_escaping=1, allow_running=1, show_map_name=1
    .byte 0
    # additional data specific to fools2022 maps
    .word WorriedExplorer_MapInitCode+1
    .word WorriedExplorer_MapConnections
    .word WorriedExplorer_MapInitScript
    .word WorriedExplorer_MapName
    .word 0x2819

WorriedExplorer_MapLayout:
    .word 10
    .word 9
    .word WorriedExplorer_MapBorder
    .word WorriedExplorer_MapData
    .word gTileset_Building
    .word gTileset_GenericBuilding

.align 4
WorriedExplorer_MapObjectEvents:
    object_event 1, OBJ_EVENT_GFX_MAN_1, 0, 5, 4, 3, MOVEMENT_TYPE_FACE_LEFT, 0, 0, TRAINER_TYPE_NONE, 0, WorriedExplorer_Interior_Script1, 0

.align 4
WorriedExplorer_MapCoordEvents:
WorriedExplorer_WarpCoordEvents:
    coord_event 3, 8, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT
    coord_event 4, 8, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT

.align 4
WorriedExplorer_MapBGEvents:

.align 4
WorriedExplorer_MapEvts:
    map_events 1, WorriedExplorer_MapObjectEvents, 0, 0, 2, WorriedExplorer_MapCoordEvents, 0, WorriedExplorer_MapBGEvents

.align 4
WorriedExplorer_MapBorder:
    .byte 0x01, 0x02, 0x01, 0x02, 0x01, 0x02, 0x01, 0x02

.align 4
WorriedExplorer_MapData:
    .hword 0xa686, 0xb687, 0xc679, 0xb67a, 0xb605, 0xb607, 0xc605, 0xb605, 0xb605, 0xc605
    .hword 0xc68e, 0xa68f, 0xb681, 0xa682, 0xc60d, 0xa60f, 0xb60d, 0xa60d, 0xb690, 0xb690
    .hword 0x3296, 0x3297, 0x3289, 0x328a, 0x3224, 0x3224, 0x3224, 0x3224, 0xc698, 0xc698
    .hword 0x3239, 0x3235, 0x3236, 0x3236, 0x3236, 0x3236, 0x3236, 0x3237, 0x3223, 0x3223
    .hword 0x3239, 0x323d, 0x32e1, 0xc648, 0xb649, 0x32e2, 0x323e, 0x323f, 0x3223, 0x3223
    .hword 0x3239, 0x323d, 0x32e1, 0xa650, 0xa651, 0x32e2, 0x323e, 0x323f, 0x3223, 0x3223
    .hword 0x3239, 0x3245, 0x3246, 0x3246, 0x3246, 0x3246, 0x3246, 0x3247, 0x3223, 0x3223
    .hword 0x3239, 0x3223, 0x3223, 0x3223, 0x3223, 0x3223, 0x3223, 0x3223, 0x3223, 0x3222
    .hword 0x3239, 0x3223, 0x3223, 0x0208, 0x0209, 0x3223, 0x3223, 0x3223, 0x3223, 0xb62a

.align 4
WorriedExplorer_MapConnections:
    .hword 2354
    .byte 11, 18
    .hword 2354
    .byte 11, 18

.align 4
WorriedExplorer_MapName:
    .string "WORRIED EXPLORER$"

# scripts/096B_WorriedExplorer.s

.align 4

WorriedExplorer_MapInitCode:
    bx lr

WorriedExplorer_MapInitScript:
    end

WorriedExplorer_Interior_Script1:
    lock
    faceplayer
    msgbox WorriedExplorer_Interior_Script1_Text
    release
    end

WorriedExplorer_Interior_Script1_Text:
    .string "Hello! I'm Matt, but everyone\n"
    .string "just calls me the {LQUOT}Worried Explorer{RQUOT}.\p"
    .string "I thought this place looked very\n"
    .string "suspicious, so I made the decision to\l"
    .string "live here and dedicate my life to\l"
    .string "solving the mysteries of this place.\p"
    .string "I think there's a underground cave\n"
    .string "system around here, but I have no idea\l"
    .string "how to reach it.\p"
    .string "Maybe you can solve the mystery of\n"
    .string "this place?$"

