# fools2022 - autogenerated map file, please do not change!
# created from: pokeemerald/data/maps/x0A32_StrangeBush/map.json

.thumb
.include "include/constants.inc"
.org MAP_LOAD_BASE

.include "include/macros.inc"
.include "include/symbols.inc"
.include "include/map.inc"
.include "include/event.inc"
.include "include/save.inc"

StrangeBush_MapHeader:
    .word StrangeBush_MapLayout
    .word StrangeBush_MapEvts
    .word NULL
    .word NULL
    .hword MUS_MT_PYRE_EXTERIOR
    .hword 0
    .byte 0
    .byte 0
    .byte WEATHER_NONE
    .byte 0
    .hword 0
    map_header_flags allow_cycling=1, allow_escaping=1, allow_running=1, show_map_name=1
    .byte 0
    # additional data specific to fools2022 maps
    .word StrangeBush_MapInitCode+1
    .word StrangeBush_MapConnections
    .word StrangeBush_MapInitScript
    .word StrangeBush_MapName
    .word 0x2819

StrangeBush_MapLayout:
    .word 10
    .word 18
    .word StrangeBush_MapBorder
    .word StrangeBush_MapData
    .word gTileset_General
    .word gTileset_Petalburg

.align 4
StrangeBush_MapObjectEvents:

.align 4
StrangeBush_MapCoordEvents:
StrangeBush_WarpCoordEvents:
    coord_event 6, 7, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT
    coord_event 7, 7, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT
    coord_event 8, 7, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT
    coord_event 9, 7, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT

.align 4
StrangeBush_MapBGEvents:
    bg_event 2, 12, 0, BG_EVENT_PLAYER_FACING_ANY, StrangeBush_Script
    bg_event 3, 12, 0, BG_EVENT_PLAYER_FACING_ANY, StrangeBush_Script

.align 4
StrangeBush_MapEvts:
    map_events 0, StrangeBush_MapObjectEvents, 0, 0, 4, StrangeBush_MapCoordEvents, 2, StrangeBush_MapBGEvents

.align 4
StrangeBush_MapBorder:
    .byte 0xd4, 0x01, 0xd5, 0x01, 0xdc, 0x01, 0xdd, 0x01

.align 4
StrangeBush_MapData:
    .hword 0xa5d4, 0xb5d5, 0xc5d4, 0xa5d5, 0xb5d4, 0xb5d5, 0x3001, 0x31d8, 0x31da, 0x3001
    .hword 0xb5dc, 0xc5dd, 0xb5dc, 0xa5dd, 0xc5dc, 0xa5dd, 0x3001, 0x31d8, 0x31da, 0x3001
    .hword 0xc5d4, 0xb5d5, 0xa5d4, 0xa5d5, 0xc5d4, 0xb5d5, 0x3001, 0x31d8, 0x31da, 0x3001
    .hword 0xa5dc, 0xb5dd, 0xa5dc, 0xa5dd, 0xc5dc, 0xa5dd, 0x3001, 0x31d8, 0x31da, 0x3001
    .hword 0xa5d4, 0xa5d5, 0xb5d4, 0xa5d5, 0xa5d4, 0xb5d5, 0x3001, 0x31d8, 0x31da, 0x3001
    .hword 0xa5dc, 0xb5dd, 0xc5dc, 0xc5dd, 0xa5dc, 0xa5dd, 0x3001, 0x31d8, 0x31da, 0x3001
    .hword 0xb5d4, 0xb5d5, 0xa5d4, 0xb5d5, 0xa5d4, 0xc5d5, 0x3001, 0x31d8, 0x31da, 0x3001
    .hword 0xc5dc, 0xa5dd, 0xb5dc, 0xa5dd, 0xc5e4, 0xa5e5, 0x3001, 0x31d8, 0x31da, 0x3001
    .hword 0xa5d4, 0xb5d5, 0xc5d4, 0xc5d5, 0x3001, 0x3004, 0x3001, 0x31d8, 0x31da, 0x3001
    .hword 0xb5e4, 0xb5e5, 0xc5e4, 0xb5e5, 0x3004, 0x3001, 0x3001, 0x31d8, 0x31da, 0x3001
    .hword 0xc540, 0x3001, 0x3001, 0x3001, 0x3001, 0x3001, 0x31d0, 0x31d9, 0x31da, 0x3001
    .hword 0xa540, 0x3001, 0xb41e, 0xb41f, 0x3001, 0x31d0, 0x31d9, 0x31d9, 0x31e2, 0x3001
    .hword 0xb540, 0x3001, 0xc426, 0xa427, 0x3001, 0x31d8, 0x31d9, 0x31e2, 0x3001, 0x3001
    .hword 0xc540, 0x3001, 0x31d0, 0x31d1, 0x31d1, 0x31d9, 0x31da, 0x3001, 0x3001, 0x3004
    .hword 0xa532, 0x3001, 0x31e0, 0x31e1, 0x31e1, 0x31e1, 0x31e2, 0x3001, 0x3004, 0x3001
    .hword 0x31ce, 0x31cf, 0x31ce, 0x31cf, 0x31ce, 0x31cf, 0x31ce, 0x31cf, 0x31ce, 0x31cf
    .hword 0xa5d4, 0xc5d5, 0xa5d4, 0xa5d5, 0xa5d4, 0xa5d5, 0xa5d4, 0xa5d5, 0xb5d4, 0xb5d5
    .hword 0xa5dc, 0xc5dd, 0xa5dc, 0xc5dd, 0xb5dc, 0xc5dd, 0xa5dc, 0xb5dd, 0xa5dc, 0xa5dd

.align 4
StrangeBush_MapConnections:
    .hword 0x0932
    .byte 14, 154
    .hword 0x0932
    .byte 14, 154
    .hword 0x0932
    .byte 14, 154
    .hword 0x0932
    .byte 14, 154

.align 4
StrangeBush_MapName:
    .string "STRANGE BUSH$"

# scripts/0A32_StrangeBush.s

.align 4

StrangeBush_MapInitCode:
    push {lr}
    ldr r0, =0x402A
    ldr r1, =GetVarPointer+1
    bl StrangeBush_BXR1
    mov r1, #0
    strb r1, [r0]
    pop {r1}
StrangeBush_BXR1:
    bx r1

.ltorg
.align 4

StrangeBush_MapInitScript:
    end

StrangeBush_Script:
    lock
    braillemessage StrangeBush_Braille
	waitbuttonpress
	closebraillemessage
    checkflag FLAG_UNDERGROUND_CAVE_PUZZLE1
    goto_if TRUE, StrangeBush_Script_Ignore
    compare_var_to_value 0x402A, 20
    goto_if_eq StrangeBush_Success
StrangeBush_Script_Ignore:
    releaseall
    end

StrangeBush_Success:
    playse SE_TRUCK_MOVE
	callnative DoSealedChamberShakingEffect1
	waitstate
	delay 40
	playse SE_DOOR
	delay 40
    msgbox StrangeBush_Script_Text
    setflag FLAG_UNDERGROUND_CAVE_PUZZLE1
    releaseall
    end

StrangeBush_Braille:
    .byte 13, 37, 69, 4, 2, 0
    .braille "ONCE ENTERED\n"
    .braille "WALK TWENTY\n"
    .braille "STEPS TOTAL$"

StrangeBush_Script_Text:
    .string "It sounded as if a door opened\n"
    .string "far, far below you.$"
