# fools2022 - autogenerated map file, please do not change!
# created from: pokeemerald/data/maps/x0B2D_StrangeRock/map.json

.thumb
.include "include/constants.inc"
.org MAP_LOAD_BASE

.include "include/macros.inc"
.include "include/symbols.inc"
.include "include/map.inc"
.include "include/event.inc"
.include "include/save.inc"

StrangeRock_MapHeader:
    .word StrangeRock_MapLayout
    .word StrangeRock_MapEvts
    .word NULL
    .word NULL
    .hword MUS_RG_SEVII_CAVE
    .hword 0
    .byte 0
    .byte 0
    .byte WEATHER_NONE
    .byte 0
    .hword 0
    map_header_flags allow_cycling=1, allow_escaping=1, allow_running=1, show_map_name=1
    .byte 0
    # additional data specific to fools2022 maps
    .word StrangeRock_MapInitCode+1
    .word StrangeRock_MapConnections
    .word StrangeRock_MapInitScript
    .word StrangeRock_MapName
    .word 0x1518

StrangeRock_MapLayout:
    .word 10
    .word 16
    .word StrangeRock_MapBorder
    .word StrangeRock_MapData
    .word gTileset_General
    .word gTileset_Petalburg

.align 4
StrangeRock_MapObjectEvents:

.align 4
StrangeRock_MapCoordEvents:
    coord_event 0, 7, 0, SCRIPT_NO_TRIGGER, 0, StrangeRock_OnSurf
StrangeRock_WarpCoordEvents:
    coord_event 6, 8, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT
    coord_event 7, 8, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT
    coord_event 8, 8, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT
    coord_event 9, 8, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT

.align 4
StrangeRock_MapBGEvents:
    bg_event 3, 4, 0, BG_EVENT_PLAYER_FACING_ANY, StrangeRock_Script
    bg_event 2, 4, 0, BG_EVENT_PLAYER_FACING_ANY, StrangeRock_Script

.align 4
StrangeRock_MapEvts:
    map_events 0, StrangeRock_MapObjectEvents, 0, 0, 5, StrangeRock_MapCoordEvents, 2, StrangeRock_MapBGEvents

.align 4
StrangeRock_MapBorder:
    .byte 0xd4, 0x01, 0xd5, 0x01, 0xdc, 0x01, 0xdd, 0x01

.align 4
StrangeRock_MapData:
    .hword 0xb5d4, 0xc5d5, 0xb5d4, 0xb5d5, 0xa5d4, 0xc5d5, 0xb5d4, 0xb5d5, 0xb5d4, 0xa5d5
    .hword 0xa5e4, 0xb5e5, 0xa5e4, 0xa5e5, 0xa5e4, 0xb5e5, 0xc5e4, 0xb5e5, 0xb5e4, 0xb5e5
    .hword 0xb540, 0x3001, 0x3001, 0x3001, 0x3001, 0x3001, 0x3001, 0x3001, 0x3001, 0x3001
    .hword 0xa540, 0x3001, 0xa483, 0xc484, 0x3001, 0x3001, 0x3001, 0x3001, 0x3001, 0x3001
    .hword 0xb540, 0x3001, 0xc48b, 0xc48c, 0x3001, 0x3001, 0x3001, 0x3001, 0x3001, 0x3001
    .hword 0xa540, 0x3001, 0x31d0, 0x31d1, 0x31d1, 0x31d1, 0x31d1, 0x31d1, 0x31d2, 0x3001
    .hword 0xa532, 0x3001, 0x31e0, 0x31e1, 0x31e1, 0x31e1, 0x31e1, 0x31d9, 0x31da, 0x3001
    .hword 0x31ce, 0x31cf, 0x31ce, 0x31cf, 0x31ce, 0x31cf, 0x3001, 0x31d8, 0x31da, 0x3001
    .hword 0xc5d4, 0xc5d5, 0xc5d4, 0xb5d5, 0xb5d4, 0xa5d5, 0x3001, 0x31d8, 0x31da, 0x3001
    .hword 0xa5dc, 0xb5dd, 0xa5dc, 0xc5dd, 0xa5dc, 0xb5dd, 0x3001, 0x31d8, 0x31da, 0x3001
    .hword 0xb5d4, 0xb5d5, 0xa5d4, 0xa5d5, 0xb5d4, 0xc5d5, 0x3001, 0x31d8, 0x31da, 0x3001
    .hword 0xb5dc, 0xa5dd, 0xb5dc, 0xc5dd, 0xb5dc, 0xc5dd, 0x3001, 0x31d8, 0x31da, 0x3001
    .hword 0xc5d4, 0xc5d5, 0xa5d4, 0xa5d5, 0xb5d4, 0xb5d5, 0x3001, 0x31d8, 0x31da, 0x3001
    .hword 0xb5dc, 0xb5dd, 0xc5dc, 0xb5dd, 0xa5dc, 0xc5dd, 0x3001, 0x31d8, 0x31da, 0x3001
    .hword 0xb5d4, 0xb5d5, 0xb5d4, 0xb5d5, 0xc5d4, 0xb5d5, 0x3001, 0x31d8, 0x31da, 0x3001
    .hword 0xa5dc, 0xb5dd, 0xa5dc, 0xc5dd, 0xc5dc, 0xc5dd, 0x3001, 0x31d8, 0x31da, 0x3001

.align 4
StrangeRock_MapConnections:
    .hword 0x0932
    .byte 14, 9
    .hword 0x0932
    .byte 14, 9
    .hword 0x0932
    .byte 14, 9
    .hword 0x0932
    .byte 14, 9

.align 4
StrangeRock_MapName:
    .string "STRANGE ROCK$"

# scripts/0B2D_StrangeRock.s

.align 4

StrangeRock_MapInitCode:
    bx lr

StrangeRock_MapInitScript:
    setvar VAR_TEMP_1, 0
    end

StrangeRock_Script:
    lock
    braillemessage StrangeRock_Braille
	waitbuttonpress
	closebraillemessage
    releaseall
    end

StrangeRock_OnSurf:
    checkflag FLAG_UNDERGROUND_CAVE_PUZZLE2
    goto_if TRUE, StrangeRock_Backoff
    addvar VAR_TEMP_1, 1
    compare_var_to_value VAR_TEMP_1, 5
    goto_if_eq StrangeRock_Success
StrangeRock_Backoff:
    releaseall
    end
StrangeRock_Success:
    playse SE_TRUCK_MOVE
	callnative DoSealedChamberShakingEffect1
	waitstate
	delay 40
	playse SE_DOOR
	delay 40
    msgbox StrangeRock_Script_Text
    setflag FLAG_UNDERGROUND_CAVE_PUZZLE2
    releaseall
    end

StrangeRock_Braille:
    .byte 13, 37, 69, 4, 2, 0
    .braille "GO TO HOLE IN\n"
    .braille "THE FENCE\n"
    .braille "FIVE TIMES$"

StrangeRock_Script_Text:
    .string "It sounded as if a door opened\n"
    .string "far, far below you.$"

