# fools2022 - autogenerated map file, please do not change!
# created from: pokeemerald/data/maps/x106D_TheWiseMan/map.json

.thumb
.include "include/constants.inc"
.org MAP_LOAD_BASE

.include "include/macros.inc"
.include "include/symbols.inc"
.include "include/map.inc"
.include "include/event.inc"
.include "include/save.inc"

TheWiseMan_MapHeader:
    .word TheWiseMan_MapLayout
    .word TheWiseMan_MapEvts
    .word NULL
    .word NULL
    .hword MUS_RG_FUCHSIA
    .hword 0
    .byte 0
    .byte 0
    .byte WEATHER_NONE
    .byte 0
    .hword 0
    map_header_flags allow_cycling=1, allow_escaping=1, allow_running=1, show_map_name=1
    .byte 0
    # additional data specific to fools2022 maps
    .word TheWiseMan_MapInitCode+1
    .word TheWiseMan_MapConnections
    .word TheWiseMan_MapInitScript
    .word TheWiseMan_MapName
    .word 0x2819

TheWiseMan_MapLayout:
    .word 10
    .word 9
    .word TheWiseMan_MapBorder
    .word TheWiseMan_MapData
    .word gTileset_Building
    .word gTileset_GenericBuilding

.align 4
TheWiseMan_MapObjectEvents:
    object_event 1, OBJ_EVENT_GFX_BIRCHS_BAG, 0, 8, 4, 3, MOVEMENT_TYPE_NONE, 0, 0, TRAINER_TYPE_NONE, 0, TheWiseMan_Script1, 0

.align 4
TheWiseMan_MapCoordEvents:
TheWiseMan_WarpCoordEvents:
    coord_event 3, 8, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT
    coord_event 4, 8, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT

.align 4
TheWiseMan_MapBGEvents:

.align 4
TheWiseMan_MapEvts:
    map_events 1, TheWiseMan_MapObjectEvents, 0, 0, 2, TheWiseMan_MapCoordEvents, 0, TheWiseMan_MapBGEvents

.align 4
TheWiseMan_MapBorder:
    .byte 0x01, 0x02, 0x01, 0x02, 0x01, 0x02, 0x01, 0x02

.align 4
TheWiseMan_MapData:
    .hword 0xb686, 0xc687, 0xa679, 0xa67a, 0xc605, 0xc607, 0xb605, 0xc605, 0xb605, 0xb605
    .hword 0xa68e, 0xa68f, 0xc681, 0xb682, 0xc60d, 0xb60f, 0xb60d, 0xb60d, 0xa690, 0xc690
    .hword 0x3296, 0x3297, 0x3289, 0x328a, 0x3224, 0x3224, 0x3224, 0x3224, 0xc698, 0xa698
    .hword 0x3239, 0x3235, 0x3236, 0x3236, 0x3236, 0x3236, 0x3236, 0x3237, 0x3223, 0x3223
    .hword 0x3239, 0x323d, 0x32e1, 0xb648, 0xa649, 0x32e2, 0x323e, 0x323f, 0x3223, 0x3223
    .hword 0x3239, 0x323d, 0x32e1, 0xa650, 0xb651, 0x32e2, 0x323e, 0x323f, 0x3223, 0x3223
    .hword 0x3239, 0x3245, 0x3246, 0x3246, 0x3246, 0x3246, 0x3246, 0x3247, 0x3223, 0x3223
    .hword 0x3239, 0x3223, 0x3223, 0x3223, 0x3223, 0x3223, 0x3223, 0x3223, 0x3223, 0x3222
    .hword 0x3239, 0x3223, 0x3223, 0x0208, 0x0209, 0x3223, 0x3223, 0x3223, 0x3223, 0xa62a

.align 4
TheWiseMan_MapConnections:
    .hword 4155
    .byte 3, 13
    .hword 4155
    .byte 3, 13

.align 4
TheWiseMan_MapName:
    .string "THE WISE MAN$"

# scripts/106D_TheWiseMan.s

.align 4

TheWiseMan_MapInitCode:
    ldr r0, =zSkipMapExitMovement
    mov r1, #2
    strb r1, [r0]
    bx lr

.align 4
.ltorg

TheWiseMan_MapInitScript:
    end

TheWiseMan_Script1:
    lock
    faceplayer
    msgbox TheWiseMan_Script1_Text, MSGBOX_YESNO
    compare VAR_RESULT, NO
    goto_if_eq TheWiseMan_Script1_Out
    msgbox TheWiseMan_Script1_Text2, MSGBOX_YESNO
    compare VAR_RESULT, NO
    goto_if_eq TheWiseMan_Script1_Out
    msgbox TheWiseMan_Script1_Text3, MSGBOX_YESNO
    compare VAR_RESULT, NO
    goto_if_eq TheWiseMan_Script1_Out
    msgbox TheWiseMan_Script1_Text4, MSGBOX_YESNO
    compare VAR_RESULT, NO
    goto_if_eq TheWiseMan_Script1_Out
    msgbox TheWiseMan_Script1_Text5
TheWiseMan_Script1_Out:
    release
    end

TheWiseMan_Script1_Text:
    .string "It's the Wise Man's Adventure Log!\n"
    .string "Let's take a quick look...\p"
    .string "Chapter I - The Edges\n"
    .string "Travelling to each edge will reward\l"
    .string "you with a unique field ability.\p"
    .string "Visiting north grants SURF.\n"
    .string "Visiting south grants CUT.\p"
    .string "Visiting east grants STRENGTH.\n"
    .string "Visiting west grants TELEPORT.\p"
    .string "Read the next page?$"

TheWiseMan_Script1_Text2:
    .string "Chapter II - About the North\n"
    .string "The northern fork is surely the\l"
    .string "biggest, but don't fear its size.\p"
    .string "While the journey may be long, there\n"
    .string "are no obstacles on the way, making\l"
    .string "it one of the best edges to visit first.\p"
    .string "Read the next page?$"

TheWiseMan_Script1_Text3:
    .string "Chapter III - About the South\n"
    .string "After the rockfall incident, the path\l"
    .string "to the Southern Edge is blocked by\l"
    .string "pushable boulders.\p"
    .string "Make sure you have enough STRENGTH\n"
    .string "before going for the Southern Edge!\p"
    .string "Read the next page?$"

TheWiseMan_Script1_Text4:
    .string "Chapter IV - About the West\n"
    .string "The TELEPORT ability allows you to\l"
    .string "travel between camps easily.\p"
    .string "Just stand on the hallowed ground\n"
    .string "spots and choose your destination!\p"
    .string "Be wary that you have to visit your\n"
    .string "destination at least once beforehand.\p"
    .string "Read the next page?$"

TheWiseMan_Script1_Text5:
    .string "Chapter V - About the East\n"
    .string "The Lost Woods may be confusing, but\l"
    .string "if you ask the locals, you can easily\l"
    .string "get information about where to go!\p"
    .string "Reaching the Edge is particularly easy.\n"
    .string "Just help the girl do her homework.\p"
    .string "If you're bad at maths, you can just\n"
    .string "keep pestering her until she gives in.\p"
    .string "The rest of the pages are blank...$"
