# fools2022 - autogenerated map file, please do not change!
# created from: pokeemerald/data/maps/x116E_HarborHouse/map.json

.thumb
.include "include/constants.inc"
.org MAP_LOAD_BASE

.include "include/macros.inc"
.include "include/symbols.inc"
.include "include/map.inc"
.include "include/event.inc"
.include "include/save.inc"

HarborHouse_MapHeader:
    .word HarborHouse_MapLayout
    .word HarborHouse_MapEvts
    .word NULL
    .word NULL
    .hword MUS_RG_FUCHSIA
    .hword 0
    .byte 0
    .byte 0
    .byte WEATHER_NONE
    .byte 0
    .hword 0
    map_header_flags allow_cycling=1, allow_escaping=1, allow_running=1, show_map_name=1
    .byte 0
    # additional data specific to fools2022 maps
    .word HarborHouse_MapInitCode+1
    .word HarborHouse_MapConnections
    .word HarborHouse_MapInitScript
    .word HarborHouse_MapName
    .word 0x2819

HarborHouse_MapLayout:
    .word 10
    .word 9
    .word HarborHouse_MapBorder
    .word HarborHouse_MapData
    .word gTileset_Building
    .word gTileset_GenericBuilding

.align 4
HarborHouse_MapObjectEvents:
    object_event 1, OBJ_EVENT_GFX_FISHERMAN, 0, 5, 4, 3, MOVEMENT_TYPE_FACE_LEFT, 0, 0, TRAINER_TYPE_NONE, 0, HarborHouse_Script1, 0

.align 4
HarborHouse_MapCoordEvents:
HarborHouse_WarpCoordEvents:
    coord_event 3, 8, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT
    coord_event 4, 8, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT

.align 4
HarborHouse_MapBGEvents:

.align 4
HarborHouse_MapEvts:
    map_events 1, HarborHouse_MapObjectEvents, 0, 0, 2, HarborHouse_MapCoordEvents, 0, HarborHouse_MapBGEvents

.align 4
HarborHouse_MapBorder:
    .byte 0x01, 0x02, 0x01, 0x02, 0x01, 0x02, 0x01, 0x02

.align 4
HarborHouse_MapData:
    .hword 0xb686, 0xa687, 0xb679, 0xa67a, 0xb605, 0xa607, 0xc605, 0xb605, 0xa605, 0xa605
    .hword 0xa68e, 0xb68f, 0xc681, 0xc682, 0xa60d, 0xc60f, 0xb60d, 0xa60d, 0xb690, 0xa690
    .hword 0x3296, 0x3297, 0x3289, 0x328a, 0x3224, 0x3224, 0x3224, 0x3224, 0xc698, 0xb698
    .hword 0x3239, 0x3235, 0x3236, 0x3236, 0x3236, 0x3236, 0x3236, 0x3237, 0x3223, 0x3223
    .hword 0x3239, 0x323d, 0x32e1, 0xc648, 0xa649, 0x32e2, 0x323e, 0x323f, 0x3223, 0x3223
    .hword 0x3239, 0x323d, 0x32e1, 0xb650, 0xc651, 0x32e2, 0x323e, 0x323f, 0x3223, 0x3223
    .hword 0x3239, 0x3245, 0x3246, 0x3246, 0x3246, 0x3246, 0x3246, 0x3247, 0x3223, 0x3223
    .hword 0x3239, 0x3223, 0x3223, 0x3223, 0x3223, 0x3223, 0x3223, 0x3223, 0x3223, 0x3222
    .hword 0x3239, 0x3223, 0x3223, 0x0208, 0x0209, 0x3223, 0x3223, 0x3223, 0x3223, 0xb62a

.align 4
HarborHouse_MapConnections:
    .hword 4413
    .byte 27, 15
    .hword 4413
    .byte 27, 15

.align 4
HarborHouse_MapName:
    .string "HARBOR HOUSE$"

# scripts/116E_HarborHouse.s

.align 4

HarborHouse_MapInitCode:
    ldr r0, =zSkipMapExitMovement
    mov r1, #2
    strb r1, [r0]
    bx lr

.align 4
.ltorg

HarborHouse_MapInitScript:
    end

HarborHouse_Script1:
    lock
    faceplayer
    checkflag FLAG_RECEIVED_VOUCHER
    goto_if TRUE, HarborHouse_Script1_Done
    msgbox HarborHouse_Script1_Text_Q, MSGBOX_YESNO
    compare VAR_RESULT, NO
    goto_if_eq HarborHouse_Script1_N
    msgbox HarborHouse_Script1_Text_Y
    setflag FLAG_RECEIVED_VOUCHER
    giveitem 352
    call SyncProgressScript
HarborHouse_Script1_Done:
    msgbox HarborHouse_Script1_Text_Y2
    release
    end

HarborHouse_Script1_N:
    msgbox HarborHouse_Script1_Text_N
    release
    end

HarborHouse_Script1_Text_Q:
    .string "Hello! I'm the Fishing Guru!\n"
    .string "Do you like to fish?$"

HarborHouse_Script1_Text_Y:
    .string "You do? That's great.\n"
    .string "I appreciate that.\p"
    .string "... ... ... ... ... ...\n"
    .string "... ... ... ... ... ...\p"
    .string "What? You really thought I'm going\n"
    .string "to give you a free fishing rod?\p"
    .string "Sorry, giving stuff for free isn't\n"
    .string "really a good business strategy.\p"
    .string "However, I can make up for it with\n"
    .string "something much better than a rod!$"

HarborHouse_Script1_Text_Y2:
    .string "Take that coupon to our BIKE SHOP\n"
    .string "and trade it for a free BIKE!\p"
    .string "Maybe they're more convinced to\n"
    .string "give out free stuff than I am!$"

HarborHouse_Script1_Text_N:
    .string "Oh, you don't?\n"
    .string "That's really disappointing...$"
