# fools2022 - autogenerated map file, please do not change!
# created from: pokeemerald/data/maps/x123D_UnknownHouse/map.json

.thumb
.include "include/constants.inc"
.org MAP_LOAD_BASE

.include "include/macros.inc"
.include "include/symbols.inc"
.include "include/map.inc"
.include "include/event.inc"
.include "include/save.inc"

UnknownHouse_MapHeader:
    .word UnknownHouse_MapLayout
    .word UnknownHouse_MapEvts
    .word NULL
    .word NULL
    .hword MUS_MT_PYRE_EXTERIOR
    .hword 0
    .byte 0
    .byte 0
    .byte WEATHER_NONE
    .byte 0
    .hword 0
    map_header_flags allow_cycling=1, allow_escaping=1, allow_running=1, show_map_name=1
    .byte 0
    # additional data specific to fools2022 maps
    .word UnknownHouse_MapInitCode+1
    .word UnknownHouse_MapConnections
    .word UnknownHouse_MapInitScript
    .word UnknownHouse_MapName
    .word 0x2819

UnknownHouse_MapLayout:
    .word 16
    .word 12
    .word UnknownHouse_MapBorder
    .word UnknownHouse_MapData
    .word gTileset_General
    .word gTileset_Petalburg

.align 4
UnknownHouse_MapObjectEvents:

.align 4
UnknownHouse_MapCoordEvents:
UnknownHouse_WarpCoordEvents:
    coord_event 7, 7, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT
    coord_event 7, 8, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT
    coord_event 7, 9, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT
    coord_event 7, 10, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT
    coord_event 7, 11, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT

.align 4
UnknownHouse_MapBGEvents:
    bg_event 12, 3, 0, BG_EVENT_PLAYER_FACING_ANY, UnknownHouse_Script
    bg_event 13, 3, 0, BG_EVENT_PLAYER_FACING_ANY, UnknownHouse_Script

.align 4
UnknownHouse_MapEvts:
    map_events 0, UnknownHouse_MapObjectEvents, 0, 0, 5, UnknownHouse_MapCoordEvents, 2, UnknownHouse_MapBGEvents

.align 4
UnknownHouse_MapBorder:
    .byte 0xd4, 0x01, 0xd5, 0x01, 0xdc, 0x01, 0xdd, 0x01

.align 4
UnknownHouse_MapData:
    .hword 0xc5d4, 0xb5d5, 0xc5d4, 0xb5d5, 0xb5d4, 0xa5d5, 0xc5d4, 0xb5d5, 0xc5d4, 0xc5d5, 0xc408, 0xc409, 0xc409, 0xb40a, 0xa5d4, 0xa5d5
    .hword 0xc5dc, 0xc5dd, 0xb5dc, 0xb5dd, 0xb5dc, 0xa5dd, 0xa5dc, 0xb5dd, 0xb5dc, 0xa5dd, 0xa410, 0xc411, 0xb411, 0xb412, 0xc5dc, 0xb5dd
    .hword 0xa5d4, 0xc5d5, 0xb5d4, 0xb5d5, 0xc5d4, 0xb5d5, 0xb5d4, 0xb5d5, 0xa5d4, 0xc5d5, 0xb418, 0xa40c, 0xa419, 0xc41a, 0xc5d4, 0xb5d5
    .hword 0xb5dc, 0xc5dd, 0xa5dc, 0xa5dd, 0xa5dc, 0xc5dd, 0xc5dc, 0xb5dd, 0xa5dc, 0xb5dd, 0xc420, 0xa414, 0xa421, 0xb422, 0xc5e4, 0xc5e5
    .hword 0xb5d4, 0xb5d5, 0xb5d4, 0xc5d5, 0xb5d4, 0xa5d5, 0xc5d4, 0xa5d5, 0xc5d4, 0xc5d5, 0xa538, 0xb549, 0x3001, 0x3001, 0xc549, 0xb53a
    .hword 0xb5e4, 0xc5e5, 0xa5e4, 0xb5e5, 0xa5e4, 0xb5e5, 0xa5e4, 0xb5e5, 0xb5e4, 0xb5e5, 0xc539, 0x3001, 0x3001, 0x3001, 0x3001, 0xb542
    .hword 0xc549, 0xb549, 0xa549, 0xc549, 0xc549, 0xb549, 0xc549, 0xb549, 0xc549, 0xa549, 0xb532, 0x3001, 0x3100, 0x3102, 0x3001, 0xc542
    .hword 0x3001, 0x3001, 0x3001, 0x3001, 0x3001, 0x3001, 0x3001, 0x3001, 0x3001, 0x3001, 0x3001, 0x3004, 0x3108, 0x310a, 0x3001, 0xa542
    .hword 0x3101, 0x3101, 0x3101, 0x3101, 0x3101, 0x3101, 0x3101, 0x3101, 0x3101, 0x3101, 0x3101, 0x3101, 0x3109, 0x310a, 0x3004, 0xb533
    .hword 0x3111, 0x3111, 0x3111, 0x3111, 0x3111, 0x3111, 0x3111, 0x3111, 0x3111, 0x3111, 0x3111, 0x3111, 0x3111, 0x3112, 0x3001, 0x300d
    .hword 0x3001, 0x3001, 0x3001, 0x3001, 0x3001, 0x3001, 0x3001, 0x3004, 0x3001, 0x3004, 0x3001, 0x3001, 0x3001, 0x3001, 0x3001, 0x300d
    .hword 0x31ce, 0x31cf, 0x31ce, 0x31cf, 0x31ce, 0x31cf, 0x31ce, 0x31cf, 0x31ce, 0x31cf, 0x31ce, 0x31cf, 0x31ce, 0x31cf, 0x31c6, 0x31c7

.align 4
UnknownHouse_MapConnections:
    .hword 0x113d
    .byte 160, 26
    .hword 0x113d
    .byte 160, 26
    .hword 0x113d
    .byte 160, 26
    .hword 0x113d
    .byte 160, 26
    .hword 0x113d
    .byte 160, 26

.align 4
UnknownHouse_MapName:
    .string "UNKNOWN HOUSE$"

# scripts/123D_UnknownHouse.s

.align 4

UnknownHouse_MapInitCode:
    bx lr

.ltorg
.align 4

UnknownHouse_MapInitScript:
    end

UnknownHouse_Script:
    lock
    msgbox UnknownHouse_Script_Text_Q, MSGBOX_YESNO
    compare VAR_RESULT, NO
    goto_if_eq UnknownHouse_Script_N
    compare_addr_to_value UnknownHouse_FunValue, 0xd0
    goto_if_lt UnknownHouse_Script_A
    compare_addr_to_value UnknownHouse_FunValue, 0xf0
    goto_if_lt UnknownHouse_Script_B
    msgbox UnknownHouse_Script_Text3
    release
    end
UnknownHouse_Script_A:
    msgbox UnknownHouse_Script_Text1
    release
    end
UnknownHouse_Script_B:
    msgbox UnknownHouse_Script_Text2
    release
    end
UnknownHouse_Script_N:
    msgbox UnknownHouse_Script_Text_N
    release
    end

UnknownHouse_Script_Text_Q:
    .string "The door is firmly shut, but some\n"
    .string "people seem to be talking inside...\l"
    .string "Eavesdrop on the conversation?$"

UnknownHouse_Script_Text_N:
    .string "You give up on the immoral act of\n"
    .string "eavesdropping.$"

UnknownHouse_Script_Text1:
    .string "You listen closely, but the voices\n"
    .string "inside have quietened considerably.\l"
    .string "Now you can't hear anything.$"

UnknownHouse_Script_Text2:
    .string "You listen closely. You hear some people\n"
    .string "reminiscing of their times together.\l"
    .string "Sounds like a very close friend group.\p"
    .string "It's the kind of closeness some people\n"
    .string "crave, yet cannot experience...$"

UnknownHouse_Script_Text3:
    .string "You listen closely. You heard something\n"
    .string "about... someone being a dog?\l"
    .string "Cause a dog is a man's best friend.\p"
    .string "It does not make any sense, but maybe\n"
    .string "it's not supposed to.\p"
    .string "What the hell is Fidei?\n"
    .string "It's where dreams have died.$"

UnknownHouse_FunValue:
    .ascii "--FUNVAL--"
	.byte 0xff

