# fools2022 - autogenerated map file, please do not change!
# created from: pokeemerald/data/maps/x1337_Mysterious/map.json

.thumb
.include "include/constants.inc"
.org MAP_LOAD_BASE

.include "include/macros.inc"
.include "include/symbols.inc"
.include "include/map.inc"
.include "include/event.inc"
.include "include/save.inc"

Mysterious_MapHeader:
    .word Mysterious_MapLayout
    .word Mysterious_MapEvts
    .word NULL
    .word NULL
    .hword MUS_RG_SEVII_CAVE
    .hword 0
    .byte 0
    .byte 0
    .byte WEATHER_NONE
    .byte 0
    .hword 0
    map_header_flags allow_cycling=1, allow_escaping=1, allow_running=1, show_map_name=1
    .byte 0
    # additional data specific to fools2022 maps
    .word Mysterious_MapInitCode+1
    .word Mysterious_MapConnections
    .word Mysterious_MapInitScript
    .word Mysterious_MapName
    .word 0x2819

Mysterious_MapLayout:
    .word 5
    .word 5
    .word Mysterious_MapBorder
    .word Mysterious_MapData
    .word gTileset_General
    .word gTileset_Cave

.align 4
Mysterious_MapObjectEvents:
    object_event 1, OBJ_EVENT_GFX_ROUND_CUSHION, 0, 2, 1, 3, MOVEMENT_TYPE_NONE, 0, 0, TRAINER_TYPE_NONE, 0, Mysterious_Warp, 0

.align 4
Mysterious_MapCoordEvents:
Mysterious_WarpCoordEvents:

.align 4
Mysterious_MapBGEvents:

.align 4
Mysterious_MapEvts:
    map_events 1, Mysterious_MapObjectEvents, 0, 0, 0, Mysterious_MapCoordEvents, 0, Mysterious_MapBGEvents

.align 4
Mysterious_MapBorder:
    .byte 0xd9, 0x02, 0xd9, 0x02, 0xd9, 0x02, 0xd9, 0x02

.align 4
Mysterious_MapData:
    .hword 0xc6d3, 0xb6e1, 0xa6e1, 0xc6e1, 0xc6d4
    .hword 0xc6da, 0x32d9, 0x32d9, 0x32d9, 0xb6d8
    .hword 0xc6da, 0x32d9, 0x32d9, 0x32d9, 0xb6d8
    .hword 0xb6da, 0x32d9, 0x32d9, 0x32d9, 0xb6d8
    .hword 0xc6d1, 0xb6d1, 0xb6d1, 0xb6d1, 0xc6d1

.align 4
Mysterious_MapConnections:

.align 4
Mysterious_MapName:
    .string "MYSTERIOUS$"

# scripts/1337_Mysterious.s

.align 4

Mysterious_MapInitCode:
    bx lr

Mysterious_MapInitScript:
    end

Mysterious_Warp:
    lock
    faceplayer
    msgbox Mysterious_Warp_Text
    release
    end

Mysterious_Warp_Text:
    .string "You did very well.\n"
    .string "Please reset your game.$"
