# fools2022 - autogenerated map file, please do not change!
# created from: pokeemerald/data/maps/x146F_ShadyMerchant/map.json

.thumb
.include "include/constants.inc"
.org MAP_LOAD_BASE

.include "include/macros.inc"
.include "include/symbols.inc"
.include "include/map.inc"
.include "include/event.inc"
.include "include/save.inc"

ShadyMerchant_MapHeader:
    .word ShadyMerchant_MapLayout
    .word ShadyMerchant_MapEvts
    .word NULL
    .word NULL
    .hword MUS_RG_ROCKET_HIDEOUT
    .hword 0
    .byte 0
    .byte 0
    .byte WEATHER_NONE
    .byte 0
    .hword 0
    map_header_flags allow_cycling=1, allow_escaping=1, allow_running=1, show_map_name=1
    .byte 0
    # additional data specific to fools2022 maps
    .word ShadyMerchant_MapInitCode+1
    .word ShadyMerchant_MapConnections
    .word ShadyMerchant_MapInitScript
    .word ShadyMerchant_MapName
    .word 0x2819

ShadyMerchant_MapLayout:
    .word 6
    .word 6
    .word ShadyMerchant_MapBorder
    .word ShadyMerchant_MapData
    .word gTileset_Building
    .word gTileset_PrettyPetalFlowerShop

.align 4
ShadyMerchant_MapObjectEvents:
    object_event 1, OBJ_EVENT_GFX_BARD, 0, 0, 3, 3, MOVEMENT_TYPE_FACE_RIGHT, 0, 0, TRAINER_TYPE_NONE, 0, ShadyMerchant_Script, 0

.align 4
ShadyMerchant_MapCoordEvents:
ShadyMerchant_WarpCoordEvents:
    coord_event 3, 5, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT
    coord_event 4, 5, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT

.align 4
ShadyMerchant_MapBGEvents:

.align 4
ShadyMerchant_MapEvts:
    map_events 1, ShadyMerchant_MapObjectEvents, 0, 0, 2, ShadyMerchant_MapCoordEvents, 0, ShadyMerchant_MapBGEvents

.align 4
ShadyMerchant_MapBorder:
    .byte 0x01, 0x00, 0x01, 0x00, 0x01, 0x00, 0x01, 0x00

.align 4
ShadyMerchant_MapData:
    .hword 0xb613, 0xb613, 0xb613, 0xb614, 0xb615, 0xc613
    .hword 0xb61b, 0xa61b, 0xc61b, 0xa61c, 0xc61d, 0xb61b
    .hword 0x3201, 0xc62f, 0x320b, 0x3203, 0x3203, 0x3203
    .hword 0x3201, 0xb637, 0x320c, 0x3201, 0x3201, 0x3201
    .hword 0x323e, 0xa63f, 0x320c, 0x3201, 0x3201, 0x3201
    .hword 0xb646, 0xc647, 0x3209, 0x3006, 0x3007, 0x3201

.align 4
ShadyMerchant_MapConnections:
    .hword 5170
    .byte 3, 3
    .hword 5170
    .byte 3, 3

.align 4
ShadyMerchant_MapName:
    .string "SHADY MERCHANT$"

# scripts/146F_ShadyMerchant.s

.align 4

ShadyMerchant_MapInitCode:
    ldr r0, =zSkipMapExitMovement
    mov r1, #2
    strb r1, [r0]
    bx lr

.align 4
.ltorg

ShadyMerchant_MapInitScript:
    end

ShadyMerchant_Script:
    lock
    faceplayer
    checkflag FLAG_FLUTE_RECEIVED
    goto_if TRUE, ShadyMerchant_Script_Done
    msgbox ShadyMerchant_Script_Text, MSGBOX_YESNO
    compare VAR_RESULT, YES
    goto_if_eq ShadyMerchant_Script_GiveNugget
    msgbox ShadyMerchant_Script_Text4
    release
    end
ShadyMerchant_Script_GiveNugget:
    checkflag FLAG_DUNSPARCE_SURVEY
    goto_if FALSE, ShadyMerchant_Script_NoNugget
    msgbox ShadyMerchant_Script_Text3
    giveitem 350
    setflag FLAG_FLUTE_RECEIVED
    call SyncProgressScript
    release
    end
ShadyMerchant_Script_NoNugget:
    msgbox ShadyMerchant_Script_Text2
    release
    end
ShadyMerchant_Script_Done:
    msgbox ShadyMerchant_Script_Text5
    release
    end

ShadyMerchant_Script_Text:
    .string "Hello, hello!\n"
    .string "Do I have a customer?\l"
    .string "Have I got the offer just for you!\p"
    .string "Bring me a NUGGET, and I'll trade\n"
    .string "it for this awesome POK{EACUTE} FLUTE!\p"
    .string "Near mint condition, only used once\n"
    .string "or twice! Do we have a deal?$"

ShadyMerchant_Script_Text2:
    .string "Oh, I'm sorry, I'm afraid you don't\n"
    .string "have a NUGGET...$"

ShadyMerchant_Script_Text3:
    .string "Great! We have a deal!\n"
    .string "Here, have this POK{EACUTE} FLUTE!$"

ShadyMerchant_Script_Text4:
    .string "Do as you want. Just remember, you won't\n"
    .string "find such a great deal anywhere else!$"

ShadyMerchant_Script_Text5:
    .string "What?\n"
    .string "I don't give any refunds.$"

