# fools2022 - autogenerated map file, please do not change!
# created from: pokeemerald/data/maps/x1671_NorthernEncampment/map.json

.thumb
.include "include/constants.inc"
.org MAP_LOAD_BASE

.include "include/macros.inc"
.include "include/symbols.inc"
.include "include/map.inc"
.include "include/event.inc"
.include "include/save.inc"

NorthernEncampment_MapHeader:
    .word NorthernEncampment_MapLayout
    .word NorthernEncampment_MapEvts
    .word NULL
    .word NULL
    .hword MUS_RG_FUCHSIA
    .hword 0
    .byte 0
    .byte 0
    .byte WEATHER_NONE
    .byte 0
    .hword 0
    map_header_flags allow_cycling=1, allow_escaping=1, allow_running=1, show_map_name=1
    .byte 0
    # additional data specific to fools2022 maps
    .word NorthernEncampment_MapInitCode+1
    .word NorthernEncampment_MapConnections
    .word NorthernEncampment_MapInitScript
    .word NorthernEncampment_MapName
    .word 0x0700

NorthernEncampment_MapLayout:
    .word 10
    .word 9
    .word NorthernEncampment_MapBorder
    .word NorthernEncampment_MapData
    .word gTileset_Building
    .word gTileset_GenericBuilding

.align 4
NorthernEncampment_MapObjectEvents:
    object_event 1, OBJ_EVENT_GFX_MANIAC, 0, 5, 4, 3, MOVEMENT_TYPE_FACE_LEFT, 0, 0, TRAINER_TYPE_NONE, 0, NorthernEncampment_Interior_Script1, 0

.align 4
NorthernEncampment_MapCoordEvents:
NorthernEncampment_WarpCoordEvents:
    coord_event 3, 8, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT
    coord_event 4, 8, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT

.align 4
NorthernEncampment_MapBGEvents:

.align 4
NorthernEncampment_MapEvts:
    map_events 1, NorthernEncampment_MapObjectEvents, 0, 0, 2, NorthernEncampment_MapCoordEvents, 0, NorthernEncampment_MapBGEvents

.align 4
NorthernEncampment_MapBorder:
    .byte 0x01, 0x02, 0x01, 0x02, 0x01, 0x02, 0x01, 0x02

.align 4
NorthernEncampment_MapData:
    .hword 0xb686, 0xb687, 0xb679, 0xc67a, 0xc605, 0xa607, 0xc605, 0xa605, 0xc605, 0xa605
    .hword 0xb68e, 0xa68f, 0xa681, 0xc682, 0xc60d, 0xb60f, 0xa60d, 0xc60d, 0xb690, 0xc690
    .hword 0x3296, 0x3297, 0x3289, 0x328a, 0x3224, 0x3224, 0x3224, 0x3224, 0xb698, 0xb698
    .hword 0x3239, 0x3235, 0x3236, 0x3236, 0x3236, 0x3236, 0x3236, 0x3237, 0x3223, 0x3223
    .hword 0x3239, 0x323d, 0x32e1, 0xc648, 0xa649, 0x32e2, 0x323e, 0x323f, 0x3223, 0x3223
    .hword 0x3239, 0x323d, 0x32e1, 0xc650, 0xc651, 0x32e2, 0x323e, 0x323f, 0x3223, 0x3223
    .hword 0x3239, 0x3245, 0x3246, 0x3246, 0x3246, 0x3246, 0x3246, 0x3247, 0x3223, 0x3223
    .hword 0x3239, 0x3223, 0x3223, 0x3223, 0x3223, 0x3223, 0x3223, 0x3223, 0x3223, 0x3222
    .hword 0x3239, 0x3223, 0x3223, 0x0208, 0x0209, 0x3223, 0x3223, 0x3223, 0x3223, 0xc62a

.align 4
NorthernEncampment_MapConnections:
    .hword 5681
    .byte 17, 15
    .hword 5681
    .byte 17, 15

.align 4
NorthernEncampment_MapName:
    .string "NORTHERN CAMP$"

# scripts/1671_NorthernEncampment.s

.align 4

NorthernEncampment_MapInitCode:
    ldr r0, =zSkipMapExitMovement
    mov r1, #2
    strb r1, [r0]
    bx lr

.align 4
.ltorg

NorthernEncampment_MapInitScript:
    end

NorthernEncampment_Interior_Script1:
    lock
    faceplayer
    checkflag FLAG_DELIRIA_PERMIT
    goto_if TRUE, NorthernEncampment_Interior_Script1_Done
    msgbox NorthernEncampment_Interior_Script1_Text
    setflag FLAG_DELIRIA_PERMIT
    message NorthernEncampment_Interior_Script1_Text_Received
    waitmessage
    playfanfare MUS_RG_OBTAIN_KEY_ITEM
    waitfanfare
    call SyncProgressScript
    release
    end
NorthernEncampment_Interior_Script1_Done:
    msgbox NorthernEncampment_Interior_Script1_Text_Done
    release
    end

NorthernEncampment_Interior_Script1_Text:
    .string "Deliria is the most fun place you\n"
    .string "can find in Glitchland.\p"
    .string "However, you need an special permit\n"
    .string "in order to get there.\p"
    .string "This is preposterous! Disallowing\n"
    .string "anyone from going there is cruel.\p"
    .string "That's why I give out forged permits\n"
    .string "for people who wish to visit Deliria.\p"
    .string "Do you want one? Here's one permit,\n"
    .string "free of charge. Let's liberate Deliria!$"

NorthernEncampment_Interior_Script1_Text_Received:
    .string "You received a forged Deliria permit\n"
    .string "from the mysterious man.$"

NorthernEncampment_Interior_Script1_Text_Done:
    .string "Go forth and explore Deliria as much\n"
    .string "as you want!$"

