# fools2022 - autogenerated map file, please do not change!
# created from: pokeemerald/data/maps/x1A3C_GameCorner/map.json

.thumb
.include "include/constants.inc"
.org MAP_LOAD_BASE

.include "include/macros.inc"
.include "include/symbols.inc"
.include "include/map.inc"
.include "include/event.inc"
.include "include/save.inc"

GameCorner_MapHeader:
    .word GameCorner_MapLayout
    .word GameCorner_MapEvts
    .word NULL
    .word NULL
    .hword MUS_RG_ROUTE11
    .hword 0
    .byte 0
    .byte 0
    .byte WEATHER_NONE
    .byte 0
    .hword 0
    map_header_flags allow_cycling=1, allow_escaping=1, allow_running=1, show_map_name=1
    .byte 0
    # additional data specific to fools2022 maps
    .word GameCorner_MapInitCode+1
    .word GameCorner_MapConnections
    .word GameCorner_MapInitScript
    .word GameCorner_MapName
    .word 0x2819

GameCorner_MapLayout:
    .word 20
    .word 10
    .word GameCorner_MapBorder
    .word GameCorner_MapData
    .word gTileset_General
    .word gTileset_Mauville

.align 4
GameCorner_MapObjectEvents:
    object_event 1, OBJ_EVENT_GFX_OLD_MAN, 0, 3, 4, 3, MOVEMENT_TYPE_FACE_UP, 0, 0, TRAINER_TYPE_NONE, 0, GameCorner_Script2, 0
    object_event 2, OBJ_EVENT_GFX_GENTLEMAN, 0, 10, 3, 3, MOVEMENT_TYPE_WANDER_LEFT_AND_RIGHT, 1, 0, TRAINER_TYPE_NONE, 0, GameCorner_Script1, 0

.align 4
GameCorner_MapCoordEvents:
GameCorner_WarpCoordEvents:
    coord_event 12, 4, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT
    coord_event 12, 5, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT
    coord_event 12, 6, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT
    coord_event 12, 7, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT
    coord_event 5, 3, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT

.align 4
GameCorner_MapBGEvents:

.align 4
GameCorner_MapEvts:
    map_events 2, GameCorner_MapObjectEvents, 0, 0, 5, GameCorner_MapCoordEvents, 0, GameCorner_MapBGEvents

.align 4
GameCorner_MapBorder:
    .byte 0xd4, 0x01, 0xd5, 0x01, 0xdc, 0x01, 0xdd, 0x01

.align 4
GameCorner_MapData:
    .hword 0xc5d4, 0xa5d5, 0xc6d8, 0xb6d9, 0xc6d9, 0xb6d9, 0xc6d9, 0xb6dc, 0xc5d4, 0xb5d5, 0xc5d4, 0xb5d5, 0xb5d4, 0xc5d5, 0xa5d4, 0xa5d5, 0xa5d4, 0xb5d5, 0xa5d4, 0xa5d5
    .hword 0xb5dc, 0xc5dd, 0xa6e0, 0xc6e1, 0xc6e1, 0xa6e1, 0xc6e1, 0xb6e4, 0xc5e4, 0xb5e5, 0xc5e4, 0xb5e5, 0xc5dc, 0xc5dd, 0xb5dc, 0xa5dd, 0xc5dc, 0xb5dd, 0xc5dc, 0xb5dd
    .hword 0xa5d4, 0xa5d5, 0xc6e8, 0xa6db, 0xa6e9, 0xc6ea, 0xc6eb, 0xb6ec, 0x3001, 0x3206, 0x3001, 0x3001, 0xc5d4, 0xb5d5, 0xc5d4, 0xb5d5, 0xb5d4, 0xb5d5, 0xa5d4, 0xc5d5
    .hword 0xc5dc, 0xb5dd, 0xb6d1, 0xc6e3, 0xc6d2, 0x32d3, 0xc6da, 0xb6e2, 0x3001, 0x3001, 0x3001, 0x3001, 0xb5e4, 0xc5e5, 0xa5e4, 0xc5e5, 0xa5e4, 0xa5e5, 0xb5e4, 0xa5e5
    .hword 0xb5d4, 0xa5d5, 0x3118, 0x3119, 0x3119, 0x3119, 0x3119, 0x3119, 0x3119, 0x3119, 0x311a, 0x3001, 0x3001, 0x3001, 0x3206, 0x3001, 0x3001, 0x3001, 0x3001, 0x3001
    .hword 0xc5dc, 0xa5dd, 0x3128, 0x3129, 0x3129, 0x3129, 0x3129, 0x3129, 0x3129, 0x3121, 0x3121, 0x3119, 0x3119, 0x3119, 0x3119, 0x3119, 0x3119, 0x3119, 0x3119, 0x3119
    .hword 0xb5d4, 0xc5d5, 0x3001, 0x3001, 0x3206, 0x3001, 0x3001, 0x3001, 0x3206, 0x3128, 0x3129, 0x3129, 0x3129, 0x3129, 0x3129, 0x3129, 0x3129, 0x3129, 0x3129, 0x3129
    .hword 0xa5dc, 0xc5dd, 0x31ce, 0x31cf, 0x31ce, 0x31cf, 0x31ce, 0x31cf, 0x31ce, 0x31cf, 0x31ce, 0x31cf, 0x31ce, 0x31cf, 0x31ce, 0x31cf, 0x31ce, 0x31cf, 0x31ce, 0x31cf
    .hword 0xa5d4, 0xc5d5, 0xc5d4, 0xa5d5, 0xc5d4, 0xc5d5, 0xa5d4, 0xc5d5, 0xa5d4, 0xc5d5, 0xc5d4, 0xa5d5, 0xc5d4, 0xb5d5, 0xa5d4, 0xb5d5, 0xc5d4, 0xc5d5, 0xa5d4, 0xa5d5
    .hword 0xa5dc, 0xa5dd, 0xb5dc, 0xc5dd, 0xb5dc, 0xc5dd, 0xb5dc, 0xb5dd, 0xa5dc, 0xa5dd, 0xa5dc, 0xb5dd, 0xb5dc, 0xa5dd, 0xb5dc, 0xb5dd, 0xb5dc, 0xc5dd, 0xa5dc, 0xc5dd

.align 4
GameCorner_MapConnections:
    .hword 0x1631
    .byte 139, 133
    .hword 0x1631
    .byte 139, 133
    .hword 0x1631
    .byte 139, 133
    .hword 0x1631
    .byte 139, 133
    .hword 6771
    .byte 2, 136

.align 4
GameCorner_MapName:
    .string "GAME CORNER$"

# scripts/1A3C_GameCorner.s

.align 4

GameCorner_MapInitCode:
    bx lr

GameCorner_MapInitScript:
    end

GameCorner_Script1:
    lock
    faceplayer
    msgbox GameCorner_Script1_Text
    release
    end

GameCorner_Script1_Text:
    .string "This guy's Glitchland Lottery\n"
    .string "results are crazy!\p"
    .string "My drawings can't win against drawings\n"
    .string "like that!\p"
    .string "He needed precisely these two letters\n"
    .string "to win.\p"
    .string "There was nothing I could do.\n"
    .string "I played that perfectly!$"

GameCorner_Script2:
    lock
    faceplayer
    msgbox GameCorner_Script2_Text
    release
    end

GameCorner_Script2_Text:
    .string "Heheh. This GAME CORNER is great.\n"
    .string "It's full of women!$"

