# fools2022 - autogenerated map file, please do not change!
# created from: pokeemerald/data/maps/x1F79_Deliria/map.json

.thumb
.include "include/constants.inc"
.org MAP_LOAD_BASE

.include "include/macros.inc"
.include "include/symbols.inc"
.include "include/map.inc"
.include "include/event.inc"
.include "include/save.inc"

Deliria_MapHeader:
    .word Deliria_MapLayout
    .word Deliria_MapEvts
    .word NULL
    .word NULL
    .hword MUS_RG_SEVII_CAVE
    .hword 0
    .byte 0
    .byte 0
    .byte WEATHER_NONE
    .byte 0
    .hword 0
    map_header_flags allow_cycling=1, allow_escaping=1, allow_running=1, show_map_name=1
    .byte 0
    # additional data specific to fools2022 maps
    .word Deliria_MapInitCode+1
    .word Deliria_MapConnections
    .word Deliria_MapInitScript
    .word Deliria_MapName
    .word 0x2200

Deliria_MapLayout:
    .word 2
    .word 2
    .word Deliria_MapBorder
    .word Deliria_MapData
    .word gTileset_Building
    .word gTileset_PrettyPetalFlowerShop

.align 4
Deliria_MapObjectEvents:
    object_event 1, OBJ_EVENT_GFX_MAN_5, 0, 1, 0, 3, MOVEMENT_TYPE_FACE_LEFT, 0, 0, TRAINER_TYPE_NONE, 0, Deliria_Interior_Script1, 0

.align 4
Deliria_MapCoordEvents:
Deliria_WarpCoordEvents:
    coord_event 0, 1, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT

.align 4
Deliria_MapBGEvents:

.align 4
Deliria_MapEvts:
    map_events 1, Deliria_MapObjectEvents, 0, 0, 1, Deliria_MapCoordEvents, 0, Deliria_MapBGEvents

.align 4
Deliria_MapBorder:
    .byte 0x01, 0x00, 0x01, 0x00, 0x01, 0x00, 0x01, 0x00

.align 4
Deliria_MapData:
    .hword 0x0203, 0x0203
    .hword 0x0006, 0x0007

.align 4
Deliria_MapConnections:
    .hword 7994
    .byte 19, 5

.align 4
Deliria_MapName:
    .string "DELIRIA$"

# scripts/1F79_Deliria.s

.align 4

Deliria_MapInitCode:
    ldr r0, =zSkipMapExitMovement
    mov r1, #2
    strb r1, [r0]
    bx lr

Deliria_MapInitScript:
    end

Deliria_Interior_Script1:
    lock
    faceplayer
    msgbox Deliria_Interior_Script1_Text
    release
    end

Deliria_Interior_Script1_Text:
    .string "{JPN}i like my house\n"
    .string "so spacious !!$"

