# fools2022 - autogenerated map file, please do not change!
# created from: pokeemerald/data/maps/x207B_Deliria/map.json

.thumb
.include "include/constants.inc"
.org MAP_LOAD_BASE

.include "include/macros.inc"
.include "include/symbols.inc"
.include "include/map.inc"
.include "include/event.inc"
.include "include/save.inc"

Deliria_MapHeader:
    .word Deliria_MapLayout
    .word Deliria_MapEvts
    .word NULL
    .word NULL
    .hword MUS_RG_SEVII_CAVE
    .hword 0
    .byte 0
    .byte 0
    .byte WEATHER_NONE
    .byte 0
    .hword 0
    map_header_flags allow_cycling=1, allow_escaping=1, allow_running=1, show_map_name=1
    .byte 0
    # additional data specific to fools2022 maps
    .word Deliria_MapInitCode+1
    .word Deliria_MapConnections
    .word Deliria_MapInitScript
    .word Deliria_MapName
    .word 0x2200

Deliria_MapLayout:
    .word 6
    .word 6
    .word Deliria_MapBorder
    .word Deliria_MapData
    .word gTileset_General
    .word gTileset_Petalburg

.align 4
Deliria_MapObjectEvents:

.align 4
Deliria_MapCoordEvents:
Deliria_WarpCoordEvents:

.align 4
Deliria_MapBGEvents:

.align 4
Deliria_MapEvts:
    map_events 0, Deliria_MapObjectEvents, 0, 0, 0, Deliria_MapCoordEvents, 0, Deliria_MapBGEvents

.align 4
Deliria_MapBorder:
    .byte 0xd4, 0x01, 0xd5, 0x01, 0xdc, 0x01, 0xdd, 0x01

.align 4
Deliria_MapData:
    .hword 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000
    .hword 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000
    .hword 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000
    .hword 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000
    .hword 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000
    .hword 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000

.align 4
Deliria_MapConnections:

.align 4
Deliria_MapName:
    .string "DELIRIA$"

# scripts/207B_Deliria.s

Deliria_MapInitCode:
    bx lr

Deliria_MapInitScript:
    end


