# fools2022 - autogenerated map file, please do not change!
# created from: pokeemerald/data/maps/x2174_BikeShop/map.json

.thumb
.include "include/constants.inc"
.org MAP_LOAD_BASE

.include "include/macros.inc"
.include "include/symbols.inc"
.include "include/map.inc"
.include "include/event.inc"
.include "include/save.inc"

BikeShop_MapHeader:
    .word BikeShop_MapLayout
    .word BikeShop_MapEvts
    .word NULL
    .word NULL
    .hword MUS_RG_FUCHSIA
    .hword 0
    .byte 0
    .byte 0
    .byte WEATHER_NONE
    .byte 0
    .hword 0
    map_header_flags allow_cycling=1, allow_escaping=1, allow_running=1, show_map_name=1
    .byte 0
    # additional data specific to fools2022 maps
    .word BikeShop_MapInitCode+1
    .word BikeShop_MapConnections
    .word BikeShop_MapInitScript
    .word BikeShop_MapName
    .word 0x2819

BikeShop_MapLayout:
    .word 12
    .word 9
    .word BikeShop_MapBorder
    .word BikeShop_MapData
    .word gTileset_General
    .word gTileset_BikeShop

.align 4
BikeShop_MapObjectEvents:
    object_event 1, OBJ_EVENT_GFX_MART_EMPLOYEE, 0, 3, 2, 3, MOVEMENT_TYPE_NONE, 0, 0, TRAINER_TYPE_NONE, 0, BikeShop_Script1, 0
    object_event 2, OBJ_EVENT_GFX_LASS, 0, 11, 2, 3, MOVEMENT_TYPE_FACE_LEFT, 0, 0, TRAINER_TYPE_NONE, 0, BikeShop_Script2, 0

.align 4
BikeShop_MapCoordEvents:
BikeShop_WarpCoordEvents:
    coord_event 3, 8, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT
    coord_event 4, 8, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT

.align 4
BikeShop_MapBGEvents:
    bg_event 8, 1, 0, BG_EVENT_PLAYER_FACING_ANY, BikeShop_Script3

.align 4
BikeShop_MapEvts:
    map_events 2, BikeShop_MapObjectEvents, 0, 0, 2, BikeShop_MapCoordEvents, 1, BikeShop_MapBGEvents

.align 4
BikeShop_MapBorder:
    .byte 0x08, 0x02, 0x08, 0x02, 0x08, 0x02, 0x08, 0x02

.align 4
BikeShop_MapData:
    .hword 0xa601, 0xc602, 0xc603, 0xc604, 0xb604, 0xa605, 0xc628, 0xc629, 0xb62a, 0xc62b, 0xc62b, 0xa62b
    .hword 0xb609, 0xb60a, 0xc60b, 0xa60c, 0xb60c, 0xb60d, 0xa630, 0xa631, 0xc632, 0xc633, 0xa633, 0xc633
    .hword 0xa611, 0xa612, 0xc613, 0x3214, 0x3215, 0x3216, 0xb638, 0x3239, 0x323a, 0x323b, 0x323b, 0x323b
    .hword 0xc619, 0xa61a, 0xa61b, 0xc61c, 0xa61d, 0xc61e, 0xb640, 0x3241, 0x3242, 0x323f, 0x3243, 0x3244
    .hword 0xa621, 0xa622, 0x3223, 0x3224, 0x3225, 0x3226, 0xb648, 0xa649, 0x324a, 0x323f, 0xc64b, 0xb64c
    .hword 0xa606, 0xa607, 0x323f, 0x323f, 0x323f, 0x323f, 0x3250, 0x3251, 0x3252, 0x323f, 0xa653, 0xa654
    .hword 0xc619, 0xb622, 0x323f, 0x323f, 0x323f, 0x323f, 0x323f, 0x323f, 0x323f, 0x323f, 0xc645, 0xb646
    .hword 0xc621, 0xc622, 0x323f, 0x323f, 0x323f, 0x323f, 0x323f, 0x323f, 0x323f, 0x323f, 0xa64d, 0xa64e
    .hword 0xa60e, 0xc60f, 0x323f, 0x3218, 0x3220, 0x323f, 0x323f, 0x323f, 0x323f, 0x323f, 0xa655, 0xa656

.align 4
BikeShop_MapConnections:
    .hword 8485
    .byte 18, 7
    .hword 8485
    .byte 18, 7

.align 4
BikeShop_MapName:
    .string "BIKE SHOP$"

# scripts/2174_BikeShop.s

.align 4

BikeShop_MapInitCode:
    ldr r0, =zSkipMapExitMovement
    mov r1, #2
    strb r1, [r0]
    bx lr

.align 4
.ltorg

BikeShop_MapInitScript:
    end

BikeShop_Script1:
    lock
    faceplayer
    checkflag FLAG_RECEIVED_BIKE
    goto_if TRUE, BikeShop_Script1_Instructions
    checkflag FLAG_RECEIVED_VOUCHER
    goto_if TRUE, BikeShop_Script1_GotVoucher
    msgbox BikeShop_Script1_Text
    release
    end
BikeShop_Script1_GotVoucher:
    msgbox BikeShop_Script1_Text2
    message BikeShop_Script1_TextExch
    waitmessage
    playfanfare MUS_RG_OBTAIN_KEY_ITEM
    waitfanfare
    setflag FLAG_RECEIVED_BIKE
    additem 360
    call SyncProgressScript
BikeShop_Script1_Instructions:
    msgbox BikeShop_Script1_Text3
    release
    end

BikeShop_Script1_Text:
    .string "Welcome to our BIKE SHOP!\n"
    .string "For limited time only, you can get\l"
    .string "a gnarly BIKE for just {DOLLAR}1000000!\p"
    .string "Oh, we're terribly sorry.\n"
    .string "You cannot afford it.$"

BikeShop_Script1_Text2:
    .string "Welcome to our BIKE SHOP!\n"
    .string "Oh, is that a BIKE VOUCHER?\p"
    .string "You're in luck, that voucher was\n"
    .string "to expire in a few minutes!\p"
    .string "Well, here you go!\n"
    .string "A gnarly, rad BICYCLE!$"

BikeShop_Script1_TextExch:
    .string "You exchanged the BIKE VOUCHER\n"
    .string "for a shining new BICYCLE!$"

BikeShop_Script1_Text3:
    .string "Just remember...\n"
    .string "No refunds! Haha!\p"
    .string "If you need instructions on how to\n"
    .string "use your BIKE, check out the enclosed\l"
    .string "instruction book in the right room.$"

BikeShop_Script2:
    lock
    faceplayer
    msgbox BikeShop_Script2_Text
    release
    end

BikeShop_Script2_Text:
    .string "What do you mean? Riding on a BIKE?\n"
    .string "Why would anyone ever do that?\p"
    .string "You already have the RUNNING SHOES for\n"
    .string "faster movement. Use them!\p"
    .string "Our BIKES are meant to be decorative.\n"
    .string "Who would ever want to ride a BIKE?$"

BikeShop_Script3:
    lock
    msgbox BikeShop_Script3_Text
    release
    end

BikeShop_Script3_Text:
    .string "This is the BICYCLE's enclosed\n"
    .string "instruction book!\p"
    .string "{LQUOT}Glitchland's special designer BIKE,\n"
    .string "designed for staring at it!\p"
    .string "With this new design, you can admire\n"
    .string "our bike even more efficiently!{RQUOT}$"

