# fools2022 - autogenerated map file, please do not change!
# created from: pokeemerald/data/maps/x2275_GlitchlandMansion/map.json

.thumb
.include "include/constants.inc"
.org MAP_LOAD_BASE

.include "include/macros.inc"
.include "include/symbols.inc"
.include "include/map.inc"
.include "include/event.inc"
.include "include/save.inc"

GlitchlandMansion_MapHeader:
    .word GlitchlandMansion_MapLayout
    .word GlitchlandMansion_MapEvts
    .word NULL
    .word NULL
    .hword MUS_RG_SEVII_CAVE
    .hword 0
    .byte 0
    .byte 0
    .byte WEATHER_NONE
    .byte 0
    .hword 0
    map_header_flags allow_cycling=1, allow_escaping=1, allow_running=1, show_map_name=1
    .byte 0
    # additional data specific to fools2022 maps
    .word GlitchlandMansion_MapInitCode+1
    .word GlitchlandMansion_MapConnections
    .word GlitchlandMansion_MapInitScript
    .word GlitchlandMansion_MapName
    .word 0x1718

GlitchlandMansion_MapLayout:
    .word 22
    .word 16
    .word GlitchlandMansion_MapBorder
    .word GlitchlandMansion_MapData
    .word gTileset_Building
    .word gTileset_InsideShip

.align 4
GlitchlandMansion_MapObjectEvents:
    object_event 1, OBJ_EVENT_GFX_SCOTT, 0, 17, 3, 3, MOVEMENT_TYPE_FACE_DOWN, 0, 0, TRAINER_TYPE_NONE, 0, GlitchlandMansion_Script1, FLAG_MANSION_PICKING1
    object_event 2, OBJ_EVENT_GFX_SCOTT, 0, 18, 3, 3, MOVEMENT_TYPE_NONE, 0, 0, TRAINER_TYPE_NONE, 0, GlitchlandMansion_Retry, FLAG_MANSION_PICKING3

.align 4
GlitchlandMansion_MapCoordEvents:
GlitchlandMansion_WarpCoordEvents:
    coord_event 11, 12, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT
    coord_event 12, 12, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT

.align 4
GlitchlandMansion_MapBGEvents:
    bg_event 7, 2, 0, BG_EVENT_PLAYER_FACING_ANY, GlitchlandMansion_Script2
    bg_event 12, 2, 0, BG_EVENT_PLAYER_FACING_ANY, GlitchlandMansion_Script3
    bg_event 13, 8, 0, BG_EVENT_PLAYER_FACING_ANY, GlitchlandMansion_Script4
    bg_event 17, 2, 0, BG_EVENT_PLAYER_FACING_ANY, GlitchlandMansion_Script5

.align 4
GlitchlandMansion_MapEvts:
    map_events 2, GlitchlandMansion_MapObjectEvents, 0, 0, 2, GlitchlandMansion_MapCoordEvents, 4, GlitchlandMansion_MapBGEvents

.align 4
GlitchlandMansion_MapBorder:
    .byte 0x01, 0x00, 0x01, 0x00, 0x01, 0x00, 0x01, 0x00

.align 4
GlitchlandMansion_MapData:
    .hword 0xb401, 0xa401, 0xc401, 0xa401, 0xb401, 0xc401, 0xa401, 0xc401, 0xa401, 0xa401, 0xc401, 0xb401, 0xa401, 0xc401, 0xb401, 0xc401, 0xc401, 0xb401, 0xc401, 0xa401, 0xc401, 0xa401
    .hword 0xb401, 0xb401, 0xc401, 0xb636, 0xa66c, 0xb66c, 0xa695, 0xb6af, 0xb696, 0xc66c, 0xc66c, 0xc695, 0xb6af, 0xc696, 0xc66c, 0xb66c, 0xc695, 0xc663, 0xb696, 0xb637, 0xc401, 0xa401
    .hword 0xb401, 0xa401, 0xb401, 0xa63e, 0xa674, 0xa674, 0xc69d, 0xb6b7, 0xc69e, 0xa674, 0xc674, 0xc69d, 0xc6b7, 0xb69e, 0xc674, 0xb674, 0xc69d, 0xc697, 0xb69e, 0xa63f, 0xc401, 0xc401
    .hword 0xb401, 0xa401, 0xc401, 0xc63e, 0x323a, 0x323b, 0x323b, 0x323b, 0x323b, 0x323b, 0x323b, 0x323b, 0x323b, 0x323b, 0x323b, 0x323b, 0x323b, 0x323b, 0x323b, 0xa63f, 0xb401, 0xa401
    .hword 0xb401, 0xc401, 0xc401, 0xc63e, 0x323d, 0x3238, 0x3238, 0x3238, 0x3238, 0x3238, 0x3238, 0x3238, 0x3238, 0x3238, 0x3238, 0x3238, 0x3238, 0x3238, 0x3238, 0xa63f, 0xc401, 0xc401
    .hword 0xa401, 0xb401, 0xc401, 0xc63e, 0x323d, 0xc660, 0xb656, 0xa657, 0x3238, 0x3238, 0xb63f, 0xc401, 0xc401, 0xb401, 0xb401, 0xc401, 0xc401, 0xb401, 0xc401, 0xa401, 0xc401, 0xb401
    .hword 0xa401, 0xa401, 0xb401, 0xb63e, 0x323d, 0xa660, 0xc65e, 0xc65f, 0x3238, 0x3238, 0xb66c, 0xc66c, 0xb66c, 0xc66c, 0xa637, 0xc401, 0xa401, 0xa401, 0xa401, 0xb401, 0xb401, 0xc401
    .hword 0xa401, 0xa401, 0xb401, 0xc63e, 0x323d, 0x3238, 0x3238, 0x3238, 0x3238, 0x3238, 0xa674, 0xb674, 0xa674, 0xb674, 0xb63f, 0xb401, 0xa401, 0xa401, 0xc401, 0xb401, 0xc401, 0xc401
    .hword 0xa401, 0xa401, 0xa401, 0xa63e, 0x323d, 0xb660, 0xc656, 0xa657, 0x3238, 0x3238, 0x323b, 0xc667, 0x323b, 0xc635, 0xb63f, 0xa401, 0xc401, 0xb401, 0xb401, 0xb401, 0xb401, 0xc401
    .hword 0xc401, 0xc401, 0xc401, 0xb63e, 0x323d, 0xb660, 0xc65e, 0xc65f, 0x3238, 0x3238, 0x3238, 0x3238, 0x3238, 0x3238, 0xc63f, 0xa401, 0xc401, 0xb401, 0xa401, 0xc401, 0xb401, 0xb401
    .hword 0xb401, 0xa401, 0xc401, 0xc63e, 0x323d, 0x3238, 0x3238, 0x3238, 0x3238, 0x3238, 0x3238, 0x3238, 0x3238, 0x3238, 0xc63f, 0xa401, 0xa401, 0xc401, 0xc401, 0xb401, 0xb401, 0xa401
    .hword 0xa401, 0xb401, 0xa401, 0xb63e, 0xc6ab, 0x3238, 0x3238, 0x3238, 0x3238, 0x3238, 0x3238, 0x3238, 0x3238, 0x3238, 0xa63f, 0xc401, 0xb401, 0xc401, 0xc401, 0xc401, 0xc401, 0xc401
    .hword 0xb401, 0xc401, 0xb401, 0xc63e, 0x323d, 0x3238, 0x3238, 0xa6aa, 0xc6ab, 0x3238, 0x3238, 0x3006, 0x3007, 0x3238, 0xb63f, 0xc401, 0xb401, 0xa401, 0xc401, 0xc401, 0xc401, 0xc401
    .hword 0xc401, 0xa401, 0xa401, 0xc401, 0xa401, 0xa401, 0xb401, 0xb401, 0xb401, 0xb401, 0xc401, 0xb401, 0xb401, 0xb401, 0xc401, 0xa401, 0xb401, 0xb401, 0xb401, 0xa401, 0xa401, 0xc401
    .hword 0xa401, 0xb401, 0xc401, 0xa401, 0xc401, 0xa401, 0xc401, 0xa401, 0xb401, 0xb401, 0xb401, 0xa401, 0xa401, 0xa401, 0xc401, 0xc401, 0xb401, 0xa401, 0xc401, 0xb401, 0xa401, 0xc401
    .hword 0xb401, 0xa401, 0xc401, 0xb401, 0xb401, 0xa401, 0xa401, 0xb401, 0xb401, 0xa401, 0xa401, 0xb401, 0xa401, 0xc401, 0xc401, 0xa401, 0xa401, 0xa401, 0xa401, 0xb401, 0xc401, 0xa401

.align 4
GlitchlandMansion_MapConnections:
    .hword 8762
    .byte 16, 10
    .hword 8762
    .byte 16, 10

.align 4
GlitchlandMansion_MapName:
    .string "WEST MANSION$"

# scripts/2275_GlitchlandMansion.s

.align 4

GlitchlandMansion_MapInitCode:
    ldr r0, =zSkipMapExitMovement
    mov r1, #2
    strb r1, [r0]
    bx lr

GlitchlandMansion_SetTargetMap:
    ldr r0, =zWarpTargetData
    ldr r1, =0x21102276
    str r1, [r0]
    ldr r0, =zWarpTargetDirection
    mov r1, #1
    strb r1, [r0]
    ldr r0, =zSkipMapExitMovement
    mov r1, #0
    strb r1, [r0]
    bx lr

.align 4
.ltorg

GlitchlandMansion_MapInitScript:
    end

GlitchlandMansion_Script1:
    lock
    faceplayer
    msgbox GlitchlandMansion_Script1_Text
    closemessage
    delay 22
    applymovement 1, GlitchlandMansion_Script1_Turn
    waitmovement 1
    delay 44
    msgbox GlitchlandMansion_Script1_Text2
    closemessage
    applymovement 1, GlitchlandMansion_Script1_GoIn
    waitmovement 1
    setflag FLAG_MANSION_PICKING1
    clearflag FLAG_MANSION_PICKING3
    removeobject 1
    removeobject 2
    playse SE_DOOR
    delay 44
    callnative GlitchlandMansion_SetTargetMap
    goto WarpScript
GlitchlandMansion_Script1_GoIn:
    walk_up
    step_end
GlitchlandMansion_Script1_Turn:
    face_up
    step_end

GlitchlandMansion_Script1_Text:
    .string "So, you ready? Let's see what's the\n"
    .string "deal about this lock.$"

GlitchlandMansion_Script1_Text2:
    .string "I'm going to use this wiper insert as\n"
    .string "a turning tool, and a medium hook\l"
    .string "in eighteen thousands.\p"
    .string "Click out of one...\n"
    .string "Nothing on two...\p"
    .string "... ... ... ... ... ...\n"
    .string "... ... ... ... ... ...\p"
    .string "Aaaand we got this open.\n"
    .string "I'll meet you inside!$"

GlitchlandMansion_Script2:
    lock
    msgbox GlitchlandMansion_Script2_Text
    release
    end

GlitchlandMansion_Script2_Text:
    .string "Door broke.\n"
    .string "It's impossible to go through.$"

GlitchlandMansion_Script3:
    lock
    msgbox GlitchlandMansion_Script3_Text
    release
    end

GlitchlandMansion_Script3_Text:
    .string "A broken door. The hole is too small\n"
    .string "to fit in.$"

GlitchlandMansion_Script4:
    lock
    msgbox GlitchlandMansion_Script4_Text
    release
    end

GlitchlandMansion_Script4_Text:
    .string "Inside the trash can... there's some\n"
    .string "trash! Unbelievable!$"

GlitchlandMansion_Script5:
    lock
    msgbox GlitchlandMansion_Script5_Text
    checkflag FLAG_CHECKOUT_DOOR
    goto_if TRUE, GlitchlandMansion_Script5_End
    setflag FLAG_CHECKOUT_DOOR
    call SyncProgressScript
GlitchlandMansion_Script5_End:
    release
    end

GlitchlandMansion_Script5_Text:
    .string "The door is locked. Looks like it's\n"
    .string "a standard pin tumbler lock design.$"

GlitchlandMansion_Retry:
    lock
    msgbox GlitchlandMansion_Retry_Text
    delay 32
    callnative GlitchlandMansion_SetTargetMap
    goto WARP_SCRIPT

GlitchlandMansion_Retry_Text:
    .string "You want to go inside the MANSION?\n"
    .string "I will work my magic.$"

