# fools2022 - autogenerated map file, please do not change!
# created from: pokeemerald/data/maps/x2536_FunVerCabinFrontyard/map.json

.thumb
.include "include/constants.inc"
.org MAP_LOAD_BASE

.include "include/macros.inc"
.include "include/symbols.inc"
.include "include/map.inc"
.include "include/event.inc"
.include "include/save.inc"

FunVerCabinFrontyard_MapHeader:
    .word FunVerCabinFrontyard_MapLayout
    .word FunVerCabinFrontyard_MapEvts
    .word NULL
    .word NULL
    .hword 0xffff
    .hword 0
    .byte 0
    .byte 0
    .byte WEATHER_NONE
    .byte 0
    .hword 0
    map_header_flags allow_cycling=1, allow_escaping=1, allow_running=1, show_map_name=1
    .byte 0
    # additional data specific to fools2022 maps
    .word FunVerCabinFrontyard_MapInitCode+1
    .word FunVerCabinFrontyard_MapConnections
    .word FunVerCabinFrontyard_MapInitScript
    .word FunVerCabinFrontyard_MapName
    .word 0x2819

FunVerCabinFrontyard_MapLayout:
    .word 16
    .word 18
    .word FunVerCabinFrontyard_MapBorder
    .word FunVerCabinFrontyard_MapData
    .word gTileset_General
    .word gTileset_PokemonSchool

.align 4
FunVerCabinFrontyard_MapObjectEvents:
    object_event 1, OBJ_EVENT_GFX_BRANDON, 0, 14, 15, 3, MOVEMENT_TYPE_FACE_UP, 0, 0, TRAINER_TYPE_NONE, 0, CabinFrontyard_WTF, 0

.align 4
FunVerCabinFrontyard_MapCoordEvents:
FunVerCabinFrontyard_WarpCoordEvents:
    coord_event 2, 7, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT
    coord_event 3, 7, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT
    coord_event 4, 7, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT

.align 4
FunVerCabinFrontyard_MapBGEvents:
    bg_event 14, 14, 0, BG_EVENT_PLAYER_FACING_ANY, CabinFrontyard_Map
    bg_event 10, 12, 0, BG_EVENT_PLAYER_FACING_ANY, CabinFrontyard_Script1

.align 4
FunVerCabinFrontyard_MapEvts:
    map_events 1, FunVerCabinFrontyard_MapObjectEvents, 0, 0, 3, FunVerCabinFrontyard_MapCoordEvents, 2, FunVerCabinFrontyard_MapBGEvents

.align 4
FunVerCabinFrontyard_MapBorder:
    .byte 0xd4, 0x01, 0xd5, 0x01, 0xdc, 0x01, 0xdd, 0x01

.align 4
FunVerCabinFrontyard_MapData:
    .hword 0xa5d4, 0xc5d5, 0x31d8, 0x31da, 0xa5d4, 0xc5d5, 0xa5d4, 0xa5d5, 0xa5d4, 0xa5d5, 0xa5d4, 0xa5d5, 0xb5d4, 0xa5d5, 0xb5d4, 0xa5d5
    .hword 0xb5dc, 0xa5dd, 0x31d8, 0x31da, 0xa5dc, 0xa5dd, 0xa5dc, 0xb5dd, 0xc5dc, 0xa5dd, 0xc5dc, 0xa5dd, 0xc5dc, 0xb5dd, 0xb5dc, 0xa5dd
    .hword 0xc5d4, 0xa5d5, 0x31d8, 0x31da, 0xb5d4, 0xc5d5, 0xc5d4, 0xc5d5, 0xa5d4, 0xc5d5, 0xc5d4, 0xc5d5, 0xc5d4, 0xb5d5, 0xb5d4, 0xb5d5
    .hword 0xb5dc, 0xa5dd, 0x31d8, 0x31da, 0xa5dc, 0xb5dd, 0xa5dc, 0xc5dd, 0xc5dc, 0xa5dd, 0xb5dc, 0xc5dd, 0xa5dc, 0xa5dd, 0xc5dc, 0xc5dd
    .hword 0xa5d4, 0xc5d5, 0x31d8, 0x31da, 0xb5d4, 0xa5d5, 0xb5d4, 0xa5d5, 0xc5d4, 0xb5d5, 0xc5d4, 0xb5d5, 0xc5d4, 0xa5d5, 0xb5d4, 0xc5d5
    .hword 0xc5dc, 0xa5dd, 0x31d8, 0x31da, 0xa5dc, 0xa5dd, 0xc5dc, 0xb5dd, 0xc5dc, 0xc5dd, 0xc5dc, 0xb5dd, 0xb5dc, 0xb5dd, 0xc5dc, 0xc5dd
    .hword 0xc5d4, 0xa5d5, 0x31d8, 0x31da, 0xc5d4, 0xc5d5, 0xc5d4, 0xc5d5, 0xb5d4, 0xc5d5, 0xa5d4, 0xc5d5, 0xa5d4, 0xa5d5, 0xa5d4, 0xc5d5
    .hword 0xb5dc, 0xb5dd, 0x31d8, 0x31da, 0xc5e4, 0xa5e5, 0xa5e4, 0xb5e5, 0xb5e4, 0xc5e5, 0xc5e4, 0xb5e5, 0xb5dc, 0xa5dd, 0xc5dc, 0xb5dd
    .hword 0xc5d4, 0xb5d5, 0x31d8, 0x31da, 0xc549, 0xb549, 0xc549, 0xa549, 0xa549, 0xc549, 0xa549, 0xa549, 0xb5d4, 0xa5d5, 0xa5d4, 0xa5d5
    .hword 0xa5dc, 0xc5dd, 0x31d8, 0x31da, 0x3001, 0x3001, 0x3001, 0x3001, 0x3001, 0x3001, 0x3001, 0x3001, 0xa5dc, 0xa5dd, 0xc5dc, 0xc5dd
    .hword 0xa5d4, 0xa5d5, 0x31d8, 0x31d9, 0x31d1, 0x31d1, 0x31d1, 0x31d1, 0x31d1, 0x31d2, 0x3004, 0x3001, 0xa5d4, 0xa5d5, 0xb5d4, 0xc5d5
    .hword 0xb5dc, 0xb5dd, 0x31e0, 0x31e1, 0x31e1, 0x31e1, 0x31e1, 0x31e1, 0x31d9, 0x31da, 0x3001, 0x3004, 0xb5dc, 0xa5dd, 0xa5dc, 0xb5dd
    .hword 0xc5d4, 0xb5d5, 0x3001, 0x3001, 0x3004, 0x3001, 0x3004, 0x3001, 0x31d8, 0x31da, 0xa4e0, 0x3001, 0xa5d4, 0xa5d5, 0xa5d4, 0xb5d5
    .hword 0xa5dc, 0xb5dd, 0x31ce, 0x31cf, 0x31ce, 0x31cf, 0x3001, 0x3001, 0x31d8, 0x31da, 0x3001, 0x3001, 0xb5e4, 0xc5e5, 0xc5e4, 0xb5e5
    .hword 0xb5d4, 0xb5d5, 0xb5d4, 0xa5d5, 0xb5d4, 0xb5d5, 0x3001, 0x3001, 0x31d8, 0x31da, 0x3001, 0x3004, 0x3001, 0x3001, 0xb41b, 0x3001
    .hword 0xc5dc, 0xb5dd, 0xa5dc, 0xb5dd, 0xa5dc, 0xc5dd, 0x31ce, 0x31cf, 0x31d8, 0x31d9, 0x31d1, 0x31d1, 0x31d1, 0x31d1, 0x31d2, 0x3001
    .hword 0xb5d4, 0xc5d5, 0xa5d4, 0xc5d5, 0xc5d4, 0xa5d5, 0xa5d4, 0xc5d5, 0x31e0, 0x31e1, 0x31e1, 0x31e1, 0x31e1, 0x31e1, 0x31e2, 0x3001
    .hword 0xb5dc, 0xc5dd, 0xc5dc, 0xb5dd, 0xa5dc, 0xb5dd, 0xa5dc, 0xc5dd, 0x31ce, 0x31cf, 0x31ce, 0x31cf, 0x31ce, 0x31cf, 0x31ce, 0x31cf

.align 4
FunVerCabinFrontyard_MapConnections:
    .hword 0x2435
    .byte 11, 144
    .hword 0x2435
    .byte 11, 144
    .hword 0x2435
    .byte 11, 144

.align 4
FunVerCabinFrontyard_MapName:
    .string "CABIN FRONTYARD$"

# scripts/2536_FunVerCabinFrontyard.s

.align 4

FunVerCabinFrontyard_MapInitCode:
    bx lr

FunVerCabinFrontyard_GBACrashSound:
    ldr r0, =0x4000200
    mov r1, #1
    strh r1, [r0]
    bx lr

.align 4
.ltorg

FunVerCabinFrontyard_MapInitScript:
    end

CabinFrontyard_Script1:
    lock
    msgbox CabinFrontyard_Script1_Text
    release
    end

CabinFrontyard_Script1_Text:
    .string "It's a rock. There's a half-burned\n"
    .string "photograph underside it.\p"
    .string "Just two people you do not seem to\n"
    .string "recognize.$"

CabinFrontyard_Map:
    lock
    msgbox CabinFrontyard_Map_Text
    release
    end

CabinFrontyard_Map_Text:
    .string "A detailed map of Glitchland is\n"
    .string "crudely drawn here.\p"
    .string "But some things are off. Many locations\n"
    .string "are in different places, or they don't\l"
    .string "appear on the map at all.\p"
    .string "Whoever drew this map must know a lot\n"
    .string "about this world and its origins.$"

CabinFrontyard_WTF:
    lock
    faceplayer
    message CabinFrontyard_WTF_Text1
    waitmessage
    delay 60
    message CabinFrontyard_WTF_Text2
    waitmessage
    delay 60
    playbgm MUS_FALLARBOR, 0
    delay 60
    message CabinFrontyard_WTF_Text3
    waitmessage
    delay 60
    message CabinFrontyard_WTF_Text4
    waitmessage
    delay 60
    callnative FunVerCabinFrontyard_GBACrashSound
    delay 60
    message CabinFrontyard_WTF_Text5
    waitmessage
    delay 60
    message CabinFrontyard_WTF_Text6
    waitmessage
    delay 60
    message CabinFrontyard_WTF_Text7
    waitmessage
    delay 60
    callnative 0x08000000-1

CabinFrontyard_WTF_Text1:
    .string "Oh, hi...\n"
    .string "I'm kinda shy...$"

CabinFrontyard_WTF_Text2:
    .string "It's so quiet here.\n"
    .string "Maybe I'll turn on some music...$"

CabinFrontyard_WTF_Text3:
    .string "See?\n"
    .string "It's much better...$"

CabinFrontyard_WTF_Text4:
    .string "Now, let me quickly change just one\n"
    .string "more thing...$"

CabinFrontyard_WTF_Text5:
    .string "Oh well...\n"
    .string "That didn't work...$"

CabinFrontyard_WTF_Text6:
    .string "Why do I always ruin everything?$"

CabinFrontyard_WTF_Text7:
    .string "Forget we had this conversation.$"

