# fools2022 - autogenerated map file, please do not change!
# created from: pokeemerald/data/maps/x2B7C_WesternEncampment/map.json

.thumb
.include "include/constants.inc"
.org MAP_LOAD_BASE

.include "include/macros.inc"
.include "include/symbols.inc"
.include "include/map.inc"
.include "include/event.inc"
.include "include/save.inc"

WesternEncampment_MapHeader:
    .word WesternEncampment_MapLayout
    .word WesternEncampment_MapEvts
    .word NULL
    .word NULL
    .hword MUS_RG_FUCHSIA
    .hword 0
    .byte 0
    .byte 0
    .byte WEATHER_NONE
    .byte 0
    .hword 0
    map_header_flags allow_cycling=1, allow_escaping=1, allow_running=1, show_map_name=1
    .byte 0
    # additional data specific to fools2022 maps
    .word WesternEncampment_MapInitCode+1
    .word WesternEncampment_MapConnections
    .word WesternEncampment_MapInitScript
    .word WesternEncampment_MapName
    .word 0x0700

WesternEncampment_MapLayout:
    .word 10
    .word 9
    .word WesternEncampment_MapBorder
    .word WesternEncampment_MapData
    .word gTileset_Building
    .word gTileset_GenericBuilding

.align 4
WesternEncampment_MapObjectEvents:
    object_event 1, OBJ_EVENT_GFX_MANIAC, 0, 5, 4, 3, MOVEMENT_TYPE_FACE_LEFT, 0, 0, TRAINER_TYPE_NONE, 0, WesternCamp_Interior_Script1, 0

.align 4
WesternEncampment_MapCoordEvents:
WesternEncampment_WarpCoordEvents:
    coord_event 3, 8, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT
    coord_event 4, 8, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT

.align 4
WesternEncampment_MapBGEvents:

.align 4
WesternEncampment_MapEvts:
    map_events 1, WesternEncampment_MapObjectEvents, 0, 0, 2, WesternEncampment_MapCoordEvents, 0, WesternEncampment_MapBGEvents

.align 4
WesternEncampment_MapBorder:
    .byte 0x01, 0x02, 0x01, 0x02, 0x01, 0x02, 0x01, 0x02

.align 4
WesternEncampment_MapData:
    .hword 0xa686, 0xa687, 0xc679, 0xa67a, 0xb605, 0xa607, 0xc605, 0xc605, 0xa605, 0xc605
    .hword 0xb68e, 0xa68f, 0xa681, 0xa682, 0xb60d, 0xa60f, 0xc60d, 0xc60d, 0xc690, 0xc690
    .hword 0x3296, 0x3297, 0x3289, 0x328a, 0x3224, 0x3224, 0x3224, 0x3224, 0xa698, 0xb698
    .hword 0x3239, 0x3235, 0x3236, 0x3236, 0x3236, 0x3236, 0x3236, 0x3237, 0x3223, 0x3223
    .hword 0x3239, 0x323d, 0x32e1, 0xb648, 0xa649, 0x32e2, 0x323e, 0x323f, 0x3223, 0x3223
    .hword 0x3239, 0x323d, 0x32e1, 0xb650, 0xc651, 0x32e2, 0x323e, 0x323f, 0x3223, 0x3223
    .hword 0x3239, 0x3245, 0x3246, 0x3246, 0x3246, 0x3246, 0x3246, 0x3247, 0x3223, 0x3223
    .hword 0x3239, 0x3223, 0x3223, 0x3223, 0x3223, 0x3223, 0x3223, 0x3223, 0x3223, 0x3222
    .hword 0x3239, 0x3223, 0x3223, 0x0208, 0x0209, 0x3223, 0x3223, 0x3223, 0x3223, 0xa62a

.align 4
WesternEncampment_MapConnections:
    .hword 11049
    .byte 11, 3
    .hword 11049
    .byte 11, 3

.align 4
WesternEncampment_MapName:
    .string "WESTERN CAMP$"

# scripts/2B7C_WesternEncampment.s

.align 4

WesternEncampment_MapInitCode:
    ldr r0, =zSkipMapExitMovement
    mov r1, #2
    strb r1, [r0]
    bx lr

.align 4
.ltorg

WesternEncampment_MapInitScript:
    end

WesternCamp_Interior_Script1:
    lock
    faceplayer
    msgbox WesternCamp_Interior_Script1_Text, MSGBOX_YESNO
    compare VAR_RESULT, NO
    goto_if_eq WesternCamp_Interior_Script1_No
    goto WesternCamp_Interior_Script1_GiveBalls1

WesternCamp_Interior_Script1_No:
    msgbox WesternCamp_Interior_Script1_Text4
    release
    end

WesternCamp_Interior_Script1_BallGiven:
    message WesternCamp_Interior_Script1_Text2
    waitmessage
    playfanfare MUS_RG_OBTAIN_KEY_ITEM
    waitfanfare
    removeitem 4
    call WesternCamp_Interior_Script1_CountBalls
    buffernumberstring STR_VAR_1, VAR_TEMP_2
    msgbox WesternCamp_Interior_Script1_Text3
    call SyncProgressScript
    release
    end

WesternCamp_Interior_Script1_BallNotGiven:
    msgbox WesternCamp_Interior_Script1_Text1
    release
    end

WesternCamp_Interior_Script1_GiveBalls1:
    checkflag FLAG_RECEIVED_BALL1
    goto_if FALSE, WesternCamp_Interior_Script1_GiveBalls2
    checkflag FLAG_GIVEN_BALL1
    goto_if TRUE, WesternCamp_Interior_Script1_GiveBalls2
    setflag FLAG_GIVEN_BALL1
    goto WesternCamp_Interior_Script1_BallGiven
WesternCamp_Interior_Script1_GiveBalls2:
    checkflag FLAG_RECEIVED_BALL2
    goto_if FALSE, WesternCamp_Interior_Script1_GiveBalls3
    checkflag FLAG_GIVEN_BALL2
    goto_if TRUE, WesternCamp_Interior_Script1_GiveBalls3
    setflag FLAG_GIVEN_BALL2
    goto WesternCamp_Interior_Script1_BallGiven
WesternCamp_Interior_Script1_GiveBalls3:
    checkflag FLAG_RECEIVED_BALL3
    goto_if FALSE, WesternCamp_Interior_Script1_GiveBalls4
    checkflag FLAG_GIVEN_BALL3
    goto_if TRUE, WesternCamp_Interior_Script1_GiveBalls4
    setflag FLAG_GIVEN_BALL3
    goto WesternCamp_Interior_Script1_BallGiven
WesternCamp_Interior_Script1_GiveBalls4:
    checkflag FLAG_RECEIVED_BALL4
    goto_if FALSE, WesternCamp_Interior_Script1_GiveBalls5
    checkflag FLAG_GIVEN_BALL4
    goto_if TRUE, WesternCamp_Interior_Script1_GiveBalls5
    setflag FLAG_GIVEN_BALL4
    goto WesternCamp_Interior_Script1_BallGiven
WesternCamp_Interior_Script1_GiveBalls5:
    checkflag FLAG_RECEIVED_BALL5
    goto_if FALSE, WesternCamp_Interior_Script1_GiveBalls6
    checkflag FLAG_GIVEN_BALL5
    goto_if TRUE, WesternCamp_Interior_Script1_GiveBalls6
    setflag FLAG_GIVEN_BALL5
    goto WesternCamp_Interior_Script1_BallGiven
WesternCamp_Interior_Script1_GiveBalls6:
    checkflag FLAG_RECEIVED_BALL6
    goto_if FALSE, WesternCamp_Interior_Script1_GiveBalls7
    checkflag FLAG_GIVEN_BALL6
    goto_if TRUE, WesternCamp_Interior_Script1_GiveBalls7
    setflag FLAG_GIVEN_BALL6
    goto WesternCamp_Interior_Script1_BallGiven
WesternCamp_Interior_Script1_GiveBalls7:
    checkflag FLAG_RECEIVED_BALL7
    goto_if FALSE, WesternCamp_Interior_Script1_GiveBalls8
    checkflag FLAG_GIVEN_BALL7
    goto_if TRUE, WesternCamp_Interior_Script1_GiveBalls8
    setflag FLAG_GIVEN_BALL7
    goto WesternCamp_Interior_Script1_BallGiven
WesternCamp_Interior_Script1_GiveBalls8:
    checkflag FLAG_RECEIVED_BALL8
    goto_if FALSE, WesternCamp_Interior_Script1_GiveBalls9
    checkflag FLAG_GIVEN_BALL8
    goto_if TRUE, WesternCamp_Interior_Script1_GiveBalls9
    setflag FLAG_GIVEN_BALL8
    goto WesternCamp_Interior_Script1_BallGiven
WesternCamp_Interior_Script1_GiveBalls9:
    checkflag FLAG_RECEIVED_BALL9
    goto_if FALSE, WesternCamp_Interior_Script1_BallNotGiven
    checkflag FLAG_GIVEN_BALL9
    goto_if TRUE, WesternCamp_Interior_Script1_BallNotGiven
    setflag FLAG_GIVEN_BALL9
    goto WesternCamp_Interior_Script1_BallGiven

WesternCamp_Interior_Script1_CountBalls:
    setvar VAR_TEMP_2, 0
    checkflag FLAG_GIVEN_BALL1
    call_if TRUE, WesternCamp_Interior_Script1_CountBalls_Incr
    checkflag FLAG_GIVEN_BALL2
    call_if TRUE, WesternCamp_Interior_Script1_CountBalls_Incr
    checkflag FLAG_GIVEN_BALL3
    call_if TRUE, WesternCamp_Interior_Script1_CountBalls_Incr
    checkflag FLAG_GIVEN_BALL4
    call_if TRUE, WesternCamp_Interior_Script1_CountBalls_Incr
    checkflag FLAG_GIVEN_BALL5
    call_if TRUE, WesternCamp_Interior_Script1_CountBalls_Incr
    checkflag FLAG_GIVEN_BALL6
    call_if TRUE, WesternCamp_Interior_Script1_CountBalls_Incr
    checkflag FLAG_GIVEN_BALL7
    call_if TRUE, WesternCamp_Interior_Script1_CountBalls_Incr
    checkflag FLAG_GIVEN_BALL8
    call_if TRUE, WesternCamp_Interior_Script1_CountBalls_Incr
    checkflag FLAG_GIVEN_BALL9
    call_if TRUE, WesternCamp_Interior_Script1_CountBalls_Incr
    return

WesternCamp_Interior_Script1_CountBalls_Incr:
    addvar VAR_TEMP_2, 1
    return

WesternCamp_Interior_Script1_Text:
    .string "Hey, you know what I really like?\n"
    .string "Balls! I like POK{EACUTE} BALLS of all kind!\p"
    .string "You can pretty much say that I'm\n"
    .string "a sucker for balls, haha!\p"
    .string "So, do you happen to have any BALLS?\n"
    .string "If so, do you wish to give them to me?$"

WesternCamp_Interior_Script1_Text1:
    .string "Sir, I'm afraid you don't have any\n"
    .string "BALLS to show me.\p"
    .string "Once you get some BALLS, please let\n"
    .string "me know - I'll check them out!$"

WesternCamp_Interior_Script1_Text2:
    .string "Hmm, yes! That's a POK{EACUTE} BALL!\n"
    .string "And in great condition as well!$"

WesternCamp_Interior_Script1_Text3:
    .string "Oh yes... The taste...\n"
    .string "The smell... The texture...\p"
    .string "Thank you! So far, you've brought\n"
    .string "{STR_VAR_1} different BALLS to me.\p"
    .string "If you were to find any more BALLS,\n"
    .string "please bring them over!$"

WesternCamp_Interior_Script1_Text4:
    .string "Oh, that's disappointing. Let me\n"
    .string "know if you find any BALLS.$"
