# fools2022 - autogenerated map file, please do not change!
# created from: pokeemerald/data/maps/x2B7D_WesternEncampment/map.json

.thumb
.include "include/constants.inc"
.org MAP_LOAD_BASE

.include "include/macros.inc"
.include "include/symbols.inc"
.include "include/map.inc"
.include "include/event.inc"
.include "include/save.inc"

WesternEncampment_MapHeader:
    .word WesternEncampment_MapLayout
    .word WesternEncampment_MapEvts
    .word NULL
    .word NULL
    .hword MUS_RG_FUCHSIA
    .hword 0
    .byte 0
    .byte 0
    .byte WEATHER_NONE
    .byte 0
    .hword 0
    map_header_flags allow_cycling=1, allow_escaping=1, allow_running=1, show_map_name=1
    .byte 0
    # additional data specific to fools2022 maps
    .word WesternEncampment_MapInitCode+1
    .word WesternEncampment_MapConnections
    .word WesternEncampment_MapInitScript
    .word WesternEncampment_MapName
    .word 0x0700

WesternEncampment_MapLayout:
    .word 10
    .word 9
    .word WesternEncampment_MapBorder
    .word WesternEncampment_MapData
    .word gTileset_Building
    .word gTileset_GenericBuilding

.align 4
WesternEncampment_MapObjectEvents:
    object_event 1, OBJ_EVENT_GFX_SCOTT, 0, 2, 4, 3, MOVEMENT_TYPE_FACE_RIGHT, 0, 0, TRAINER_TYPE_NONE, 0, WesternCamp_Interior_Script1, 0

.align 4
WesternEncampment_MapCoordEvents:
WesternEncampment_WarpCoordEvents:
    coord_event 3, 8, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT
    coord_event 4, 8, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT

.align 4
WesternEncampment_MapBGEvents:

.align 4
WesternEncampment_MapEvts:
    map_events 1, WesternEncampment_MapObjectEvents, 0, 0, 2, WesternEncampment_MapCoordEvents, 0, WesternEncampment_MapBGEvents

.align 4
WesternEncampment_MapBorder:
    .byte 0x01, 0x02, 0x01, 0x02, 0x01, 0x02, 0x01, 0x02

.align 4
WesternEncampment_MapData:
    .hword 0xa686, 0xa687, 0xa679, 0xc67a, 0xc605, 0xa607, 0xa605, 0xc605, 0xb605, 0xc605
    .hword 0xa68e, 0xb68f, 0xa681, 0xc682, 0xc60d, 0xc60f, 0xc60d, 0xa60d, 0xb690, 0xb690
    .hword 0x3296, 0x3297, 0x3289, 0x328a, 0x3224, 0x3224, 0x3224, 0x3224, 0xc698, 0xa698
    .hword 0x3239, 0x3235, 0x3236, 0x3236, 0x3236, 0x3236, 0x3236, 0x3237, 0x3223, 0x3223
    .hword 0x3239, 0x323d, 0x32e1, 0xc648, 0xb649, 0x32e2, 0x323e, 0x323f, 0x3223, 0x3223
    .hword 0x3239, 0x323d, 0x32e1, 0xc650, 0xa651, 0x32e2, 0x323e, 0x323f, 0x3223, 0x3223
    .hword 0x3239, 0x3245, 0x3246, 0x3246, 0x3246, 0x3246, 0x3246, 0x3247, 0x3223, 0x3223
    .hword 0x3239, 0x3223, 0x3223, 0x3223, 0x3223, 0x3223, 0x3223, 0x3223, 0x3223, 0x3222
    .hword 0x3239, 0x3223, 0x3223, 0x0208, 0x0209, 0x3223, 0x3223, 0x3223, 0x3223, 0xa62a

.align 4
WesternEncampment_MapConnections:
    .hword 11049
    .byte 21, 3
    .hword 11049
    .byte 21, 3

.align 4
WesternEncampment_MapName:
    .string "WESTERN CAMP$"

# scripts/2B7D_WesternEncampment.s

.align 4

WesternEncampment_MapInitCode:
    ldr r0, =zSkipMapExitMovement
    mov r1, #2
    strb r1, [r0]
    bx lr

.align 4
.ltorg

WesternEncampment_MapInitScript:
    end

WesternCamp_Interior_Script1:
    lock
    faceplayer
    checkflag FLAG_MANSION_GOT_SCALE
    goto_if TRUE, WesternCamp_Interior_Script1_PostPicking
    checkflag FLAG_CHECKOUT_DOOR
    goto_if FALSE, WesternCamp_Interior_Script1_HaventCheckedDoor
    checkflag FLAG_MANSION_PICKING1
    goto_if TRUE, WesternCamp_Interior_Script1_PrePicking
WesternCamp_Interior_Script1_PrePicking_Done:
    msgbox WesternCamp_Interior_Script1_Text2_Sub
    release
    end

WesternCamp_Interior_Script1_PostPicking:
    msgbox WesternCamp_Interior_Script1_Text3
    release
    end

WesternCamp_Interior_Script1_PrePicking:
    msgbox WesternCamp_Interior_Script1_Text2
    clearflag FLAG_MANSION_PICKING1
    call SyncProgressScript
    release
    end

WesternCamp_Interior_Script1_HaventCheckedDoor:
    msgbox WesternCamp_Interior_Script1_Text
    release
    end

WesternCamp_Interior_Script1_Text:
    .string "Hey. Exploring is fun, but my number\n"
    .string "one hobby is lockpicking.\p"
    .string "It's especially great if I get to\n"
    .string "combine both of those things together.\p"
    .string "Let me know if you find a good\n"
    .string "opportunity to practice my skills.\p"
    .string "Tell me the type of lock, and I'll\n"
    .string "immediately get to picking!$"

WesternCamp_Interior_Script1_Text2:
    .string "Hey. Exploring is fun, but my number\n"
    .string "one hobby is lockpicking.\p"
    .string "Oh, so this spooky abandoned mansion\n"
    .string "has a locked door?\l"
    .string "And it's a pin tumbler design?\p"
WesternCamp_Interior_Script1_Text2_Sub:
    .string "No need to tell me anything more. I'll\n"
    .string "meet you in the mansion.\p"
    .string "I should be able to take care of this\n"
    .string "lock pretty quickly.$"

WesternCamp_Interior_Script1_Text3:
    .string "Exploring that mansion was pretty fun.\n"
    .string "Also a great opportunity to practice my\l"
    .string "lockpicking skills. I give you my thanks.$"

