# fools2022 - autogenerated map file, please do not change!
# created from: pokeemerald/data/maps/x2B7E_ExplorerSindicate/map.json

.thumb
.include "include/constants.inc"
.org MAP_LOAD_BASE

.include "include/macros.inc"
.include "include/symbols.inc"
.include "include/map.inc"
.include "include/event.inc"
.include "include/save.inc"

ExplorerSindicate_MapHeader:
    .word ExplorerSindicate_MapLayout
    .word ExplorerSindicate_MapEvts
    .word NULL
    .word NULL
    .hword MUS_FALLARBOR
    .hword 0
    .byte 0
    .byte 0
    .byte WEATHER_NONE
    .byte 0
    .hword 0
    map_header_flags allow_cycling=1, allow_escaping=1, allow_running=1, show_map_name=1
    .byte 0
    # additional data specific to fools2022 maps
    .word ExplorerSindicate_MapInitCode+1
    .word ExplorerSindicate_MapConnections
    .word ExplorerSindicate_MapInitScript
    .word ExplorerSindicate_MapName
    .word 0x2819

ExplorerSindicate_MapLayout:
    .word 16
    .word 10
    .word ExplorerSindicate_MapBorder
    .word ExplorerSindicate_MapData
    .word gTileset_Building
    .word gTileset_Lab

.align 4
ExplorerSindicate_MapObjectEvents:
    object_event 1, OBJ_EVENT_GFX_BOY_3, 0, 2, 3, 3, MOVEMENT_TYPE_FACE_DOWN, 0, 0, TRAINER_TYPE_NONE, 0, ExplorerSindicate_Script1, 0
    object_event 2, OBJ_EVENT_GFX_FAT_MAN, 0, 8, 3, 3, MOVEMENT_TYPE_FACE_UP, 0, 0, TRAINER_TYPE_NONE, 0, ExplorerSindicate_Script2, 0
    object_event 3, OBJ_EVENT_GFX_SCIENTIST_1, 0, 13, 4, 3, MOVEMENT_TYPE_FACE_LEFT, 0, 0, TRAINER_TYPE_NONE, 0, ExplorerSindicate_Script3, 0
    object_event 4, OBJ_EVENT_GFX_LITTLE_BOY, 0, 9, 9, 3, MOVEMENT_TYPE_WANDER_LEFT_AND_RIGHT, 1, 0, TRAINER_TYPE_NONE, 0, ExplorerSindicate_Script4, 0

.align 4
ExplorerSindicate_MapCoordEvents:
ExplorerSindicate_WarpCoordEvents:
    coord_event 3, 9, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT
    coord_event 4, 9, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT

.align 4
ExplorerSindicate_MapBGEvents:
    bg_event 3, 1, 0, BG_EVENT_PLAYER_FACING_ANY, ExplorerSindicate_PC1
    bg_event 4, 1, 0, BG_EVENT_PLAYER_FACING_ANY, ExplorerSindicate_PC1
    bg_event 12, 1, 0, BG_EVENT_PLAYER_FACING_ANY, ExplorerSindicate_PC2
    bg_event 13, 1, 0, BG_EVENT_PLAYER_FACING_ANY, ExplorerSindicate_PC2
    bg_event 9, 6, 0, BG_EVENT_PLAYER_FACING_ANY, ExplorerSindicate_PC3
    bg_event 9, 7, 0, BG_EVENT_PLAYER_FACING_ANY, ExplorerSindicate_PC3
    bg_event 15, 2, 0, BG_EVENT_PLAYER_FACING_ANY, ExplorerSindicate_Pot
    bg_event 15, 9, 0, BG_EVENT_PLAYER_FACING_ANY, ExplorerSindicate_Pot

.align 4
ExplorerSindicate_MapEvts:
    map_events 4, ExplorerSindicate_MapObjectEvents, 0, 0, 2, ExplorerSindicate_MapCoordEvents, 8, ExplorerSindicate_MapBGEvents

.align 4
ExplorerSindicate_MapBorder:
    .byte 0x01, 0x00, 0x01, 0x00, 0x01, 0x00, 0x01, 0x00

.align 4
ExplorerSindicate_MapData:
    .hword 0xc65f, 0xc65f, 0xc65f, 0xa688, 0xa689, 0xc673, 0xb65f, 0xb65f, 0xb65f, 0xc65f, 0xc65f, 0xb65f, 0xc688, 0xb689, 0xb65f, 0xa65f
    .hword 0xa667, 0xa667, 0xc667, 0xc690, 0xa691, 0xa670, 0xc62c, 0xa62d, 0xa62c, 0xc62d, 0xb667, 0xb667, 0xa690, 0xa691, 0xc667, 0xa667
    .hword 0x326a, 0x327a, 0x327a, 0x3298, 0x3299, 0xa678, 0xc634, 0xb635, 0xc634, 0xa635, 0x326a, 0x327a, 0x3298, 0x3299, 0x327a, 0xb687
    .hword 0x3272, 0x3269, 0x3269, 0x3269, 0x3269, 0x3280, 0x327a, 0x327a, 0x327a, 0x327a, 0x3277, 0x3269, 0x3269, 0x3256, 0x3269, 0x3269
    .hword 0x3272, 0x3269, 0x3269, 0x3269, 0x3269, 0x3269, 0x3269, 0x3269, 0x3269, 0x3269, 0x3269, 0x3269, 0x3269, 0x3269, 0x3269, 0x3269
    .hword 0x3272, 0x3269, 0x3269, 0x3269, 0x3269, 0x3269, 0x3269, 0x3269, 0x3269, 0x3269, 0x3269, 0x3269, 0x3269, 0x3269, 0x3269, 0xc64a
    .hword 0x3272, 0x3269, 0x3269, 0x3269, 0x3269, 0x3269, 0x3269, 0x3269, 0x3269, 0xb650, 0xc62c, 0xc62d, 0xa62c, 0xa62d, 0xa62c, 0xb62d
    .hword 0x3272, 0x3269, 0x3269, 0x3269, 0x3269, 0x3269, 0x3269, 0x3269, 0x3269, 0xc658, 0xa634, 0xa635, 0xb634, 0xb635, 0xb634, 0xc635
    .hword 0x3272, 0x3269, 0x3269, 0x3269, 0x3269, 0x3269, 0x3269, 0x3269, 0x3269, 0x3269, 0x327a, 0x327a, 0x327a, 0x327a, 0x327a, 0x327a
    .hword 0x3272, 0x3269, 0x3269, 0x3206, 0x3207, 0x3269, 0x3269, 0x3269, 0x3269, 0x3269, 0x3269, 0x3269, 0x3269, 0x3269, 0x3269, 0xb65d

.align 4
ExplorerSindicate_MapConnections:
    .hword 11049
    .byte 9, 11
    .hword 11049
    .byte 9, 11

.align 4
ExplorerSindicate_MapName:
    .string "EXP.SINDICATE$"

# scripts/2B7E_ExplorerSindicate.s

.align 4

ExplorerSindicate_MapInitCode:
    ldr r0, =zSkipMapExitMovement
    mov r1, #2
    strb r1, [r0]
    bx lr

.align 4
.ltorg

ExplorerSindicate_MapInitScript:
    end

ExplorerSindicate_Script1:
    lock
    faceplayer
    msgbox ExplorerSindicate_Script1_Text
    release
    end

ExplorerSindicate_Script1_Text:
    .string "Welcome to the Glitchland Explorer\n"
    .string "Sindicate.\p"
    .string "Yes, we know.\n"
    .string "Our name is misspelled.$"

ExplorerSindicate_Script2:
    lock
    faceplayer
    msgbox ExplorerSindicate_Script2_Text
    release
    end

ExplorerSindicate_Script2_Text:
    .string "Reading books is a surefire way to\n"
    .string "boost your knowledge!\p"
    .string "Did you know that Lost Woods has four\n"
    .string "distinct secret areas, accessible\l"
    .string "by walking in different patterns?\p"
    .string "I read that going east, north, then\n"
    .string "south twice reveals one of them.$$"

ExplorerSindicate_Script3:
    lock
    faceplayer
    checkflag FLAG_TOOK_FOSSILS
    goto_if TRUE, ExplorerSindicate_Script3_Done
    checkflag FLAG_UNDERGROUND_CAVE_HELIX
    goto_if FALSE, ExplorerSindicate_Script3_NoFossils
    checkflag FLAG_ALTERING_CAVE_DOME
    goto_if FALSE, ExplorerSindicate_Script3_NoFossils
    checkflag FLAG_TINY_CAVERN_AMBER
    goto_if FALSE, ExplorerSindicate_Script3_NoFossils
    msgbox ExplorerSindicate_Script3_Text2
    setflag FLAG_TOOK_FOSSILS
    call SyncProgressScript
    release
    end
ExplorerSindicate_Script3_NoFossils:
    msgbox ExplorerSindicate_Script3_Text
    release
    end
ExplorerSindicate_Script3_Done:
    msgbox ExplorerSindicate_Script3_Text2
    release
    end

ExplorerSindicate_Script3_Text:
    .string "Hiya! I'm an important doctor!\n"
    .string "My specialty is fossil research.\p"
    .string "I'm looking for all of them - our\n"
    .string "Lord Helix, the Dome Fossil, and the\l"
    .string "less popular Old Amber.\p"
    .string "If you happen to collect them all,\n"
    .string "please give them to me for analysis.$"

ExplorerSindicate_Script3_Text2:
    .string "Hiya! I'm an important doctor!\n"
    .string "My specialty is fossil research.\p"
    .string "Wow, you got all the fossils?\n"
    .string "Fantastic! My research can proceed!\l"
    .string "Thank you for all of your hard work.$"

ExplorerSindicate_Script4:
    lock
    faceplayer
    msgbox ExplorerSindicate_Script4_Text
    release
    end

ExplorerSindicate_Script4_Text:
    .string "You know about Altering Cave?\n"
    .string "Just like the name suggests, it cycles\l"
    .string "between many different appearances\l"
    .string "every hour or so.$"

ExplorerSindicate_PC1:
    lock
    msgbox ExplorerSindicate_PC1_Text
    release
    end

ExplorerSindicate_PC1_Text:
    .string "It's an science PC. It doesn't\n"
    .string "use WINDOWS because of VIRUS.$"

ExplorerSindicate_PC2:
    lock
    msgbox ExplorerSindicate_PC2_Text
    release
    end

ExplorerSindicate_PC2_Text:
    .string "Wow, you can click here for a free\n"
    .string "iPad? What a great deal!$"

ExplorerSindicate_PC3:
    lock
    msgbox ExplorerSindicate_PC3_Text
    release
    end

ExplorerSindicate_PC3_Text:
    .string "Oops, this system crashed!\p"
    .string "The scientists here lost their data,\n"
    .string "but they had an antivirus.$"

ExplorerSindicate_Pot:
    lock
    msgbox ExplorerSindicate_Pot_Text
    release
    end

ExplorerSindicate_Pot_Text:
    .string "Look! It's an olden-tortoise\n"
    .string "water-pot, which is belonded to you.$"
