# fools2022 - autogenerated map file, please do not change!
# created from: pokeemerald/data/maps/x2D27_WesternEdge/map.json

.thumb
.include "include/constants.inc"
.org MAP_LOAD_BASE

.include "include/macros.inc"
.include "include/symbols.inc"
.include "include/map.inc"
.include "include/event.inc"
.include "include/save.inc"

WesternEdge_MapHeader:
    .word WesternEdge_MapLayout
    .word WesternEdge_MapEvts
    .word NULL
    .word NULL
    .hword MUS_END
    .hword 0
    .byte 0
    .byte 0
    .byte WEATHER_NONE
    .byte 0
    .hword 0
    map_header_flags allow_cycling=1, allow_escaping=1, allow_running=1, show_map_name=1
    .byte 0
    # additional data specific to fools2022 maps
    .word WesternEdge_MapInitCode+1
    .word WesternEdge_MapConnections
    .word WesternEdge_MapInitScript
    .word WesternEdge_MapName
    .word 0x2819

WesternEdge_MapLayout:
    .word 20
    .word 14
    .word WesternEdge_MapBorder
    .word WesternEdge_MapData
    .word gTileset_General
    .word gTileset_Petalburg

.align 4
WesternEdge_MapObjectEvents:
    object_event 1, OBJ_EVENT_GFX_NORMAN, 0, 6, 4, 3, MOVEMENT_TYPE_NONE, 0, 0, TRAINER_TYPE_NONE, 0, WesternEdge_Script1, 0

.align 4
WesternEdge_MapCoordEvents:
WesternEdge_WarpCoordEvents:
    coord_event 12, 4, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT
    coord_event 12, 5, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT
    coord_event 12, 6, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT
    coord_event 12, 7, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT

.align 4
WesternEdge_MapBGEvents:

.align 4
WesternEdge_MapEvts:
    map_events 1, WesternEdge_MapObjectEvents, 0, 0, 4, WesternEdge_MapCoordEvents, 0, WesternEdge_MapBGEvents

.align 4
WesternEdge_MapBorder:
    .byte 0x70, 0x01, 0x70, 0x01, 0x70, 0x01, 0x70, 0x01

.align 4
WesternEdge_MapData:
    .hword 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170
    .hword 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170
    .hword 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170
    .hword 0x0170, 0x0170, 0x0170, 0x0170, 0xa592, 0xa534, 0xb534, 0xb534, 0xa534, 0xa534, 0xc534, 0xc534, 0xb534, 0xc534, 0xb534, 0xa534, 0xa534, 0xa534, 0xb534, 0xc534
    .hword 0x0170, 0x0170, 0x0170, 0x0170, 0xb592, 0xa602, 0x3001, 0xa602, 0x3004, 0x3001, 0x3001, 0x3001, 0x3004, 0x3001, 0x3001, 0x3001, 0x3004, 0x3001, 0x3001, 0x3001
    .hword 0x0170, 0x0170, 0x0170, 0x0170, 0xb592, 0xb539, 0x3001, 0x3001, 0x3001, 0x3004, 0x3001, 0x3001, 0x3001, 0x3004, 0x3001, 0x3001, 0x3001, 0x3004, 0x3001, 0x3001
    .hword 0x0170, 0x0170, 0x0170, 0x0170, 0xb592, 0xb540, 0x3004, 0x3001, 0x3001, 0x3001, 0x3004, 0x3001, 0x3001, 0x3001, 0x3004, 0x3001, 0x3001, 0x3001, 0x3004, 0x3001
    .hword 0x0170, 0x0170, 0x0170, 0x0170, 0xa592, 0xb540, 0x3001, 0x3004, 0x3001, 0x3001, 0x3001, 0x3004, 0x3001, 0x3001, 0x3001, 0x3004, 0x3001, 0x3001, 0x3001, 0x3004
    .hword 0x0170, 0x0170, 0x0170, 0x0170, 0xb592, 0xc548, 0xc549, 0xa549, 0xa549, 0xb549, 0xa549, 0xa549, 0xb549, 0xc549, 0xb549, 0xa549, 0xa549, 0xb549, 0xb549, 0xb549
    .hword 0x0170, 0x0170, 0x0170, 0x0170, 0xc59a, 0xa589, 0xc589, 0xa589, 0xc589, 0xc589, 0xb589, 0xa589, 0xb589, 0xb589, 0xa589, 0xb589, 0xc589, 0xa589, 0xa589, 0xb589
    .hword 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170
    .hword 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170
    .hword 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170
    .hword 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170, 0x0170

.align 4
WesternEdge_MapConnections:
    .hword 0x2c29
    .byte 135, 140
    .hword 0x2c29
    .byte 135, 140
    .hword 0x2c29
    .byte 135, 140
    .hword 0x2c29
    .byte 135, 140

.align 4
WesternEdge_MapName:
    .string "WESTERN EDGE$"

# scripts/2D27_WesternEdge.s

.align 4

WesternEdge_MapInitCode:
    bx lr

WesternEdge_MapInitScript:
    end

WesternEdge_Script1:
    lock
    faceplayer
    checkflag FLAG_WESTERN_EDGE
    goto_if TRUE, WesternEdge_Script1_Finished
    msgbox WesternEdge_Script1_Text
    waitmessage
	closemessage
    delay 60
    playse SE_M_DETECT
    delay 20
	setvar VAR_RESULT, 3
	playse SE_ORB
	callnative DoOrbEffect
    delay 150
    callnative FadeOutOrbEffect
    waitstate
    delay 10
    message WesternEdge_Script1_Text2
    setflag FLAG_WESTERN_EDGE
    setflag FLAG_TELEPORTATION_ENABLED
    playfanfare MUS_SLOTS_JACKPOT
    waitfanfare
    call SyncProgressScript
    msgbox WesternEdge_Script1_Text4
    release
    end
WesternEdge_Script1_Finished:
    msgbox WesternEdge_Script1_Text3
    release
    end

WesternEdge_Script1_Text:
    .string "Ah, our great land, far-reaching and\n"
    .string "vast.\p"
    .string "Many seek the power to traverse this\n"
    .string "terrain easier, dropping the worry\l"
    .string "about time and distance.\p"
    .string "That monumental power.\n"
    .string "This is what I grant you.$"

WesternEdge_Script1_Text2:
    .string "The TELEPORT ability was granted!$"
    
WesternEdge_Script1_Text3:
    .string "Hope I see you another time...$"

WesternEdge_Script1_Text4:
    .string "Use the hallowed ground found in\n"
    .string "town areas to commence teleportation.$"

