# fools2022 - autogenerated map file, please do not change!
# created from: pokeemerald/data/maps/x2F7F_EasternEncampment/map.json

.thumb
.include "include/constants.inc"
.org MAP_LOAD_BASE

.include "include/macros.inc"
.include "include/symbols.inc"
.include "include/map.inc"
.include "include/event.inc"
.include "include/save.inc"

EasternEncampment_MapHeader:
    .word EasternEncampment_MapLayout
    .word EasternEncampment_MapEvts
    .word NULL
    .word NULL
    .hword MUS_RG_FUCHSIA
    .hword 0
    .byte 0
    .byte 0
    .byte WEATHER_NONE
    .byte 0
    .hword 0
    map_header_flags allow_cycling=1, allow_escaping=1, allow_running=1, show_map_name=1
    .byte 0
    # additional data specific to fools2022 maps
    .word EasternEncampment_MapInitCode+1
    .word EasternEncampment_MapConnections
    .word EasternEncampment_MapInitScript
    .word EasternEncampment_MapName
    .word 0x0700

EasternEncampment_MapLayout:
    .word 10
    .word 9
    .word EasternEncampment_MapBorder
    .word EasternEncampment_MapData
    .word gTileset_Building
    .word gTileset_GenericBuilding

.align 4
EasternEncampment_MapObjectEvents:
    object_event 1, OBJ_EVENT_GFX_MAN_4, 0, 5, 4, 3, MOVEMENT_TYPE_FACE_LEFT, 0, 0, TRAINER_TYPE_NONE, 0, EasternCamp_Script1, 0

.align 4
EasternEncampment_MapCoordEvents:
EasternEncampment_WarpCoordEvents:
    coord_event 3, 8, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT
    coord_event 4, 8, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT

.align 4
EasternEncampment_MapBGEvents:

.align 4
EasternEncampment_MapEvts:
    map_events 1, EasternEncampment_MapObjectEvents, 0, 0, 2, EasternEncampment_MapCoordEvents, 0, EasternEncampment_MapBGEvents

.align 4
EasternEncampment_MapBorder:
    .byte 0x01, 0x02, 0x01, 0x02, 0x01, 0x02, 0x01, 0x02

.align 4
EasternEncampment_MapData:
    .hword 0xc686, 0xb687, 0xb679, 0xb67a, 0xb605, 0xb607, 0xb605, 0xc605, 0xc605, 0xb605
    .hword 0xa68e, 0xb68f, 0xb681, 0xa682, 0xa60d, 0xb60f, 0xc60d, 0xb60d, 0xa690, 0xc690
    .hword 0x3296, 0x3297, 0x3289, 0x328a, 0x3224, 0x3224, 0x3224, 0x3224, 0xc698, 0xa698
    .hword 0x3239, 0x3235, 0x3236, 0x3236, 0x3236, 0x3236, 0x3236, 0x3237, 0x3223, 0x3223
    .hword 0x3239, 0x323d, 0x32e1, 0xa648, 0xc649, 0x32e2, 0x323e, 0x323f, 0x3223, 0x3223
    .hword 0x3239, 0x323d, 0x32e1, 0xa650, 0xb651, 0x32e2, 0x323e, 0x323f, 0x3223, 0x3223
    .hword 0x3239, 0x3245, 0x3246, 0x3246, 0x3246, 0x3246, 0x3246, 0x3247, 0x3223, 0x3223
    .hword 0x3239, 0x3223, 0x3223, 0x3223, 0x3223, 0x3223, 0x3223, 0x3223, 0x3223, 0x3222
    .hword 0x3239, 0x3223, 0x3223, 0x0208, 0x0209, 0x3223, 0x3223, 0x3223, 0x3223, 0xa62a

.align 4
EasternEncampment_MapConnections:
    .hword 12088
    .byte 15, 9
    .hword 12088
    .byte 15, 9

.align 4
EasternEncampment_MapName:
    .string "EASTERN CAMP$"

# scripts/2F7F_EasternEncampment.s

.align 4

EasternEncampment_MapInitCode:
    ldr r0, =zSkipMapExitMovement
    mov r1, #2
    strb r1, [r0]
    bx lr

.align 4
.ltorg

EasternEncampment_MapInitScript:
    end

EasternCamp_Script1:
    lock
    faceplayer
    checkplayergender
    compare VAR_RESULT, MALE
    goto_if_eq EasternCamp_Script1_NotCute
EasternCamp_Script1_Cute:
    checkflag FLAG_RECEIVED_BALL7
    goto_if TRUE, EasternCamp_Script1_Done
    setflag FLAG_RECEIVED_BALL7
    msgbox EasternCamp_Script1_Text3
    giveitem 4
    call SyncProgressScript
    release
    end
EasternCamp_Script1_NotCute:
    msgbox EasternCamp_Script1_Text
    release
    end
EasternCamp_Script1_Done:
    msgbox EasternCamp_Script1_Text2
    release
    end

EasternCamp_Script1_Text:
    .string "Yes, finally I was able to pay my\n"
    .string "electricity bills...\p"
    .string "Wait, how did you get here?\n"
    .string "Why did you just barge into my house?\p"
    .string "Please leave me alone.\n"
    .string "I only speak with cuties.$"

EasternCamp_Script1_Text2:
    .string "Wait... you say you're a boy?\n"
    .string "Jokes on you, I'm into that...\p"
    .string "But... It's not that I like you or\n"
    .string "anything!\p"
    .string "Was just speaking... hypothetically.\n"
    .string "You know... just a theory.$"

EasternCamp_Script1_Text3:
    .string "Hey...\n"
    .string "You do be looking kinda cute...\p"
    .string "I feel kinda nervous...\n"
    .string "Say, do you like balls?\p"
    .string "I... I mean Pok{EACUTE} Balls!\n"
    .string "I just found one...\p"
    .string "They're pretty rare here...\n"
    .string "So... I can give you one... as a gift.$"
