# fools2022 - autogenerated map file, please do not change!
# created from: pokeemerald/data/maps/x2F81_FunVerEasternEncampment/map.json

.thumb
.include "include/constants.inc"
.org MAP_LOAD_BASE

.include "include/macros.inc"
.include "include/symbols.inc"
.include "include/map.inc"
.include "include/event.inc"
.include "include/save.inc"

FunVerEasternEncampment_MapHeader:
    .word FunVerEasternEncampment_MapLayout
    .word FunVerEasternEncampment_MapEvts
    .word NULL
    .word NULL
    .hword MUS_RG_FUCHSIA
    .hword 0
    .byte 0
    .byte 0
    .byte WEATHER_NONE
    .byte 0
    .hword 0
    map_header_flags allow_cycling=1, allow_escaping=1, allow_running=1, show_map_name=1
    .byte 0
    # additional data specific to fools2022 maps
    .word FunVerEasternEncampment_MapInitCode+1
    .word FunVerEasternEncampment_MapConnections
    .word FunVerEasternEncampment_MapInitScript
    .word FunVerEasternEncampment_MapName
    .word 0x2819

FunVerEasternEncampment_MapLayout:
    .word 12
    .word 8
    .word FunVerEasternEncampment_MapBorder
    .word FunVerEasternEncampment_MapData
    .word gTileset_Building
    .word gTileset_Facility

.align 4
FunVerEasternEncampment_MapObjectEvents:
    object_event 1, OBJ_EVENT_GFX_WOMAN_2, 0, 2, 3, 3, MOVEMENT_TYPE_FACE_LEFT, 0, 0, TRAINER_TYPE_NONE, 0, EasternEncampment_Script1, 0
    object_event 2, OBJ_EVENT_GFX_MAN_4, 0, 6, 4, 3, MOVEMENT_TYPE_FACE_UP, 0, 0, TRAINER_TYPE_NONE, 0, EasternEncampment_Script2, 0

.align 4
FunVerEasternEncampment_MapCoordEvents:
FunVerEasternEncampment_WarpCoordEvents:
    coord_event 2, 7, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT
    coord_event 3, 7, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT

.align 4
FunVerEasternEncampment_MapBGEvents:
    bg_event 10, 3, 0, BG_EVENT_PLAYER_FACING_ANY, EasternEncampment_Script3
    bg_event 10, 6, 0, BG_EVENT_PLAYER_FACING_ANY, EasternEncampment_Script4
    bg_event 6, 6, 0, BG_EVENT_PLAYER_FACING_ANY, EasternEncampment_Script5
    bg_event 6, 3, 0, BG_EVENT_PLAYER_FACING_ANY, EasternEncampment_Script6

.align 4
FunVerEasternEncampment_MapEvts:
    map_events 2, FunVerEasternEncampment_MapObjectEvents, 0, 0, 2, FunVerEasternEncampment_MapCoordEvents, 4, FunVerEasternEncampment_MapBGEvents

.align 4
FunVerEasternEncampment_MapBorder:
    .byte 0x01, 0x02, 0x01, 0x02, 0x01, 0x02, 0x01, 0x02

.align 4
FunVerEasternEncampment_MapData:
    .hword 0xa788, 0xb788, 0xb788, 0xb789, 0xb788, 0xb788, 0xb788, 0xa788, 0xa789, 0xa788, 0xb788, 0xc788
    .hword 0xc790, 0xa790, 0xc790, 0xb791, 0xc790, 0xa790, 0xc790, 0xc790, 0xa791, 0xc790, 0xa790, 0xb790
    .hword 0xc7a5, 0xc7a6, 0x3384, 0x3380, 0x3380, 0x3380, 0x33a3, 0x33a4, 0x3380, 0x3380, 0x33a3, 0x33a4
    .hword 0xc7ad, 0xb7ae, 0x3384, 0x3380, 0x3380, 0x3380, 0xc7ab, 0xa7ac, 0x3380, 0x3380, 0xb7ab, 0xa7ac
    .hword 0x3384, 0x3380, 0x3380, 0x3380, 0x3380, 0x3380, 0x33a7, 0x3380, 0x3380, 0x3380, 0x33a7, 0x3380
    .hword 0x3384, 0x3380, 0x3380, 0x3380, 0x3380, 0x3380, 0x33a3, 0x33a4, 0x3380, 0x3380, 0x33a3, 0x33a4
    .hword 0x3384, 0x3380, 0x3380, 0x3380, 0x3380, 0x3380, 0xc7ab, 0xb7ac, 0x3380, 0x3380, 0xb7ab, 0xc7ac
    .hword 0x3384, 0x3380, 0x3206, 0x3207, 0x3380, 0x3380, 0x33a7, 0x3380, 0x3380, 0x3380, 0x33a7, 0x3380

.align 4
FunVerEasternEncampment_MapConnections:
    .hword 12088
    .byte 21, 3
    .hword 12088
    .byte 21, 3

.align 4
FunVerEasternEncampment_MapName:
    .string "EASTERN CAMP$"

# scripts/2F81_FunVerEasternEncampment.s

.align 4

FunVerEasternEncampment_MapInitCode:
    ldr r0, =zSkipMapExitMovement
    mov r1, #2
    strb r1, [r0]
    bx lr

.align 4
.ltorg

FunVerEasternEncampment_MapInitScript:
    end

EasternEncampment_Script1:
    lock
    faceplayer
    msgbox EasternEncampment_Script1_Text
    release
    end

EasternEncampment_Script1_Text:
    .string "We?\n"
    .string "We're just a humble game studio.\p"
    .string "We're working on many things, but it's\n"
    .string "our day off today.\p"
    .string "It's because TheZZAZZGlitch has just\n"
    .string "released his April Fools event.\p"
    .string "Quickly! We need to disassemble it and\n"
    .string "look at the code!$"

EasternEncampment_Script2:
    lock
    faceplayer
    msgbox EasternEncampment_Script2_Text
    release
    end

EasternEncampment_Script2_Text:
    .string "Holy crap, the code behind this event\n"
    .string "is so stupid!\p"
    .string "And it's handwritten assembly on a\n"
    .string "system where C programming is a thing?\p"
    .string "Why would you do that?\n"
    .string "Not only that, it's bad assembly!\p"
    .string "Like, {LQUOT}add r0, r0{RQUOT} twice to multiply\l"
    .string "by 4? Bro, it's not Z80! Use LSL!\p"
    .string "Two instructions to load and increment?\n"
    .string "Addressing modes are a thing, ya know?\p"
    .string "Wait, is that {LQUOT}ldr r0, =0{RQUOT}?\n"
    .string "Arrrgghhhh!$"

EasternEncampment_Script3:
    lock
    msgbox EasternEncampment_Script3_Text
    release
    end

EasternEncampment_Script3_Text:
    .string "It's the game program. Messing with\n"
    .string "it could bug out the game!\p"
    .string "Ah, wait. The game's already buggy as\n"
    .string "hell...$"

EasternEncampment_Script4:
    lock
    msgbox EasternEncampment_Script4_Text
    release
    end

EasternEncampment_Script4_Text:
    .string "It's a workstation with a Maxtor\n"
    .string "7200 RPM hard drive attached.\p"
    .string "... ... ... ... ...\n"
    .string "... ... ... ... ...\p"
    .string "Wait, this isn't a Maxtor.\n"
    .string "This is a Quantum Bigfoot!$"

EasternEncampment_Script5:
    lock
    msgbox EasternEncampment_Script5_Text
    release
    end

EasternEncampment_Script5_Text:
    .string "A conversation thread is displayed on\n"
    .string "the monitor.\p"
    .string "Several users argued about something,\n"
    .string "but then... it just kind of stopped.\l"
    .string "Last post written back in 2019.\p"
    .string "Everything comes to an end sooner or\n"
    .string "later. It's inevitable.\p"
    .string "At least make sure it's a good ending,\n"
    .string "because this one is not.\p"
    .string "What the hell is Fidei?\n"
    .string "It's where dreams have died.$"

EasternEncampment_Script6:
    lock
    msgbox EasternEncampment_Script6_Text
    release
    end

EasternEncampment_Script6_Text:
    .string "The screen is filled with assembly\n"
    .string "instructions that you don't understand.$"

