# fools2022 - autogenerated map file, please do not change!
# created from: pokeemerald/data/maps/x318E_CrackerCavernIV/map.json

.thumb
.include "include/constants.inc"
.org MAP_LOAD_BASE

.include "include/macros.inc"
.include "include/symbols.inc"
.include "include/map.inc"
.include "include/event.inc"
.include "include/save.inc"

CrackerCavernIV_MapHeader:
    .word CrackerCavernIV_MapLayout
    .word CrackerCavernIV_MapEvts
    .word NULL
    .word NULL
    .hword MUS_VICTORY_ROAD
    .hword 0
    .byte 0
    .byte 0
    .byte WEATHER_NONE
    .byte 0
    .hword 0
    map_header_flags allow_cycling=1, allow_escaping=1, allow_running=1, show_map_name=1
    .byte 0
    # additional data specific to fools2022 maps
    .word CrackerCavernIV_MapInitCode+1
    .word CrackerCavernIV_MapConnections
    .word CrackerCavernIV_MapInitScript
    .word CrackerCavernIV_MapName
    .word 0x0010

CrackerCavernIV_MapLayout:
    .word 12
    .word 12
    .word CrackerCavernIV_MapBorder
    .word CrackerCavernIV_MapData
    .word gTileset_General
    .word gTileset_Cave

.align 4
CrackerCavernIV_MapObjectEvents:
    object_event 1, OBJ_EVENT_GFX_NOLAND, 0, 9, 2, 3, MOVEMENT_TYPE_NONE, 0, 0, TRAINER_TYPE_NONE, 0, CrackerCavern_Wello, 0

.align 4
CrackerCavernIV_MapCoordEvents:
CrackerCavernIV_WarpCoordEvents:
    coord_event 2, 2, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT
    coord_event 9, 9, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT

.align 4
CrackerCavernIV_MapBGEvents:
    bg_event 6, 2, 0, BG_EVENT_PLAYER_FACING_ANY, CrackerCavernI_Script1

.align 4
CrackerCavernIV_MapEvts:
    map_events 1, CrackerCavernIV_MapObjectEvents, 0, 0, 2, CrackerCavernIV_MapCoordEvents, 1, CrackerCavernIV_MapBGEvents

.align 4
CrackerCavernIV_MapBorder:
    .byte 0x11, 0x02, 0x11, 0x02, 0x11, 0x02, 0x11, 0x02

.align 4
CrackerCavernIV_MapData:
    .hword 0xc21b, 0xc219, 0xc219, 0xc219, 0xc219, 0xc219, 0xc219, 0xc219, 0xc219, 0xc219, 0xc219, 0xc21c
    .hword 0xc212, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0xc210
    .hword 0xc212, 0x3201, 0x323e, 0x3201, 0x3201, 0x3201, 0xb403, 0x3201, 0x3201, 0x3201, 0x3201, 0xc210
    .hword 0xc212, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0xc210
    .hword 0xc212, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0xc210
    .hword 0xc212, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0xc210
    .hword 0xc212, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0xc210
    .hword 0xc212, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0xc202, 0xc202, 0xc203, 0xc202, 0xc210
    .hword 0xc212, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0xc21f, 0x3201, 0x3201, 0x3201, 0xc210
    .hword 0xc212, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0xc227, 0x3201, 0x323f, 0x3201, 0xc210
    .hword 0xc212, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0xc203, 0x3201, 0x3201, 0x3201, 0xc210
    .hword 0xc209, 0xc209, 0xc209, 0xc209, 0xc209, 0xc209, 0xc209, 0xc209, 0xc209, 0xc209, 0xc209, 0xc209

.align 4
CrackerCavernIV_MapConnections:
    .hword 12685
    .byte 9, 137
    .hword 12689
    .byte 2, 2

.align 4
CrackerCavernIV_MapName:
    .string "CAVERN FLOOR I$"

# scripts/318E_CrackerCavernIV.s

.align 4

CrackerCavernIV_MapInitCode:
    bx lr

CrackerCavernIV_MapInitScript:
    end

CrackerCavern_Wello1:
    lock
    faceplayer
    msgbox CrackerCavern_Wello1_Text
    release
    end

CrackerCavern_Wello1_Text:
    .string "redacted$"

CrackerCavernI_Script1:
    lock
    faceplayer
    msgbox CrackerCavernI_Script1_Text
    release
    end

CrackerCavernI_Script1_Text:
    .string "redacted$"

CrackerCavern_Wello:
    lock
    faceplayer
    msgbox CrackerCavern_Wello_Text
    release
    end

CrackerCavern_Wello_Text:
    .string "redacted$"
