# fools2022 - autogenerated map file, please do not change!
# created from: pokeemerald/data/maps/x3191_CrackerCavernRealV/map.json

.thumb
.include "include/constants.inc"
.org MAP_LOAD_BASE

.include "include/macros.inc"
.include "include/symbols.inc"
.include "include/map.inc"
.include "include/event.inc"
.include "include/save.inc"

CrackerCavernRealV_MapHeader:
    .word CrackerCavernRealV_MapLayout
    .word CrackerCavernRealV_MapEvts
    .word NULL
    .word NULL
    .hword MUS_END
    .hword 0
    .byte 0
    .byte 0
    .byte WEATHER_NONE
    .byte 0
    .hword 0
    map_header_flags allow_cycling=1, allow_escaping=1, allow_running=1, show_map_name=1
    .byte 0
    # additional data specific to fools2022 maps
    .word CrackerCavernRealV_MapInitCode+1
    .word CrackerCavernRealV_MapConnections
    .word CrackerCavernRealV_MapInitScript
    .word CrackerCavernRealV_MapName
    .word 0x2819

CrackerCavernRealV_MapLayout:
    .word 13
    .word 12
    .word CrackerCavernRealV_MapBorder
    .word CrackerCavernRealV_MapData
    .word gTileset_General
    .word gTileset_Cave

.align 4
CrackerCavernRealV_MapObjectEvents:
    object_event 1, OBJ_EVENT_GFX_NORMAN, 0, 6, 2, 3, MOVEMENT_TYPE_FACE_DOWN, 0, 0, TRAINER_TYPE_NONE, 0, CrackerCavern_Gratz, 0

.align 4
CrackerCavernRealV_MapCoordEvents:
CrackerCavernRealV_WarpCoordEvents:
    coord_event 6, 9, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT

.align 4
CrackerCavernRealV_MapBGEvents:

.align 4
CrackerCavernRealV_MapEvts:
    map_events 1, CrackerCavernRealV_MapObjectEvents, 0, 0, 1, CrackerCavernRealV_MapCoordEvents, 0, CrackerCavernRealV_MapBGEvents

.align 4
CrackerCavernRealV_MapBorder:
    .byte 0x11, 0x02, 0x11, 0x02, 0x11, 0x02, 0x11, 0x02

.align 4
CrackerCavernRealV_MapData:
    .hword 0xc21b, 0xc219, 0xc219, 0xc219, 0xc219, 0xc219, 0xc219, 0xc219, 0xc219, 0xc219, 0xc219, 0xc219, 0xc21c
    .hword 0xc212, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0xc210
    .hword 0xc212, 0x3201, 0xc21d, 0xc21e, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0xc21d, 0xc21e, 0x3201, 0xc210
    .hword 0xc212, 0x3201, 0xc225, 0xc226, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0xc225, 0xc226, 0x3201, 0xc210
    .hword 0xc212, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0xc210
    .hword 0xc212, 0x3201, 0x3201, 0xc21d, 0xc21e, 0x3201, 0x3201, 0x3201, 0xc21d, 0xc21e, 0x3201, 0x3201, 0xc210
    .hword 0xc212, 0x3201, 0x3201, 0xc225, 0xc226, 0x3201, 0x3201, 0x3201, 0xc225, 0xc226, 0x3201, 0x3201, 0xc210
    .hword 0xc212, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0xc210
    .hword 0xc212, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0xc210
    .hword 0xc212, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x323e, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0xc210
    .hword 0xc212, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0xc210
    .hword 0xc209, 0xc209, 0xc209, 0xc209, 0xc209, 0xc209, 0xc209, 0xc209, 0xc209, 0xc209, 0xc209, 0xc209, 0xc209

.align 4
CrackerCavernRealV_MapConnections:
    .hword 12688
    .byte 9, 137

.align 4
CrackerCavernRealV_MapName:
    .string "CAVERN DEPTHS$"

# scripts/3191_CrackerCavernRealV.s

.align 4

CrackerCavernRealV_MapInitCode:
    bx lr

CrackerCavernRealV_MapInitScript:
    end

CrackerCavern_Gratz:
    lock
    faceplayer
    checkflag FLAG_HACKER_BACKGROUND
    goto_if TRUE, CrackerCavern_Gratz_Finished
    msgbox CrackerCavern_Gratz_Text
    waitmessage
	closemessage
    delay 60
    playse SE_M_DETECT
    delay 20
	setvar VAR_RESULT, 3
	playse SE_ORB
	callnative DoOrbEffect
    delay 150
    callnative FadeOutOrbEffect
    waitstate
    delay 10
    message CrackerCavern_Gratz_Text2
    setflag FLAG_HACKER_BACKGROUND
    playfanfare MUS_SLOTS_JACKPOT
    waitfanfare
    call SyncProgressScript
CrackerCavern_Gratz_Finished:
    msgbox CrackerCavern_Gratz_Text3
    release
    end

CrackerCavern_Gratz_Text:
    .string "Congratulations! You have completed\n"
    .string "the Cracker Cavern Reborn!\p"
    .string "People of Glitchland are hugely amazed\n"
    .string "by your hacking skill.\p"
    .string "With such an achievement, I think\n"
    .string "a proper reward is in order.$"

CrackerCavern_Gratz_Text2:
    .string "You have unlocked the coveted\n"
    .string "Exploitation Expert title!$"

CrackerCavern_Gratz_Text3:
    .string "This leaderboard flair will let\n"
    .string "everyone know of your greatness.\p"
    .string "Now go forth and continue exploring\n"
    .string "Glitchland.\p"
    .string "Hopefully, do so without hacking.\n"
    .string "Don't ruin the fun for yourself!$"

