# fools2022 - autogenerated map file, please do not change!
# created from: pokeemerald/data/maps/x3C36_EasternEdge/map.json

.thumb
.include "include/constants.inc"
.org MAP_LOAD_BASE

.include "include/macros.inc"
.include "include/symbols.inc"
.include "include/map.inc"
.include "include/event.inc"
.include "include/save.inc"

EasternEdge_MapHeader:
    .word EasternEdge_MapLayout
    .word EasternEdge_MapEvts
    .word NULL
    .word NULL
    .hword MUS_END
    .hword 0
    .byte 0
    .byte 0
    .byte WEATHER_NONE
    .byte 0
    .hword 0
    map_header_flags allow_cycling=1, allow_escaping=1, allow_running=1, show_map_name=1
    .byte 0
    # additional data specific to fools2022 maps
    .word EasternEdge_MapInitCode+1
    .word EasternEdge_MapConnections
    .word EasternEdge_MapInitScript
    .word EasternEdge_MapName
    .word 0x2819

EasternEdge_MapLayout:
    .word 18
    .word 12
    .word EasternEdge_MapBorder
    .word EasternEdge_MapData
    .word gTileset_General
    .word gTileset_Fortree

.align 4
EasternEdge_MapObjectEvents:
    object_event 1, OBJ_EVENT_GFX_NORMAN, 0, 14, 2, 3, MOVEMENT_TYPE_NONE, 0, 0, TRAINER_TYPE_NONE, 0, EasternEdge_Script1, 0

.align 4
EasternEdge_MapCoordEvents:
EasternEdge_WarpCoordEvents:
    coord_event 7, 4, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT
    coord_event 7, 5, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT
    coord_event 7, 6, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT
    coord_event 7, 7, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT

.align 4
EasternEdge_MapBGEvents:

.align 4
EasternEdge_MapEvts:
    map_events 1, EasternEdge_MapObjectEvents, 0, 0, 4, EasternEdge_MapCoordEvents, 0, EasternEdge_MapBGEvents

.align 4
EasternEdge_MapBorder:
    .byte 0xd4, 0x01, 0xd5, 0x01, 0xdc, 0x01, 0xdd, 0x01

.align 4
EasternEdge_MapData:
    .hword 0xc5d6, 0xb5d7, 0xc5d6, 0xb5d7, 0xb5d6, 0xb5d7, 0xa5d6, 0xc5d7, 0xc5d6, 0xc5d7, 0xa5d6, 0xc5d7, 0xa5d6, 0xb5d7, 0xb5d6, 0xa5d7, 0xb5d6, 0xb5d7
    .hword 0x31de, 0x31df, 0x31de, 0x31df, 0x31de, 0x31df, 0x31de, 0x31df, 0xa5e4, 0xa5e5, 0xa5e4, 0xa5e5, 0xc5e4, 0xa5e5, 0xb5e4, 0xa5e5, 0xb5e4, 0xa5e5
    .hword 0x31d6, 0x31d7, 0x31d6, 0x31d7, 0x31d6, 0x31d7, 0x31d6, 0x31d7, 0x3004, 0x3001, 0x3004, 0x3001, 0x3004, 0x30e0, 0x3001, 0x30e0, 0x3004, 0x3001
    .hword 0xb5e4, 0xb5e5, 0xb5e4, 0xb5e5, 0xa5e4, 0xb5e5, 0xb5e4, 0xb5e5, 0x3001, 0x30e0, 0x3001, 0x30e0, 0x3001, 0x3001, 0x3004, 0x3001, 0x3001, 0x3004
    .hword 0x3001, 0x3001, 0x3001, 0x3001, 0x3001, 0x3001, 0x3001, 0x3001, 0x3004, 0x3001, 0x3004, 0x3001, 0x3004, 0x31d0, 0x31d1, 0x31d2, 0x3004, 0x3001
    .hword 0x31d1, 0x31d1, 0x31d1, 0x31d1, 0x31d1, 0x31d1, 0x31d1, 0x31d1, 0x31d1, 0x31d1, 0x31d1, 0x31d1, 0x31d1, 0x31d9, 0x31d9, 0x31d9, 0x31d2, 0x3001
    .hword 0x31e1, 0x31e1, 0x31e1, 0x31e1, 0x31e1, 0x31e1, 0x31e1, 0x31e1, 0x31e1, 0x31e1, 0x31e1, 0x31e1, 0x31e1, 0x31d9, 0x31d9, 0x31d9, 0x31e2, 0x3001
    .hword 0x31ce, 0x31cf, 0x31ce, 0x31cf, 0x31ce, 0x31cf, 0x31ce, 0x31cf, 0x3004, 0x3001, 0x3004, 0x3001, 0x3004, 0x31e0, 0x31e1, 0x31e2, 0x3004, 0x3001
    .hword 0x31d6, 0x31d7, 0x31d6, 0x31d7, 0x31d6, 0x31d7, 0x31d6, 0x31d7, 0x3001, 0x30e0, 0x3001, 0x30e0, 0x3001, 0x3001, 0x3004, 0x3001, 0x3001, 0x3004
    .hword 0x31de, 0x31df, 0x31de, 0x31df, 0x31de, 0x31df, 0x31de, 0x31df, 0x3004, 0x3001, 0x3004, 0x3001, 0x3004, 0x30e0, 0x3001, 0x30e0, 0x3004, 0x3001
    .hword 0x31d6, 0x31d7, 0x31d6, 0x31d7, 0x31d6, 0x31d7, 0x31d6, 0x31d7, 0x3149, 0x3149, 0x3149, 0x3149, 0x3149, 0x3149, 0x3149, 0x3149, 0x3149, 0x3149
    .hword 0x31de, 0x31df, 0x31de, 0x31df, 0x31de, 0x31df, 0x31de, 0x31df, 0x31c6, 0x31c7, 0x31c6, 0x31c7, 0x31c6, 0x31c7, 0x31c6, 0x31c7, 0x31c6, 0x31c7

.align 4
EasternEdge_MapConnections:
    .hword 15138
    .byte 13, 7
    .hword 15138
    .byte 13, 7
    .hword 15138
    .byte 13, 7
    .hword 15138
    .byte 13, 7

.align 4
EasternEdge_MapName:
    .string "EASTERN EDGE$"

# scripts/3C36_EasternEdge.s

.align 4

EasternEdge_MapInitCode:
    bx lr

EasternEdge_MapInitScript:
    end

EasternEdge_Script1:
    lock
    faceplayer
    checkflag FLAG_EASTERN_EDGE
    goto_if TRUE, EasternEdge_Script1_Finished
    msgbox EasternEdge_Script1_Text
    waitmessage
	closemessage
    delay 60
    playse SE_M_DETECT
    delay 20
	setvar VAR_RESULT, 3
	playse SE_ORB
	callnative DoOrbEffect
    delay 150
    callnative FadeOutOrbEffect
    waitstate
    delay 10
    message EasternEdge_Script1_Text2
    setflag FLAG_EASTERN_EDGE
    setflag 0x86a
    playfanfare MUS_SLOTS_JACKPOT
    waitfanfare
    call SyncProgressScript
    release
    end
EasternEdge_Script1_Finished:
    msgbox EasternEdge_Script1_Text3
    release
    end

EasternEdge_Script1_Text:
    .string "Ah, our great land, filled with dark,\n"
    .string "immense cave systems.\p"
    .string "Many seek the power to push through\n"
    .string "the rockfall found inside them.\p"
    .string "That monumental power.\n"
    .string "This is what I grant you.$"

EasternEdge_Script1_Text2:
    .string "The STRENGTH ability was granted!$"
    
EasternEdge_Script1_Text3:
    .string "Hope I see you another time...$"

