# fools2022 - autogenerated map file, please do not change!
# created from: pokeemerald/data/maps/x3D83_DesignersHouse/map.json

.thumb
.include "include/constants.inc"
.org MAP_LOAD_BASE

.include "include/macros.inc"
.include "include/symbols.inc"
.include "include/map.inc"
.include "include/event.inc"
.include "include/save.inc"

DesignersHouse_MapHeader:
    .word DesignersHouse_MapLayout
    .word DesignersHouse_MapEvts
    .word NULL
    .word NULL
    .hword MUS_RG_FUCHSIA
    .hword 0
    .byte 0
    .byte 0
    .byte WEATHER_NONE
    .byte 0
    .hword 0
    map_header_flags allow_cycling=1, allow_escaping=1, allow_running=1, show_map_name=1
    .byte 0
    # additional data specific to fools2022 maps
    .word DesignersHouse_MapInitCode+1
    .word DesignersHouse_MapConnections
    .word DesignersHouse_MapInitScript
    .word DesignersHouse_MapName
    .word 0x2819

DesignersHouse_MapLayout:
    .word 10
    .word 9
    .word DesignersHouse_MapBorder
    .word DesignersHouse_MapData
    .word gTileset_Building
    .word gTileset_GenericBuilding

.align 4
DesignersHouse_MapObjectEvents:
    object_event 1, OBJ_EVENT_GFX_NINJA_BOY, 0, 5, 4, 3, MOVEMENT_TYPE_FACE_LEFT, 0, 0, TRAINER_TYPE_NONE, 0, EasternCamp_Script1, 0

.align 4
DesignersHouse_MapCoordEvents:
DesignersHouse_WarpCoordEvents:
    coord_event 3, 8, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT
    coord_event 4, 8, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT

.align 4
DesignersHouse_MapBGEvents:

.align 4
DesignersHouse_MapEvts:
    map_events 1, DesignersHouse_MapObjectEvents, 0, 0, 2, DesignersHouse_MapCoordEvents, 0, DesignersHouse_MapBGEvents

.align 4
DesignersHouse_MapBorder:
    .byte 0x01, 0x02, 0x01, 0x02, 0x01, 0x02, 0x01, 0x02

.align 4
DesignersHouse_MapData:
    .hword 0xb686, 0xc687, 0xc679, 0xc67a, 0xa605, 0xc607, 0xa605, 0xa605, 0xc605, 0xb605
    .hword 0xa68e, 0xb68f, 0xa681, 0xb682, 0xc60d, 0xc60f, 0xb60d, 0xa60d, 0xa690, 0xb690
    .hword 0x3296, 0x3297, 0x3289, 0x328a, 0x3224, 0x3224, 0x3224, 0x3224, 0xc698, 0xc698
    .hword 0x3239, 0x3235, 0x3236, 0x3236, 0x3236, 0x3236, 0x3236, 0x3237, 0x3223, 0x3223
    .hword 0x3239, 0x323d, 0x32e1, 0xb648, 0xb649, 0x32e2, 0x323e, 0x323f, 0x3223, 0x3223
    .hword 0x3239, 0x323d, 0x32e1, 0xc650, 0xa651, 0x32e2, 0x323e, 0x323f, 0x3223, 0x3223
    .hword 0x3239, 0x3245, 0x3246, 0x3246, 0x3246, 0x3246, 0x3246, 0x3247, 0x3223, 0x3223
    .hword 0x3239, 0x3223, 0x3223, 0x3223, 0x3223, 0x3223, 0x3223, 0x3223, 0x3223, 0x3222
    .hword 0x3239, 0x3223, 0x3223, 0x0208, 0x0209, 0x3223, 0x3223, 0x3223, 0x3223, 0xb62a

.align 4
DesignersHouse_MapConnections:
    .hword 15648
    .byte 11, 9
    .hword 15648
    .byte 11, 9

.align 4
DesignersHouse_MapName:
    .string "DESIGNER'S HOUSE$"

# scripts/3D83_DesignersHouse.s

.align 4

DesignersHouse_MapInitCode:
    ldr r0, =zSkipMapExitMovement
    mov r1, #2
    strb r1, [r0]
    bx lr

.align 4
.ltorg

DesignersHouse_MapInitScript:
    end

EasternCamp_Script1:
    lock
    faceplayer
    msgbox EasternCamp_Script1_Text
    release
    end

EasternCamp_Script1_Text:
    .string "Hello! I'm Matthew!\n"
    .string "The genius level designer!\l"
    .string "Game design is my passion!\p"
    .string "I've created a great new map for\n"
    .string "you to enjoy. Could you help me with\l"
    .string "beta-testing?\p"
    .string "Just go to the west from here and\n"
    .string "you'll be impressed!$"

