# fools2022 - autogenerated map file, please do not change!
# created from: pokeemerald/data/maps/x4384_TheLibrary/map.json

.thumb
.include "include/constants.inc"
.org MAP_LOAD_BASE

.include "include/macros.inc"
.include "include/symbols.inc"
.include "include/map.inc"
.include "include/event.inc"
.include "include/save.inc"

TheLibrary_MapHeader:
    .word TheLibrary_MapLayout
    .word TheLibrary_MapEvts
    .word NULL
    .word NULL
    .hword MUS_LILYCOVE_MUSEUM
    .hword 0
    .byte 0
    .byte 0
    .byte WEATHER_NONE
    .byte 0
    .hword 0
    map_header_flags allow_cycling=1, allow_escaping=1, allow_running=1, show_map_name=1
    .byte 0
    # additional data specific to fools2022 maps
    .word TheLibrary_MapInitCode+1
    .word TheLibrary_MapConnections
    .word TheLibrary_MapInitScript
    .word TheLibrary_MapName
    .word 0x2819

TheLibrary_MapLayout:
    .word 18
    .word 12
    .word TheLibrary_MapBorder
    .word TheLibrary_MapData
    .word gTileset_Building
    .word gTileset_PokemonFanClub

.align 4
TheLibrary_MapObjectEvents:
    object_event 1, OBJ_EVENT_GFX_FAT_MAN, 0, 5, 7, 3, MOVEMENT_TYPE_FACE_LEFT, 0, 0, TRAINER_TYPE_NONE, 0, TheLibrary_Script1, 0
    object_event 2, OBJ_EVENT_GFX_RUNNING_TRIATHLETE_M, 0, 12, 5, 3, MOVEMENT_TYPE_NONE, 0, 0, TRAINER_TYPE_NONE, 0, TheLibrary_Script2, 0
    object_event 3, OBJ_EVENT_GFX_GIRL_2, 0, 3, 4, 3, MOVEMENT_TYPE_FACE_UP, 0, 0, TRAINER_TYPE_NONE, 0, TheLibrary_Script3, 0

.align 4
TheLibrary_MapCoordEvents:
TheLibrary_WarpCoordEvents:
    coord_event 8, 11, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT
    coord_event 9, 11, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT

.align 4
TheLibrary_MapBGEvents:

.align 4
TheLibrary_MapEvts:
    map_events 3, TheLibrary_MapObjectEvents, 0, 0, 2, TheLibrary_MapCoordEvents, 0, TheLibrary_MapBGEvents

.align 4
TheLibrary_MapBorder:
    .byte 0x01, 0x00, 0x01, 0x00, 0x01, 0x00, 0x01, 0x00

.align 4
TheLibrary_MapData:
    .hword 0xc401, 0xb401, 0xc401, 0xa401, 0xc401, 0xb401, 0xa401, 0xc611, 0xa611, 0xb611, 0xc611, 0xb401, 0xb401, 0xa401, 0xa401, 0xc401, 0xa401, 0xb401
    .hword 0xb614, 0xa611, 0xb611, 0xa611, 0xa611, 0xa611, 0xc614, 0xc642, 0xa643, 0xa642, 0xc643, 0xb614, 0xa611, 0xb611, 0xb611, 0xb611, 0xb611, 0xa614
    .hword 0xc61c, 0xb643, 0xc642, 0xc643, 0xa642, 0xb643, 0xa61c, 0xc64a, 0xb64b, 0xa64a, 0xc64b, 0xa61c, 0xc642, 0xb643, 0xa642, 0xb643, 0xb642, 0xc61c
    .hword 0xc624, 0xb64b, 0xb64a, 0xb64b, 0xa64a, 0xb64b, 0xb624, 0x3201, 0x3201, 0x3201, 0x3201, 0xc624, 0xa64a, 0xb64b, 0xb64a, 0xa64b, 0xa64a, 0xb624
    .hword 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201
    .hword 0x3201, 0x3228, 0x3229, 0x3229, 0x3229, 0x3229, 0x3201, 0xb647, 0x3201, 0x3201, 0xb647, 0x3201, 0x3228, 0x3229, 0x3229, 0x3229, 0x3229, 0x3201
    .hword 0x3201, 0x3230, 0xa660, 0xb661, 0xa662, 0x3231, 0x3201, 0xb64f, 0x3201, 0x3201, 0xa64f, 0x3201, 0x3230, 0xa660, 0xb661, 0xc662, 0x3231, 0x3201
    .hword 0x3201, 0x322e, 0xa654, 0xc655, 0xc657, 0x322d, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x322e, 0xc654, 0xb655, 0xb657, 0x322d, 0x3201
    .hword 0x3201, 0x3236, 0xa654, 0xa655, 0xc657, 0x3235, 0x3201, 0xc647, 0x3201, 0x3201, 0xa647, 0x3201, 0x3236, 0xa654, 0xc655, 0xa657, 0x3235, 0x3201
    .hword 0x3201, 0x3230, 0xa65c, 0xa65d, 0xc65f, 0x325b, 0x3201, 0xc64f, 0x3201, 0x3201, 0xa64f, 0x3201, 0x3230, 0xa65c, 0xb65d, 0xa65f, 0x325b, 0x3201
    .hword 0x3201, 0x3238, 0x3264, 0x3266, 0x3267, 0x323a, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3238, 0x3264, 0x3266, 0x3267, 0x323a, 0x3201
    .hword 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3006, 0x3007, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201

.align 4
TheLibrary_MapConnections:
    .hword 17194
    .byte 13, 7
    .hword 17194
    .byte 13, 7

.align 4
TheLibrary_MapName:
    .string "THE LIBRARY$"

# scripts/4384_TheLibrary.s

.align 4

TheLibrary_MapInitCode:
    ldr r0, =zSkipMapExitMovement
    mov r1, #2
    strb r1, [r0]
    bx lr

.align 4
.ltorg

TheLibrary_MapInitScript:
    end

TheLibrary_Script1:
    lock
    faceplayer
    msgbox TheLibrary_Script1_Text
    release
    end

TheLibrary_Script1_Text:
    .string "I have a book that is long overdue.\n"
    .string "I think by about 6 years now?\p"
    .string "But here's a great lifehack. As long\n"
    .string "as I never return it, I'll never have\l"
    .string "to pay any fines!\p"
    .string "I feel like an evil mastermind.\n"
    .string "I should join TEAM ROCKET!\p"
    .string "Stealing Pok{EACUTE}mon as well as books?\n"
    .string "Sign me right up!$"

TheLibrary_Script2:
    lock
    faceplayer
    checkflag FLAG_POT_OF_GREED
    goto_if TRUE, TheLibrary_Script2_Done
    msgbox TheLibrary_Script2_Text
    setflag FLAG_POT_OF_GREED
    message TheLibrary_Script2_Text2
    waitmessage
    playfanfare MUS_RG_OBTAIN_KEY_ITEM
    waitfanfare
    call SyncProgressScript
TheLibrary_Script2_Done:
    msgbox TheLibrary_Script2_Text3
    release
    end

TheLibrary_Script2_Text:
    .string "Hey, I found this card lying around\n"
    .string "on this table. I have no use for it,\l"
    .string "so you can have it!$"

TheLibrary_Script2_Text2:
    .string "Obtained the Pot of Greed magic card!$"

TheLibrary_Script2_Text3:
    .string "If I understand correctly, this card\n"
    .string "allows you to draw two additional\l"
    .string "cards from your deck and add them to\l"
    .string "your hand! Such a useful effect!$"

TheLibrary_Script3:
    lock
    faceplayer
    msgbox TheLibrary_Script3_Text
    release
    end

TheLibrary_Script3_Text:
    .string "Sssh! Be quiet!\n"
    .string "This is a library!$"
