# fools2022 - autogenerated map file, please do not change!
# created from: pokeemerald/data/maps/x4528_BinaryWoodsClearing/map.json

.thumb
.include "include/constants.inc"
.org MAP_LOAD_BASE

.include "include/macros.inc"
.include "include/symbols.inc"
.include "include/map.inc"
.include "include/event.inc"
.include "include/save.inc"

BinaryWoodsClearing_MapHeader:
    .word BinaryWoodsClearing_MapLayout
    .word BinaryWoodsClearing_MapEvts
    .word NULL
    .word NULL
    .hword MUS_FALLARBOR
    .hword 0
    .byte 0
    .byte 0
    .byte WEATHER_NONE
    .byte 0
    .hword 0
    map_header_flags allow_cycling=1, allow_escaping=1, allow_running=1, show_map_name=1
    .byte 0
    # additional data specific to fools2022 maps
    .word BinaryWoodsClearing_MapInitCode+1
    .word BinaryWoodsClearing_MapConnections
    .word BinaryWoodsClearing_MapInitScript
    .word BinaryWoodsClearing_MapName
    .word 0x2819

BinaryWoodsClearing_MapLayout:
    .word 14
    .word 18
    .word BinaryWoodsClearing_MapBorder
    .word BinaryWoodsClearing_MapData
    .word gTileset_General
    .word gTileset_Petalburg

.align 4
BinaryWoodsClearing_MapObjectEvents:
    object_event 1, OBJ_EVENT_GFX_EXPERT_F, 0, 7, 13, 3, MOVEMENT_TYPE_FACE_DOWN, 0, 0, TRAINER_TYPE_NONE, 0, BinaryWoodsClearing_Script1, FLAG_BINARY_WOODS_CLEARING

.align 4
BinaryWoodsClearing_MapCoordEvents:
BinaryWoodsClearing_WarpCoordEvents:
    coord_event 6, 7, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT
    coord_event 7, 7, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT
    coord_event 8, 7, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT

.align 4
BinaryWoodsClearing_MapBGEvents:

.align 4
BinaryWoodsClearing_MapEvts:
    map_events 1, BinaryWoodsClearing_MapObjectEvents, 0, 0, 3, BinaryWoodsClearing_MapCoordEvents, 0, BinaryWoodsClearing_MapBGEvents

.align 4
BinaryWoodsClearing_MapBorder:
    .byte 0xd4, 0x01, 0xd5, 0x01, 0xdc, 0x01, 0xdd, 0x01

.align 4
BinaryWoodsClearing_MapData:
    .hword 0xc5d4, 0xb5d5, 0xa5d4, 0xb5d5, 0xc5d4, 0xc5d5, 0x31d8, 0x31da, 0xb5d4, 0xa5d5, 0xa5d4, 0xc5d5, 0xa5d4, 0xc5d5
    .hword 0xa5dc, 0xc5dd, 0xa5dc, 0xb5dd, 0xb5dc, 0xb5dd, 0x31d8, 0x31da, 0xa5dc, 0xb5dd, 0xb5dc, 0xc5dd, 0xa5dc, 0xc5dd
    .hword 0xc5d4, 0xa5d5, 0xb5d4, 0xb5d5, 0xc5d4, 0xa5d5, 0x31d8, 0x31da, 0xc5d4, 0xa5d5, 0xb5d4, 0xa5d5, 0xb5d4, 0xa5d5
    .hword 0xb5dc, 0xa5dd, 0xa5dc, 0xa5dd, 0xb5dc, 0xb5dd, 0x31d8, 0x31da, 0xc5dc, 0xa5dd, 0xb5dc, 0xa5dd, 0xb5dc, 0xc5dd
    .hword 0xa5d4, 0xc5d5, 0xc5d4, 0xb5d5, 0xa5d4, 0xb5d5, 0x31d8, 0x31da, 0xb5d4, 0xb5d5, 0xc5d4, 0xb5d5, 0xa5d4, 0xb5d5
    .hword 0xa5dc, 0xa5dd, 0xb5dc, 0xc5dd, 0xa5dc, 0xc5dd, 0x31d8, 0x31da, 0xa5dc, 0xc5dd, 0xa5dc, 0xb5dd, 0xa5dc, 0xc5dd
    .hword 0xb5d4, 0xa5d5, 0xa5d4, 0xa5d5, 0xc5d4, 0xb5d5, 0x31d8, 0x31da, 0xb5d4, 0xc5d5, 0xc5d4, 0xb5d5, 0xa5d4, 0xc5d5
    .hword 0xa5dc, 0xb5dd, 0xa5e4, 0xb5e5, 0xa5e4, 0xc5e5, 0x31d8, 0x31da, 0xb5e4, 0xb5e5, 0xa5e4, 0xc5e5, 0xa5dc, 0xa5dd
    .hword 0xb5d4, 0xb5d5, 0x3001, 0x3001, 0x3001, 0x3001, 0x31d8, 0x31da, 0x3004, 0x3001, 0x3001, 0x3001, 0xa5d4, 0xc5d5
    .hword 0xb5dc, 0xb5dd, 0x3001, 0x3001, 0x3001, 0x3001, 0x31d8, 0x31da, 0x3001, 0x3004, 0x3001, 0x3001, 0xc5dc, 0xc5dd
    .hword 0xb5d4, 0xc5d5, 0x3004, 0x3001, 0x3001, 0x31d0, 0x31d9, 0x31d9, 0x31d2, 0x3001, 0x3001, 0x3001, 0xc5d4, 0xc5d5
    .hword 0xa5dc, 0xc5dd, 0x3001, 0x3004, 0x3001, 0x31d8, 0x31d9, 0x31d9, 0x31da, 0x3001, 0x3001, 0x3001, 0xa5dc, 0xa5dd
    .hword 0xc5d4, 0xa5d5, 0x3001, 0x31d0, 0x31d1, 0x31d9, 0x31d9, 0x31d9, 0x31d9, 0x31d1, 0x31d2, 0x3001, 0xb5d4, 0xb5d5
    .hword 0xb5dc, 0xa5dd, 0x3001, 0x31e0, 0x31d9, 0x31d9, 0x31d9, 0x31d9, 0x31d9, 0x31d9, 0x31e2, 0x3001, 0xc5dc, 0xc5dd
    .hword 0xa5d4, 0xb5d5, 0x3001, 0x3001, 0x31e0, 0x31e1, 0x31e1, 0x31e1, 0x31e1, 0x31e2, 0x3004, 0x3001, 0xc5d4, 0xc5d5
    .hword 0xa5dc, 0xb5dd, 0x31ce, 0x31cf, 0x31ce, 0x31cf, 0x31ce, 0x31cf, 0x31ce, 0x31cf, 0x31ce, 0x31cf, 0xa5dc, 0xc5dd
    .hword 0xb5d4, 0xb5d5, 0xb5d4, 0xa5d5, 0xa5d4, 0xb5d5, 0xa5d4, 0xc5d5, 0xb5d4, 0xa5d5, 0xc5d4, 0xc5d5, 0xc5d4, 0xa5d5
    .hword 0xa5dc, 0xa5dd, 0xc5dc, 0xa5dd, 0xb5dc, 0xc5dd, 0xc5dc, 0xa5dd, 0xc5dc, 0xa5dd, 0xb5dc, 0xc5dd, 0xc5dc, 0xc5dd

.align 4
BinaryWoodsClearing_MapConnections:
    .hword 0x4585
    .byte 9, 158
    .hword 0x4585
    .byte 9, 158
    .hword 0x4585
    .byte 9, 158

.align 4
BinaryWoodsClearing_MapName:
    .string "WOODS CLEARING$"

# scripts/4528_BinaryWoodsClearing.s

.align 4

BinaryWoodsClearing_MapInitCode:
    bx lr

BinaryWoodsClearing_MapInitScript:
    end

BinaryWoodsClearing_Script1:
    lock
    faceplayer
    msgbox BinaryWoodsClearing_Script1_Text
    setflag FLAG_BINARY_WOODS_CLEARING
    call SyncProgressScript
    delay 16
    closemessage
    delay 16
    fadescreen 1
    removeobject 1
    fadescreen 0
    release
    end

BinaryWoodsClearing_Script1_Text:
    .string "Hello. You must have had very strong\n"
    .string "will to come all the way up here.\p"
    .string "I come here to meditate and unify with\n"
    .string "our mother nature.\p"
    .string "People are scared of nature.\n"
    .string "Natural disasters. Dangerous animals.\l"
    .string "Harsh weather. The list goes on...\p"
    .string "People distance themselves from nature\n"
    .string "out of fear. I do things differently.\p"
    .string "I want to become one with nature and\n"
    .string "to better understand it.\p"
    .string "Thank you for coming here.\n"
    .string "You're a great conversation partner.$"


