# fools2022 - autogenerated map file, please do not change!
# created from: pokeemerald/data/maps/x4787_SouthernEncampment/map.json

.thumb
.include "include/constants.inc"
.org MAP_LOAD_BASE

.include "include/macros.inc"
.include "include/symbols.inc"
.include "include/map.inc"
.include "include/event.inc"
.include "include/save.inc"

SouthernEncampment_MapHeader:
    .word SouthernEncampment_MapLayout
    .word SouthernEncampment_MapEvts
    .word NULL
    .word NULL
    .hword MUS_RG_FUCHSIA
    .hword 0
    .byte 0
    .byte 0
    .byte WEATHER_NONE
    .byte 0
    .hword 0
    map_header_flags allow_cycling=1, allow_escaping=1, allow_running=1, show_map_name=1
    .byte 0
    # additional data specific to fools2022 maps
    .word SouthernEncampment_MapInitCode+1
    .word SouthernEncampment_MapConnections
    .word SouthernEncampment_MapInitScript
    .word SouthernEncampment_MapName
    .word 0x0400

SouthernEncampment_MapLayout:
    .word 10
    .word 9
    .word SouthernEncampment_MapBorder
    .word SouthernEncampment_MapData
    .word gTileset_Building
    .word gTileset_GenericBuilding

.align 4
SouthernEncampment_MapObjectEvents:
    object_event 1, OBJ_EVENT_GFX_BOY_3, 0, 2, 4, 3, MOVEMENT_TYPE_FACE_RIGHT, 0, 0, TRAINER_TYPE_NONE, 0, SouthernEncampment_Script1, 0

.align 4
SouthernEncampment_MapCoordEvents:
SouthernEncampment_WarpCoordEvents:
    coord_event 3, 8, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT
    coord_event 4, 8, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT

.align 4
SouthernEncampment_MapBGEvents:

.align 4
SouthernEncampment_MapEvts:
    map_events 1, SouthernEncampment_MapObjectEvents, 0, 0, 2, SouthernEncampment_MapCoordEvents, 0, SouthernEncampment_MapBGEvents

.align 4
SouthernEncampment_MapBorder:
    .byte 0x01, 0x02, 0x01, 0x02, 0x01, 0x02, 0x01, 0x02

.align 4
SouthernEncampment_MapData:
    .hword 0xa686, 0xb687, 0xb679, 0xc67a, 0xa605, 0xb607, 0xb605, 0xc605, 0xa605, 0xb605
    .hword 0xa68e, 0xa68f, 0xb681, 0xc682, 0xb60d, 0xb60f, 0xb60d, 0xa60d, 0xb690, 0xc690
    .hword 0x3296, 0x3297, 0x3289, 0x328a, 0x3224, 0x3224, 0x3224, 0x3224, 0xb698, 0xa698
    .hword 0x3239, 0x3235, 0x3236, 0x3236, 0x3236, 0x3236, 0x3236, 0x3237, 0x3223, 0x3223
    .hword 0x3239, 0x323d, 0x32e1, 0xb648, 0xc649, 0x32e2, 0x323e, 0x323f, 0x3223, 0x3223
    .hword 0x3239, 0x323d, 0x32e1, 0xa650, 0xa651, 0x32e2, 0x323e, 0x323f, 0x3223, 0x3223
    .hword 0x3239, 0x3245, 0x3246, 0x3246, 0x3246, 0x3246, 0x3246, 0x3247, 0x3223, 0x3223
    .hword 0x3239, 0x3223, 0x3223, 0x3223, 0x3223, 0x3223, 0x3223, 0x3223, 0x3223, 0x3222
    .hword 0x3239, 0x3223, 0x3223, 0x0208, 0x0209, 0x3223, 0x3223, 0x3223, 0x3223, 0xb62a

.align 4
SouthernEncampment_MapConnections:
    .hword 18219
    .byte 9, 16
    .hword 18219
    .byte 9, 16

.align 4
SouthernEncampment_MapName:
    .string "SOUTHERN CAMP$"

# scripts/4787_SouthernEncampment.s

.align 4

SouthernEncampment_MapInitCode:
    ldr r0, =zSkipMapExitMovement
    mov r1, #2
    strb r1, [r0]
    bx lr

.align 4
.ltorg

SouthernEncampment_MapInitScript:
    end

SouthernEncampment_Script1:
    lock
    faceplayer
    checkflag FLAG_FLUTE_RETURNED
    goto_if TRUE, SouthernEncampment_Script1_PlaySong
    checkflag FLAG_FLUTE_RECEIVED
    goto_if TRUE, SouthernEncampment_Script1_GiveFlute
    msgbox SouthernEncampment_Script1_Text
    release
    end

SouthernEncampment_Script1_GiveFlute:
    msgbox SouthernEncampment_Script1_Text1
    waitmessage
    playfanfare MUS_RG_OBTAIN_KEY_ITEM
    waitfanfare
    setflag FLAG_FLUTE_RETURNED
    call SyncProgressScript
    release
    end

SouthernEncampment_Script1_PlaySong:
    msgbox SouthernEncampment_Script1_Text2
    closemessage
    fadeoutbgm 1
    delay 50
    message SouthernEncampment_Script1_Text3
    waitmessage
    delay 50
    message SouthernEncampment_Script1_Text4
    waitmessage
    delay 50
    message SouthernEncampment_Script1_Text5
    waitmessage
    message SouthernEncampment_Script1_Text6
    waitmessage
    delay 80
    fadeinbgm 1
    msgbox SouthernEncampment_Script1_Text7
    release
    end

SouthernEncampment_Script1_Text:
    .string "No! That's horrible!\n"
    .string "That's a complete disaster!\l"
    .string "I lost my POK{EACUTE} FLUTE!\p"
    .string "I always loved playing it whenever I\n"
    .string "felt down, but now I can't!\p"
    .string "Please, help me find my lost flute and\n"
    .string "return it to me!$"

SouthernEncampment_Script1_Text1:
    .string "Is that...\n"
    .string "Yes, I couldn't mistake it!\p"
    .string "You found my flute! Big thanks for\n"
    .string "all of your hard work!$"

SouthernEncampment_Script1_Text2:
    .string "Now that I have my flute back,\n"
    .string "I can play you a cool song!$"

SouthernEncampment_Script1_Text3:
    .string "{PLAY_SE}{SE_NOTE_D}If {WAIT_SE}"
    .string "{PLAY_SE}{SE_NOTE_D}you're {WAIT_SE}"
    .string "{PLAY_SE}{SE_NOTE_G}hap{WAIT_SE}"
    .string "{PLAY_SE}{SE_NOTE_G}py {WAIT_SE}"
    .string "{PLAY_SE}{SE_NOTE_G}and {WAIT_SE}"
    .string "{PLAY_SE}{SE_NOTE_G}you {WAIT_SE}"
    .string "{PLAY_SE}{SE_NOTE_G}know {WAIT_SE}"
    .string "{PLAY_SE}{SE_NOTE_G}it,\n{WAIT_SE}"
    .string "{PLAY_SE}{SE_NOTE_F}syn{WAIT_SE}"
    .string "{PLAY_SE}{SE_NOTE_G}tax {WAIT_SE}"
    .string "{PLAY_SE}{SE_NOTE_A}error!{WAIT_SE}"
    .string "$"

SouthernEncampment_Script1_Text4:
    .string "{PLAY_SE}{SE_NOTE_D}If {WAIT_SE}"
    .string "{PLAY_SE}{SE_NOTE_D}you're {WAIT_SE}"
    .string "{PLAY_SE}{SE_NOTE_A}hap{WAIT_SE}"
    .string "{PLAY_SE}{SE_NOTE_A}py {WAIT_SE}"
    .string "{PLAY_SE}{SE_NOTE_A}and {WAIT_SE}"
    .string "{PLAY_SE}{SE_NOTE_A}you {WAIT_SE}"
    .string "{PLAY_SE}{SE_NOTE_A}know {WAIT_SE}"
    .string "{PLAY_SE}{SE_NOTE_A}it,\n{WAIT_SE}"
    .string "{PLAY_SE}{SE_NOTE_G}syn{WAIT_SE}"
    .string "{PLAY_SE}{SE_NOTE_A}tax {WAIT_SE}"
    .string "{PLAY_SE}{SE_NOTE_B}error!{WAIT_SE}"
    .string "$"

SouthernEncampment_Script1_Text5:
    .string "{PLAY_SE}{SE_NOTE_B}If {WAIT_SE}"
    .string "{PLAY_SE}{SE_NOTE_B}you're {WAIT_SE}"
    .string "{PLAY_SE}{SE_NOTE_C_HIGH}hap{WAIT_SE}"
    .string "{PLAY_SE}{SE_NOTE_C_HIGH}py {WAIT_SE}"
    .string "{PLAY_SE}{SE_NOTE_C_HIGH}and {WAIT_SE}"
    .string "{PLAY_SE}{SE_NOTE_C_HIGH}you {WAIT_SE}"
    .string "{PLAY_SE}{SE_NOTE_E}know {WAIT_SE}"
    .string "{PLAY_SE}{SE_NOTE_E}it,\n{WAIT_SE}"
    .string "{PLAY_SE}{SE_NOTE_C_HIGH}and {WAIT_SE}"
    .string "{PLAY_SE}{SE_NOTE_C_HIGH}you {WAIT_SE}"
    .string "{PLAY_SE}{SE_NOTE_B}rea{WAIT_SE}"
    .string "{PLAY_SE}{SE_NOTE_B}lly {WAIT_SE}"
    .string "{PLAY_SE}{SE_NOTE_B}want {WAIT_SE}"
    .string "{PLAY_SE}{SE_NOTE_A}to {WAIT_SE}"
    .string "{PLAY_SE}{SE_NOTE_G}show {WAIT_SE}"
    .string "{PLAY_SE}{SE_NOTE_G}it,"
    .string "$"

SouthernEncampment_Script1_Text6:
    .string "{WAIT_SE}{PLAY_SE}{SE_NOTE_B}If {WAIT_SE}"
    .string "{PLAY_SE}{SE_NOTE_B}you're {WAIT_SE}"
    .string "{PLAY_SE}{SE_NOTE_A}hap{WAIT_SE}"
    .string "{PLAY_SE}{SE_NOTE_A}py {WAIT_SE}"
    .string "{PLAY_SE}{SE_NOTE_A}and {WAIT_SE}"
    .string "{PLAY_SE}{SE_NOTE_G}you {WAIT_SE}"
    .string "{PLAY_SE}{SE_NOTE_F}know {WAIT_SE}"
    .string "{PLAY_SE}{SE_NOTE_F}it,\n{WAIT_SE}"
    .string "{PLAY_SE}{SE_NOTE_E}syn{WAIT_SE}"
    .string "{PLAY_SE}{SE_NOTE_F}tax {WAIT_SE}"
    .string "{PLAY_SE}{SE_NOTE_G}error!{WAIT_SE}"
    .string "$"

SouthernEncampment_Script1_Text7:
    .string "How did you like it?\n"
    .string "Be gentle, I'm still practicing!$"
