# fools2022 - autogenerated map file, please do not change!
# created from: pokeemerald/data/maps/x4788_SouthernEncampment/map.json

.thumb
.include "include/constants.inc"
.org MAP_LOAD_BASE

.include "include/macros.inc"
.include "include/symbols.inc"
.include "include/map.inc"
.include "include/event.inc"
.include "include/save.inc"

SouthernEncampment_MapHeader:
    .word SouthernEncampment_MapLayout
    .word SouthernEncampment_MapEvts
    .word NULL
    .word NULL
    .hword MUS_RG_FUCHSIA
    .hword 0
    .byte 0
    .byte 0
    .byte WEATHER_NONE
    .byte 0
    .hword 0
    map_header_flags allow_cycling=1, allow_escaping=1, allow_running=1, show_map_name=1
    .byte 0
    # additional data specific to fools2022 maps
    .word SouthernEncampment_MapInitCode+1
    .word SouthernEncampment_MapConnections
    .word SouthernEncampment_MapInitScript
    .word SouthernEncampment_MapName
    .word 0x0400

SouthernEncampment_MapLayout:
    .word 10
    .word 9
    .word SouthernEncampment_MapBorder
    .word SouthernEncampment_MapData
    .word gTileset_Building
    .word gTileset_GenericBuilding

.align 4
SouthernEncampment_MapObjectEvents:
    object_event 1, OBJ_EVENT_GFX_LUCY, 0, 5, 2, 3, MOVEMENT_TYPE_FACE_UP, 0, 0, TRAINER_TYPE_NONE, 0, SouthernCamp_Script1, 0

.align 4
SouthernEncampment_MapCoordEvents:
SouthernEncampment_WarpCoordEvents:
    coord_event 3, 8, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT
    coord_event 4, 8, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT

.align 4
SouthernEncampment_MapBGEvents:

.align 4
SouthernEncampment_MapEvts:
    map_events 1, SouthernEncampment_MapObjectEvents, 0, 0, 2, SouthernEncampment_MapCoordEvents, 0, SouthernEncampment_MapBGEvents

.align 4
SouthernEncampment_MapBorder:
    .byte 0x01, 0x02, 0x01, 0x02, 0x01, 0x02, 0x01, 0x02

.align 4
SouthernEncampment_MapData:
    .hword 0xa686, 0xb687, 0xc679, 0xa67a, 0xb605, 0xb607, 0xc605, 0xb605, 0xa605, 0xb605
    .hword 0xb68e, 0xb68f, 0xa681, 0xb682, 0xc60d, 0xc60f, 0xc60d, 0xc60d, 0xa690, 0xb690
    .hword 0x3296, 0x3297, 0x3289, 0x328a, 0x3224, 0x3224, 0x3224, 0x3224, 0xa698, 0xc698
    .hword 0x3239, 0x3235, 0x3236, 0x3236, 0x3236, 0x3236, 0x3236, 0x3237, 0x3223, 0x3223
    .hword 0x3239, 0x323d, 0x32e1, 0xb648, 0xa649, 0x32e2, 0x323e, 0x323f, 0x3223, 0x3223
    .hword 0x3239, 0x323d, 0x32e1, 0xb650, 0xc651, 0x32e2, 0x323e, 0x323f, 0x3223, 0x3223
    .hword 0x3239, 0x3245, 0x3246, 0x3246, 0x3246, 0x3246, 0x3246, 0x3247, 0x3223, 0x3223
    .hword 0x3239, 0x3223, 0x3223, 0x3223, 0x3223, 0x3223, 0x3223, 0x3223, 0x3223, 0x3222
    .hword 0x3239, 0x3223, 0x3223, 0x0208, 0x0209, 0x3223, 0x3223, 0x3223, 0x3223, 0xb62a

.align 4
SouthernEncampment_MapConnections:
    .hword 18219
    .byte 15, 16
    .hword 18219
    .byte 15, 16

.align 4
SouthernEncampment_MapName:
    .string "SOUTHERN CAMP$"

# scripts/4788_SouthernEncampment.s

.align 4

SouthernEncampment_MapInitCode:
    ldr r0, =zSkipMapExitMovement
    mov r1, #2
    strb r1, [r0]
    bx lr

SouthernCamp_ChangeToFeminineAndSetTargetMap:
    ldr r0, =gSaveBlock2Ptr
    ldr r0, [r0]
    mov r1, #1
    strb r1, [r0, #0x08]
    b SouthernCamp_SetTargetMap
SouthernCamp_ChangeFromFeminineAndSetTargetMap:
    ldr r0, =gSaveBlock2Ptr
    ldr r0, [r0]
    mov r1, #0
    strb r1, [r0, #0x08]
SouthernCamp_SetTargetMap:
    ldr r0, =zWarpTargetData
    ldr r1, =0x100f472b
    str r1, [r0]
    ldr r0, =zWarpTargetDirection
    mov r1, #0
    strb r1, [r0]
    bx lr

.align 4
.ltorg

SouthernEncampment_MapInitScript:
    end

SouthernCamp_Script1:
    lock
    faceplayer
    checkflag FLAG_HEART_SCALE_RETURNED
    goto_if TRUE, SouthernCamp_Script1_Transform
    checkflag FLAG_MANSION_GOT_SCALE
    goto_if TRUE, SouthernCamp_Script1_GiveScale
    msgbox SouthernCamp_Script1_Text
    release
    end

SouthernCamp_Script1_GiveScale:
    setflag FLAG_HEART_SCALE_RETURNED
    msgbox SouthernCamp_Script1_Text
    message SouthernCamp_Script1_Text2
    waitmessage
    playfanfare MUS_RG_OBTAIN_KEY_ITEM
    waitfanfare
    call SyncProgressScript
    msgbox SouthernCamp_Script1_Text3
    release
    end

SouthernCamp_Script1_Transform:
    checkplayergender
    compare VAR_RESULT, MALE
    goto_if_eq SouthernCamp_Script1_MToF
SouthernCamp_Script1_FToM:
    msgbox SouthernCamp_Script1_Text7, MSGBOX_YESNO
    compare VAR_RESULT, NO
    goto_if_eq SouthernCamp_Script1_NoToM
    msgbox SouthernCamp_Script1_Text9
    playse SE_PIKE_CURTAIN_CLOSE
    fadescreen 1
    waitse
    callnative SouthernCamp_ChangeFromFeminineAndSetTargetMap
    goto WARP_SCRIPT
SouthernCamp_Script1_MToF:
    msgbox SouthernCamp_Script1_Text4, MSGBOX_YESNO
    compare VAR_RESULT, NO
    goto_if_eq SouthernCamp_Script1_NoToF
    msgbox SouthernCamp_Script1_Text6
    playse SE_PIKE_CURTAIN_CLOSE
    fadescreen 1
    waitse
    callnative SouthernCamp_ChangeToFeminineAndSetTargetMap
    goto WARP_SCRIPT
SouthernCamp_Script1_NoToF:
    msgbox SouthernCamp_Script1_Text5
    release
    end
SouthernCamp_Script1_NoToM:
    msgbox SouthernCamp_Script1_Text8
    release
    end

SouthernCamp_Script1_Text:
    .string "Oh, hi! I might look like a girl, but I'm\n"
    .string "actually a boy.\p"
    .string "Say, have you perhaps stumbled across\n"
    .string "a HEART SCALE?\p"
    .string "I think it would make for a really cute\n"
    .string "head accessory, but I have trouble\l"
    .string "finding any around here...$"

SouthernCamp_Script1_Text2:
    .string "Wow, you actually have a HEART SCALE!\n"
    .string "Thank you so much!$"

SouthernCamp_Script1_Text3:
    .string "I've been looking for one for years!\n"
    .string "I don't know how I can repay you.\p"
    .string "Well, if you wanted, I could teach you\n"
    .string "the sacred arts of crossdressing.\p"
    .string "Just speak to me if you ever wanted to\n"
    .string "take up a feminine look.$"

SouthernCamp_Script1_Text4:
    .string "Oh, hi! I might look like a girl, but I'm\n"
    .string "actually a boy.\p"
    .string "Are you inspired? Do you perhaps want\n"
    .string "to take up a feminine look yourself?$"

SouthernCamp_Script1_Text5:
    .string "No? That's OK. After all, people can\n"
    .string "be really judgmental around here.\p"
    .string "You do not want to end up in Deliria,\n"
    .string "trust me!$"

SouthernCamp_Script1_Text6:
    .string "Great! If I recall correctly, I happen\n"
    .string "to have a spare set of femboy attire.\l"
    .string "This will only take a minute...$"

SouthernCamp_Script1_Text7:
    .string "Oh, hi! I might look like a girl, but I'm\n"
    .string "actually a boy. Just like you!\p"
    .string "Are you satisfied with your new look?\n"
    .string "Or do you want to swap back?$"

SouthernCamp_Script1_Text8:
    .string "I understand. Once you put on the cat\n"
    .string "ears, you never go back. Ha ha!$"

SouthernCamp_Script1_Text9:
    .string "Okay! Let me get your original clothes\n"
    .string "real quick!$"
