# fools2022 - autogenerated map file, please do not change!
# created from: pokeemerald/data/maps/x4B3A_HiddenRetreat/map.json

.thumb
.include "include/constants.inc"
.org MAP_LOAD_BASE

.include "include/macros.inc"
.include "include/symbols.inc"
.include "include/map.inc"
.include "include/event.inc"
.include "include/save.inc"

HiddenRetreat_MapHeader:
    .word HiddenRetreat_MapLayout
    .word HiddenRetreat_MapEvts
    .word NULL
    .word NULL
    .hword MUS_RG_ROUTE24
    .hword 0
    .byte 0
    .byte 0
    .byte WEATHER_NONE
    .byte 0
    .hword 0
    map_header_flags allow_cycling=1, allow_escaping=1, allow_running=1, show_map_name=1
    .byte 0
    # additional data specific to fools2022 maps
    .word HiddenRetreat_MapInitCode+1
    .word HiddenRetreat_MapConnections
    .word HiddenRetreat_MapInitScript
    .word HiddenRetreat_MapName
    .word 0x2819

HiddenRetreat_MapLayout:
    .word 20
    .word 12
    .word HiddenRetreat_MapBorder
    .word HiddenRetreat_MapData
    .word gTileset_General
    .word gTileset_Rustboro

.align 4
HiddenRetreat_MapObjectEvents:
    object_event 1, OBJ_EVENT_GFX_CUTTABLE_TREE, 0, 14, 3, 3, MOVEMENT_TYPE_NONE, 0, 0, TRAINER_TYPE_NONE, 0, EventScript_CutTree, 0x12
    object_event 2, OBJ_EVENT_GFX_CUTTABLE_TREE, 0, 15, 2, 3, MOVEMENT_TYPE_NONE, 0, 0, TRAINER_TYPE_NONE, 0, EventScript_CutTree, 0x13
    object_event 3, OBJ_EVENT_GFX_MAGMA_MEMBER_M, 0, 14, 2, 3, MOVEMENT_TYPE_FACE_UP, 0, 0, TRAINER_TYPE_NONE, 0, HiddenRetreat_Script1, 0

.align 4
HiddenRetreat_MapCoordEvents:
HiddenRetreat_WarpCoordEvents:
    coord_event 7, 6, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT
    coord_event 7, 7, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT
    coord_event 7, 8, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT
    coord_event 7, 9, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT

.align 4
HiddenRetreat_MapBGEvents:

.align 4
HiddenRetreat_MapEvts:
    map_events 3, HiddenRetreat_MapObjectEvents, 0, 0, 4, HiddenRetreat_MapCoordEvents, 0, HiddenRetreat_MapBGEvents

.align 4
HiddenRetreat_MapBorder:
    .byte 0xd4, 0x01, 0xd5, 0x01, 0xdc, 0x01, 0xdd, 0x01

.align 4
HiddenRetreat_MapData:
    .hword 0xc5d4, 0xb5d5, 0xa5d4, 0xa5d5, 0xa5d4, 0xa5d5, 0xb5d4, 0xc5d5, 0xa5d4, 0xc5d5, 0xa5d4, 0xa5d5, 0xa5d4, 0xa5d5, 0xc5d4, 0xa5d5, 0xc5d4, 0xa5d5, 0xa5d4, 0xa5d5
    .hword 0xc5dc, 0xb5dd, 0xb5dc, 0xc5dd, 0xb5dc, 0xa5dd, 0xa5dc, 0xa5dd, 0xc5e4, 0xc5e5, 0xc5e4, 0xa5e5, 0xb5dc, 0xa5dd, 0xb5e4, 0xb5e5, 0xb5dc, 0xb5dd, 0xb5dc, 0xa5dd
    .hword 0xa5d4, 0xb5d5, 0xa5d4, 0xb5d5, 0xc5d4, 0xa5d5, 0xb5d4, 0xb5d5, 0xa6d6, 0xa6b7, 0xc6b7, 0xa6d7, 0xb5d4, 0xb5d5, 0x3001, 0x3001, 0xb5d4, 0xa5d5, 0xb5d4, 0xa5d5
    .hword 0xc5dc, 0xa5dd, 0xa5dc, 0xc5dd, 0xc5dc, 0xc5dd, 0xb5dc, 0xb5dd, 0x3001, 0x3001, 0x3001, 0x3001, 0xb5e4, 0xc5e5, 0x3001, 0x3001, 0xc5e4, 0xa5e5, 0xa5dc, 0xb5dd
    .hword 0xa5d4, 0xb5d5, 0xa5d4, 0xa5d5, 0xb5d4, 0xa5d5, 0xc5d4, 0xb5d5, 0x3001, 0x3001, 0x3001, 0x3001, 0x3001, 0x3001, 0x3118, 0x311a, 0x3001, 0x3001, 0xa5d4, 0xa5d5
    .hword 0xc5e4, 0xa5e5, 0xa5e4, 0xa5e5, 0xc5e4, 0xa5e5, 0xa5e4, 0xb5e5, 0x3004, 0x3001, 0x3004, 0x3001, 0x3001, 0x3001, 0x3120, 0x3122, 0x3004, 0x3001, 0xb5dc, 0xc5dd
    .hword 0x3001, 0x3001, 0x3001, 0x3001, 0x3001, 0x3001, 0x3001, 0x3001, 0x3001, 0x3004, 0x3001, 0x3004, 0x3001, 0x3001, 0x3120, 0x3122, 0x3001, 0x3004, 0xb5d4, 0xb5d5
    .hword 0x3119, 0x3119, 0x3119, 0x3119, 0x3119, 0x3119, 0x3119, 0x3119, 0x3119, 0x3119, 0x3119, 0x3119, 0x3119, 0x3119, 0x3121, 0x3122, 0x3004, 0x3001, 0xa5dc, 0xc5dd
    .hword 0x3129, 0x3129, 0x3129, 0x3129, 0x3129, 0x3129, 0x3129, 0x3129, 0x3129, 0x3129, 0x3129, 0x3129, 0x3129, 0x3129, 0x3129, 0x312a, 0x3001, 0x3004, 0xa5d4, 0xa5d5
    .hword 0x31ce, 0x31cf, 0x31ce, 0x31cf, 0x31ce, 0x31cf, 0x31ce, 0x31cf, 0x31ce, 0x31cf, 0x31ce, 0x31cf, 0x31ce, 0x31cf, 0x31ce, 0x31cf, 0x31ce, 0x31cf, 0xb5dc, 0xb5dd
    .hword 0xa5d4, 0xb5d5, 0xa5d4, 0xa5d5, 0xb5d4, 0xb5d5, 0xb5d4, 0xc5d5, 0xa5d4, 0xa5d5, 0xc5d4, 0xb5d5, 0xa5d4, 0xa5d5, 0xc5d4, 0xa5d5, 0xb5d4, 0xb5d5, 0xc5d4, 0xa5d5
    .hword 0xb5dc, 0xb5dd, 0xc5dc, 0xb5dd, 0xb5dc, 0xb5dd, 0xb5dc, 0xa5dd, 0xc5dc, 0xa5dd, 0xc5dc, 0xa5dd, 0xc5dc, 0xb5dd, 0xc5dc, 0xc5dd, 0xc5dc, 0xc5dd, 0xb5dc, 0xb5dd

.align 4
HiddenRetreat_MapConnections:
    .hword 18996
    .byte 147, 7
    .hword 18996
    .byte 147, 7
    .hword 18996
    .byte 147, 7
    .hword 18996
    .byte 147, 7

.align 4
HiddenRetreat_MapName:
    .string "HIDDEN RETREAT$"

# scripts/4B3A_HiddenRetreat.s

.align 4

HiddenRetreat_MapInitCode:
    bx lr

HiddenRetreat_MapInitScript:
    end

HiddenRetreat_Script1:
    lock
    faceplayer
    msgbox HiddenRetreat_Script1_Text
    checkflag FLAG_HIDDEN_RETREAT
    goto_if TRUE, HiddenRetreat_Script1_NoMark
    setflag FLAG_HIDDEN_RETREAT
    call SyncProgressScript
HiddenRetreat_Script1_NoMark:
    release
    end

HiddenRetreat_Script1_Text:
    .string "What? How did you know I concealed\n"
    .string "myself within those trees?\p"
    .string "You have an overhead view?\n"
    .string "But that's cheating!\p"
    .string "Please don't tell anyone I'm here,\n"
    .string "kay-o?$"


EventScript_CutTree:
    lock
    faceplayer
    msgbox EventScript_CutTree_Text
    release
    end

EventScript_CutTree_Text:
    .string "redacted$"
