# fools2022 - autogenerated map file, please do not change!
# created from: pokeemerald/data/maps/x506F_WesternRelic/map.json

.thumb
.include "include/constants.inc"
.org MAP_LOAD_BASE

.include "include/macros.inc"
.include "include/symbols.inc"
.include "include/map.inc"
.include "include/event.inc"
.include "include/save.inc"

WesternRelic_MapHeader:
    .word WesternRelic_MapLayout
    .word WesternRelic_MapEvts
    .word NULL
    .word NULL
    .hword MUS_SEALED_CHAMBER
    .hword 0
    .byte 0
    .byte 0
    .byte WEATHER_NONE
    .byte 0
    .hword 0
    map_header_flags allow_cycling=1, allow_escaping=1, allow_running=1, show_map_name=1
    .byte 0
    # additional data specific to fools2022 maps
    .word WesternRelic_MapInitCode+1
    .word WesternRelic_MapConnections
    .word WesternRelic_MapInitScript
    .word WesternRelic_MapName
    .word 0x2819

WesternRelic_MapLayout:
    .word 9
    .word 12
    .word WesternRelic_MapBorder
    .word WesternRelic_MapData
    .word gTileset_General
    .word gTileset_Cave

.align 4
WesternRelic_MapObjectEvents:
    object_event 1, OBJ_EVENT_GFX_ITEM_BALL, 0, 4, 5, 3, MOVEMENT_TYPE_NONE, 0, 0, TRAINER_TYPE_NONE, 0, WesternRelic_Script1, FLAG_WESTERN_RELIC_ITEM

.align 4
WesternRelic_MapCoordEvents:
WesternRelic_WarpCoordEvents:
    coord_event 4, 10, 0, SCRIPT_WARP_TRIGGER, 0, WARP_SCRIPT

.align 4
WesternRelic_MapBGEvents:
    bg_event 4, 4, 0, BG_EVENT_PLAYER_FACING_ANY, WesternRelic_Script2

.align 4
WesternRelic_MapEvts:
    map_events 1, WesternRelic_MapObjectEvents, 0, 0, 1, WesternRelic_MapCoordEvents, 1, WesternRelic_MapBGEvents

.align 4
WesternRelic_MapBorder:
    .byte 0x11, 0x02, 0x11, 0x02, 0x11, 0x02, 0x11, 0x02

.align 4
WesternRelic_MapData:
    .hword 0xb61b, 0xc619, 0xc619, 0xb619, 0xa619, 0xa619, 0xc619, 0xa619, 0xb61c
    .hword 0xa612, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0xc610
    .hword 0xa612, 0x3201, 0x3201, 0xa608, 0xc609, 0xb60a, 0x3201, 0x3201, 0xc610
    .hword 0xa612, 0x3201, 0x3201, 0xc610, 0xa611, 0xb612, 0x3201, 0x3201, 0xc610
    .hword 0xb612, 0x3201, 0x3201, 0xc618, 0xa635, 0xb61a, 0x3201, 0x3201, 0xa610
    .hword 0xa612, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0xb610
    .hword 0xa612, 0x3201, 0xb603, 0x3201, 0x3201, 0x3201, 0xb603, 0x3201, 0xc610
    .hword 0xc612, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0xc610
    .hword 0xc612, 0x3201, 0xc603, 0x3201, 0x3201, 0x3201, 0xb603, 0x3201, 0xc610
    .hword 0xa612, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0xc610
    .hword 0xa612, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0x3201, 0xc610
    .hword 0xa609, 0xb609, 0xa609, 0xb658, 0xa659, 0xa65a, 0xb609, 0xc609, 0xc609

.align 4
WesternRelic_MapConnections:
    .hword 9005
    .byte 32, 13

.align 4
WesternRelic_MapName:
    .string "WESTERN RELIC$"

# scripts/506F_WesternRelic.s

.align 4

WesternRelic_MapInitCode:
    ldr r0, =zSkipMapExitMovement
    mov r1, #2
    strb r1, [r0]
    bx lr

.align 4
.ltorg

WesternRelic_MapInitScript:
    end

WesternRelic_Script1:
    lock
    removeobject 1
    giveitem 4
    setflag FLAG_RECEIVED_BALL9
    setflag FLAG_WESTERN_RELIC_ITEM
    call SyncProgressScript
    release
    end

WesternRelic_Script2:
    lock
    braillemessage WesternRelic_Braille
	waitbuttonpress
	closebraillemessage
    releaseall
    end

WesternRelic_Braille:
    .byte 13, 37, 69, 4, 2, 0
    .braille "TRENDY PHRASE$"

